// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gaussian,hls_ip_2013_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=1.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.049000,HLS_SYN_LAT=318417487,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=6,HLS_SYN_FF=5834,HLS_SYN_LUT=3343}" *)

module gaussian (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_r_address1,
        in_r_ce1,
        in_r_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [20:0] in_r_address0;
output   in_r_ce0;
input  [15:0] in_r_q0;
output  [20:0] in_r_address1;
output   in_r_ce1;
input  [15:0] in_r_q1;
output  [20:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [15:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[20:0] in_r_address0;
reg in_r_ce0;
reg[20:0] in_r_address1;
reg in_r_ce1;
reg out_r_ce0;
reg out_r_we0;
reg   [7:0] ap_CS_fsm = 8'b00000000;
reg   [15:0] reg_186;
reg   [15:0] reg_190;
wire   [31:0] grp_fu_180_p1;
reg   [31:0] reg_194;
wire   [31:0] grp_fu_164_p2;
reg   [31:0] reg_199;
wire   [31:0] grp_fu_160_p2;
reg   [31:0] reg_205;
wire   [0:0] exitcond_fu_223_p2;
reg   [0:0] exitcond_reg_516;
wire   [10:0] grp_fu_211_p2;
reg   [10:0] tmp_i_12_reg_520;
wire   [10:0] grp_fu_217_p2;
reg   [10:0] i_reg_526;
wire   [10:0] grp_fu_229_p2;
reg   [10:0] tmp6_i_reg_533;
wire   [10:0] grp_fu_235_p2;
reg   [10:0] j_reg_538;
wire   [0:0] exitcond1_fu_241_p2;
wire   [22:0] grp_fu_271_p2;
reg   [22:0] p_addr_reg_557;
wire   [23:0] tmp_4_i_trn_cast_fu_277_p1;
reg   [23:0] tmp_4_i_trn_cast_reg_562;
wire   [23:0] p_addr_cast_fu_281_p1;
reg   [23:0] p_addr_cast_reg_569;
wire   [23:0] tmp_8_i_trn_cast_fu_290_p1;
reg   [23:0] tmp_8_i_trn_cast_reg_576;
wire   [23:0] grp_fu_284_p2;
reg   [23:0] p_addr2_reg_583;
wire   [23:0] grp_fu_293_p2;
reg   [23:0] p_addr3_reg_588;
wire   [63:0] tmp_6_i3_fu_315_p1;
wire   [23:0] tmp_12_i_trn_cast_fu_325_p1;
reg   [23:0] tmp_12_i_trn_cast_reg_613;
wire   [31:0] grp_fu_183_p1;
reg   [31:0] tmp_i_reg_620;
wire   [23:0] grp_fu_328_p2;
reg   [23:0] p_addr5_reg_625;
wire   [63:0] tmp_14_i5_fu_341_p1;
wire   [31:0] grp_fu_169_p2;
reg   [31:0] tmp_10_i_reg_650;
wire   [22:0] grp_fu_368_p2;
reg   [22:0] p_addr8_reg_655;
wire   [23:0] p_addr8_cast_fu_374_p1;
reg   [23:0] p_addr8_cast_reg_660;
wire   [23:0] grp_fu_377_p2;
reg   [23:0] p_addr9_reg_667;
wire   [63:0] tmp_18_i6_fu_390_p1;
wire   [22:0] grp_fu_417_p2;
reg   [22:0] p_addr6_reg_692;
wire   [23:0] p_addr6_cast_fu_431_p1;
wire   [23:0] grp_fu_423_p2;
reg   [23:0] p_addr11_reg_704;
wire   [23:0] grp_fu_427_p2;
reg   [23:0] p_addr10_reg_709;
wire   [23:0] grp_fu_434_p2;
reg   [23:0] p_addr7_reg_714;
wire   [23:0] grp_fu_439_p2;
reg   [23:0] p_addr4_reg_719;
wire   [23:0] grp_fu_444_p2;
reg   [23:0] p_addr1_reg_724;
wire   [63:0] tmp_8_fu_452_p1;
reg   [63:0] tmp_8_reg_729;
wire   [63:0] tmp_22_i7_fu_481_p1;
reg   [15:0] in_load_7_reg_759;
reg   [15:0] in_load_8_reg_769;
wire   [63:0] tmp_26_i8_fu_494_p1;
wire   [63:0] tmp_30_i9_fu_499_p1;
wire   [63:0] tmp_34_i1_fu_504_p1;
wire   [63:0] tmp_38_i1_fu_508_p1;
wire   [15:0] tmp_14_fu_512_p1;
reg   [15:0] tmp_14_reg_794;
reg   [10:0] indvar1_i_reg_135;
reg   [10:0] indvar_i_reg_147;
wire   [63:0] tmp_2_fu_302_p1;
wire   [63:0] tmp_3_fu_310_p1;
wire   [63:0] tmp_4_fu_336_p1;
wire   [63:0] tmp_7_fu_385_p1;
wire   [63:0] tmp_9_fu_460_p1;
wire   [63:0] tmp_11_fu_468_p1;
wire   [63:0] tmp_12_fu_476_p1;
wire   [63:0] tmp_13_fu_489_p1;
reg   [31:0] grp_fu_160_p0;
reg   [31:0] grp_fu_160_p1;
wire   [31:0] grp_fu_164_p0;
reg   [31:0] grp_fu_164_p1;
wire   [31:0] grp_fu_169_p0;
wire   [31:0] grp_fu_169_p1;
wire   [31:0] grp_fu_177_p0;
reg   [63:0] grp_fu_180_p0;
wire   [63:0] grp_fu_183_p0;
wire   [10:0] grp_fu_211_p0;
wire   [10:0] grp_fu_211_p1;
wire   [10:0] grp_fu_217_p0;
wire   [10:0] grp_fu_217_p1;
wire   [10:0] grp_fu_229_p0;
wire   [10:0] grp_fu_229_p1;
wire   [10:0] grp_fu_235_p0;
wire   [10:0] grp_fu_235_p1;
wire   [21:0] tmp_fu_247_p3;
wire   [17:0] tmp_1_fu_259_p3;
wire   [22:0] grp_fu_271_p0;
wire   [22:0] grp_fu_271_p1;
wire   [23:0] grp_fu_284_p0;
wire   [23:0] grp_fu_284_p1;
wire   [23:0] grp_fu_293_p0;
wire   [23:0] grp_fu_293_p1;
wire   [31:0] tmp_2_fu_302_p0;
wire   [31:0] tmp_3_fu_310_p0;
wire   [23:0] grp_fu_328_p0;
wire   [23:0] grp_fu_328_p1;
wire   [31:0] tmp_4_fu_336_p0;
wire   [21:0] tmp_5_fu_346_p3;
wire   [17:0] tmp_6_fu_357_p3;
wire   [22:0] grp_fu_368_p0;
wire   [22:0] grp_fu_368_p1;
wire   [23:0] grp_fu_377_p0;
wire   [23:0] grp_fu_377_p1;
wire   [31:0] tmp_7_fu_385_p0;
wire   [21:0] tmp_s_fu_395_p3;
wire   [17:0] tmp_10_fu_406_p3;
wire   [22:0] grp_fu_417_p0;
wire   [22:0] grp_fu_417_p1;
wire   [23:0] grp_fu_423_p0;
wire   [23:0] grp_fu_423_p1;
wire   [23:0] grp_fu_427_p0;
wire   [23:0] grp_fu_427_p1;
wire   [23:0] grp_fu_434_p0;
wire   [23:0] grp_fu_434_p1;
wire   [23:0] grp_fu_439_p0;
wire   [23:0] grp_fu_439_p1;
wire   [23:0] grp_fu_444_p0;
wire   [23:0] grp_fu_444_p1;
wire   [31:0] tmp_8_fu_452_p0;
wire   [31:0] tmp_9_fu_460_p0;
wire   [31:0] tmp_11_fu_468_p0;
wire   [31:0] tmp_12_fu_476_p0;
wire   [31:0] tmp_13_fu_489_p0;
wire   [63:0] grp_fu_177_p1;
wire    grp_fu_160_ce;
wire    grp_fu_164_ce;
wire    grp_fu_169_ce;
wire    grp_fu_177_ce;
wire    grp_fu_180_ce;
wire    grp_fu_183_ce;
wire    grp_fu_211_ce;
wire    grp_fu_217_ce;
wire    grp_fu_229_ce;
wire    grp_fu_235_ce;
reg    grp_fu_271_ce;
wire    grp_fu_284_ce;
wire    grp_fu_293_ce;
wire    grp_fu_328_ce;
wire    grp_fu_368_ce;
wire    grp_fu_377_ce;
wire    grp_fu_417_ce;
wire    grp_fu_423_ce;
wire    grp_fu_427_ce;
wire    grp_fu_434_ce;
wire    grp_fu_439_ce;
wire    grp_fu_444_ce;
reg   [7:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 8'b00000000;
parameter    ap_ST_st2_fsm_1 = 8'b1;
parameter    ap_ST_st3_fsm_2 = 8'b10;
parameter    ap_ST_st4_fsm_3 = 8'b11;
parameter    ap_ST_st5_fsm_4 = 8'b100;
parameter    ap_ST_st6_fsm_5 = 8'b101;
parameter    ap_ST_st7_fsm_6 = 8'b110;
parameter    ap_ST_st8_fsm_7 = 8'b111;
parameter    ap_ST_st9_fsm_8 = 8'b1000;
parameter    ap_ST_st10_fsm_9 = 8'b1001;
parameter    ap_ST_st11_fsm_10 = 8'b1010;
parameter    ap_ST_st12_fsm_11 = 8'b1011;
parameter    ap_ST_st13_fsm_12 = 8'b1100;
parameter    ap_ST_st14_fsm_13 = 8'b1101;
parameter    ap_ST_st15_fsm_14 = 8'b1110;
parameter    ap_ST_st16_fsm_15 = 8'b1111;
parameter    ap_ST_st17_fsm_16 = 8'b10000;
parameter    ap_ST_st18_fsm_17 = 8'b10001;
parameter    ap_ST_st19_fsm_18 = 8'b10010;
parameter    ap_ST_st20_fsm_19 = 8'b10011;
parameter    ap_ST_st21_fsm_20 = 8'b10100;
parameter    ap_ST_st22_fsm_21 = 8'b10101;
parameter    ap_ST_st23_fsm_22 = 8'b10110;
parameter    ap_ST_st24_fsm_23 = 8'b10111;
parameter    ap_ST_st25_fsm_24 = 8'b11000;
parameter    ap_ST_st26_fsm_25 = 8'b11001;
parameter    ap_ST_st27_fsm_26 = 8'b11010;
parameter    ap_ST_st28_fsm_27 = 8'b11011;
parameter    ap_ST_st29_fsm_28 = 8'b11100;
parameter    ap_ST_st30_fsm_29 = 8'b11101;
parameter    ap_ST_st31_fsm_30 = 8'b11110;
parameter    ap_ST_st32_fsm_31 = 8'b11111;
parameter    ap_ST_st33_fsm_32 = 8'b100000;
parameter    ap_ST_st34_fsm_33 = 8'b100001;
parameter    ap_ST_st35_fsm_34 = 8'b100010;
parameter    ap_ST_st36_fsm_35 = 8'b100011;
parameter    ap_ST_st37_fsm_36 = 8'b100100;
parameter    ap_ST_st38_fsm_37 = 8'b100101;
parameter    ap_ST_st39_fsm_38 = 8'b100110;
parameter    ap_ST_st40_fsm_39 = 8'b100111;
parameter    ap_ST_st41_fsm_40 = 8'b101000;
parameter    ap_ST_st42_fsm_41 = 8'b101001;
parameter    ap_ST_st43_fsm_42 = 8'b101010;
parameter    ap_ST_st44_fsm_43 = 8'b101011;
parameter    ap_ST_st45_fsm_44 = 8'b101100;
parameter    ap_ST_st46_fsm_45 = 8'b101101;
parameter    ap_ST_st47_fsm_46 = 8'b101110;
parameter    ap_ST_st48_fsm_47 = 8'b101111;
parameter    ap_ST_st49_fsm_48 = 8'b110000;
parameter    ap_ST_st50_fsm_49 = 8'b110001;
parameter    ap_ST_st51_fsm_50 = 8'b110010;
parameter    ap_ST_st52_fsm_51 = 8'b110011;
parameter    ap_ST_st53_fsm_52 = 8'b110100;
parameter    ap_ST_st54_fsm_53 = 8'b110101;
parameter    ap_ST_st55_fsm_54 = 8'b110110;
parameter    ap_ST_st56_fsm_55 = 8'b110111;
parameter    ap_ST_st57_fsm_56 = 8'b111000;
parameter    ap_ST_st58_fsm_57 = 8'b111001;
parameter    ap_ST_st59_fsm_58 = 8'b111010;
parameter    ap_ST_st60_fsm_59 = 8'b111011;
parameter    ap_ST_st61_fsm_60 = 8'b111100;
parameter    ap_ST_st62_fsm_61 = 8'b111101;
parameter    ap_ST_st63_fsm_62 = 8'b111110;
parameter    ap_ST_st64_fsm_63 = 8'b111111;
parameter    ap_ST_st65_fsm_64 = 8'b1000000;
parameter    ap_ST_st66_fsm_65 = 8'b1000001;
parameter    ap_ST_st67_fsm_66 = 8'b1000010;
parameter    ap_ST_st68_fsm_67 = 8'b1000011;
parameter    ap_ST_st69_fsm_68 = 8'b1000100;
parameter    ap_ST_st70_fsm_69 = 8'b1000101;
parameter    ap_ST_st71_fsm_70 = 8'b1000110;
parameter    ap_ST_st72_fsm_71 = 8'b1000111;
parameter    ap_ST_st73_fsm_72 = 8'b1001000;
parameter    ap_ST_st74_fsm_73 = 8'b1001001;
parameter    ap_ST_st75_fsm_74 = 8'b1001010;
parameter    ap_ST_st76_fsm_75 = 8'b1001011;
parameter    ap_ST_st77_fsm_76 = 8'b1001100;
parameter    ap_ST_st78_fsm_77 = 8'b1001101;
parameter    ap_ST_st79_fsm_78 = 8'b1001110;
parameter    ap_ST_st80_fsm_79 = 8'b1001111;
parameter    ap_ST_st81_fsm_80 = 8'b1010000;
parameter    ap_ST_st82_fsm_81 = 8'b1010001;
parameter    ap_ST_st83_fsm_82 = 8'b1010010;
parameter    ap_ST_st84_fsm_83 = 8'b1010011;
parameter    ap_ST_st85_fsm_84 = 8'b1010100;
parameter    ap_ST_st86_fsm_85 = 8'b1010101;
parameter    ap_ST_st87_fsm_86 = 8'b1010110;
parameter    ap_ST_st88_fsm_87 = 8'b1010111;
parameter    ap_ST_st89_fsm_88 = 8'b1011000;
parameter    ap_ST_st90_fsm_89 = 8'b1011001;
parameter    ap_ST_st91_fsm_90 = 8'b1011010;
parameter    ap_ST_st92_fsm_91 = 8'b1011011;
parameter    ap_ST_st93_fsm_92 = 8'b1011100;
parameter    ap_ST_st94_fsm_93 = 8'b1011101;
parameter    ap_ST_st95_fsm_94 = 8'b1011110;
parameter    ap_ST_st96_fsm_95 = 8'b1011111;
parameter    ap_ST_st97_fsm_96 = 8'b1100000;
parameter    ap_ST_st98_fsm_97 = 8'b1100001;
parameter    ap_ST_st99_fsm_98 = 8'b1100010;
parameter    ap_ST_st100_fsm_99 = 8'b1100011;
parameter    ap_ST_st101_fsm_100 = 8'b1100100;
parameter    ap_ST_st102_fsm_101 = 8'b1100101;
parameter    ap_ST_st103_fsm_102 = 8'b1100110;
parameter    ap_ST_st104_fsm_103 = 8'b1100111;
parameter    ap_ST_st105_fsm_104 = 8'b1101000;
parameter    ap_ST_st106_fsm_105 = 8'b1101001;
parameter    ap_ST_st107_fsm_106 = 8'b1101010;
parameter    ap_ST_st108_fsm_107 = 8'b1101011;
parameter    ap_ST_st109_fsm_108 = 8'b1101100;
parameter    ap_ST_st110_fsm_109 = 8'b1101101;
parameter    ap_ST_st111_fsm_110 = 8'b1101110;
parameter    ap_ST_st112_fsm_111 = 8'b1101111;
parameter    ap_ST_st113_fsm_112 = 8'b1110000;
parameter    ap_ST_st114_fsm_113 = 8'b1110001;
parameter    ap_ST_st115_fsm_114 = 8'b1110010;
parameter    ap_ST_st116_fsm_115 = 8'b1110011;
parameter    ap_ST_st117_fsm_116 = 8'b1110100;
parameter    ap_ST_st118_fsm_117 = 8'b1110101;
parameter    ap_ST_st119_fsm_118 = 8'b1110110;
parameter    ap_ST_st120_fsm_119 = 8'b1110111;
parameter    ap_ST_st121_fsm_120 = 8'b1111000;
parameter    ap_ST_st122_fsm_121 = 8'b1111001;
parameter    ap_ST_st123_fsm_122 = 8'b1111010;
parameter    ap_ST_st124_fsm_123 = 8'b1111011;
parameter    ap_ST_st125_fsm_124 = 8'b1111100;
parameter    ap_ST_st126_fsm_125 = 8'b1111101;
parameter    ap_ST_st127_fsm_126 = 8'b1111110;
parameter    ap_ST_st128_fsm_127 = 8'b1111111;
parameter    ap_ST_st129_fsm_128 = 8'b10000000;
parameter    ap_ST_st130_fsm_129 = 8'b10000001;
parameter    ap_ST_st131_fsm_130 = 8'b10000010;
parameter    ap_ST_st132_fsm_131 = 8'b10000011;
parameter    ap_ST_st133_fsm_132 = 8'b10000100;
parameter    ap_ST_st134_fsm_133 = 8'b10000101;
parameter    ap_ST_st135_fsm_134 = 8'b10000110;
parameter    ap_ST_st136_fsm_135 = 8'b10000111;
parameter    ap_ST_st137_fsm_136 = 8'b10001000;
parameter    ap_ST_st138_fsm_137 = 8'b10001001;
parameter    ap_ST_st139_fsm_138 = 8'b10001010;
parameter    ap_ST_st140_fsm_139 = 8'b10001011;
parameter    ap_ST_st141_fsm_140 = 8'b10001100;
parameter    ap_ST_st142_fsm_141 = 8'b10001101;
parameter    ap_ST_st143_fsm_142 = 8'b10001110;
parameter    ap_ST_st144_fsm_143 = 8'b10001111;
parameter    ap_ST_st145_fsm_144 = 8'b10010000;
parameter    ap_ST_st146_fsm_145 = 8'b10010001;
parameter    ap_ST_st147_fsm_146 = 8'b10010010;
parameter    ap_ST_st148_fsm_147 = 8'b10010011;
parameter    ap_ST_st149_fsm_148 = 8'b10010100;
parameter    ap_ST_st150_fsm_149 = 8'b10010101;
parameter    ap_ST_st151_fsm_150 = 8'b10010110;
parameter    ap_ST_st152_fsm_151 = 8'b10010111;
parameter    ap_ST_st153_fsm_152 = 8'b10011000;
parameter    ap_ST_st154_fsm_153 = 8'b10011001;
parameter    ap_ST_st155_fsm_154 = 8'b10011010;
parameter    ap_ST_st156_fsm_155 = 8'b10011011;
parameter    ap_ST_st157_fsm_156 = 8'b10011100;
parameter    ap_ST_st158_fsm_157 = 8'b10011101;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3D7929ED = 32'b111101011110010010100111101101;
parameter    ap_const_lv32_3E193AF7 = 32'b111110000110010011101011110111;
parameter    ap_const_lv32_3EBC7736 = 32'b111110101111000111011100110110;
parameter    ap_const_lv32_3E19389B = 32'b111110000110010011100010011011;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_436 = 11'b10000110110;
parameter    ap_const_lv11_77E = 11'b11101111110;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_true = 1'b1;


gaussian_fadd_32ns_32ns_32_14_no_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 14 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fadd_32ns_32ns_32_14_no_dsp_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_160_p0 ),
    .din1( grp_fu_160_p1 ),
    .ce( grp_fu_160_ce ),
    .dout( grp_fu_160_p2 )
);

gaussian_fmul_32ns_32ns_32_8_max_dsp #(
    .ID( 2 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_8_max_dsp_U2(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_164_p0 ),
    .din1( grp_fu_164_p1 ),
    .ce( grp_fu_164_ce ),
    .dout( grp_fu_164_p2 )
);

gaussian_fmul_32ns_32ns_32_8_max_dsp #(
    .ID( 3 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_8_max_dsp_U3(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_169_p0 ),
    .din1( grp_fu_169_p1 ),
    .ce( grp_fu_169_ce ),
    .dout( grp_fu_169_p2 )
);

gaussian_fptoui_32ns_64_8 #(
    .ID( 4 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
gaussian_fptoui_32ns_64_8_U4(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_177_p0 ),
    .ce( grp_fu_177_ce ),
    .dout( grp_fu_177_p1 )
);

gaussian_sitofp_64ns_32_9 #(
    .ID( 5 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_9_U5(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_180_p0 ),
    .ce( grp_fu_180_ce ),
    .dout( grp_fu_180_p1 )
);

gaussian_sitofp_64ns_32_9 #(
    .ID( 6 ),
    .NUM_STAGE( 9 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_9_U6(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_183_p0 ),
    .ce( grp_fu_183_ce ),
    .dout( grp_fu_183_p1 )
);

gaussian_add_11ns_11ns_11_3 #(
    .ID( 7 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
gaussian_add_11ns_11ns_11_3_U7(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_211_p0 ),
    .din1( grp_fu_211_p1 ),
    .ce( grp_fu_211_ce ),
    .dout( grp_fu_211_p2 )
);

gaussian_add_11ns_11ns_11_3 #(
    .ID( 8 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
gaussian_add_11ns_11ns_11_3_U8(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_217_p0 ),
    .din1( grp_fu_217_p1 ),
    .ce( grp_fu_217_ce ),
    .dout( grp_fu_217_p2 )
);

gaussian_add_11ns_11ns_11_3 #(
    .ID( 9 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
gaussian_add_11ns_11ns_11_3_U9(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_229_p0 ),
    .din1( grp_fu_229_p1 ),
    .ce( grp_fu_229_ce ),
    .dout( grp_fu_229_p2 )
);

gaussian_add_11ns_11ns_11_3 #(
    .ID( 10 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
gaussian_add_11ns_11ns_11_3_U10(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_235_p0 ),
    .din1( grp_fu_235_p1 ),
    .ce( grp_fu_235_ce ),
    .dout( grp_fu_235_p2 )
);

gaussian_sub_23ns_23ns_23_6 #(
    .ID( 11 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 23 ))
gaussian_sub_23ns_23ns_23_6_U11(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_271_p0 ),
    .din1( grp_fu_271_p1 ),
    .ce( grp_fu_271_ce ),
    .dout( grp_fu_271_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 12 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U12(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_284_p0 ),
    .din1( grp_fu_284_p1 ),
    .ce( grp_fu_284_ce ),
    .dout( grp_fu_284_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 13 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U13(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_293_p0 ),
    .din1( grp_fu_293_p1 ),
    .ce( grp_fu_293_ce ),
    .dout( grp_fu_293_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 14 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U14(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_328_p0 ),
    .din1( grp_fu_328_p1 ),
    .ce( grp_fu_328_ce ),
    .dout( grp_fu_328_p2 )
);

gaussian_sub_23ns_23ns_23_6 #(
    .ID( 15 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 23 ))
gaussian_sub_23ns_23ns_23_6_U15(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_368_p0 ),
    .din1( grp_fu_368_p1 ),
    .ce( grp_fu_368_ce ),
    .dout( grp_fu_368_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 16 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U16(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_377_p0 ),
    .din1( grp_fu_377_p1 ),
    .ce( grp_fu_377_ce ),
    .dout( grp_fu_377_p2 )
);

gaussian_sub_23ns_23ns_23_6 #(
    .ID( 17 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 23 ))
gaussian_sub_23ns_23ns_23_6_U17(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_417_p0 ),
    .din1( grp_fu_417_p1 ),
    .ce( grp_fu_417_ce ),
    .dout( grp_fu_417_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 18 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U18(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_423_p0 ),
    .din1( grp_fu_423_p1 ),
    .ce( grp_fu_423_ce ),
    .dout( grp_fu_423_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 19 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U19(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_427_p0 ),
    .din1( grp_fu_427_p1 ),
    .ce( grp_fu_427_ce ),
    .dout( grp_fu_427_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 20 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U20(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_434_p0 ),
    .din1( grp_fu_434_p1 ),
    .ce( grp_fu_434_ce ),
    .dout( grp_fu_434_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 21 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U21(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_439_p0 ),
    .din1( grp_fu_439_p1 ),
    .ce( grp_fu_439_ce ),
    .dout( grp_fu_439_p2 )
);

gaussian_add_24s_24ns_24_6 #(
    .ID( 22 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
gaussian_add_24s_24ns_24_6_U22(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_444_p0 ),
    .din1( grp_fu_444_p1 ),
    .ce( grp_fu_444_ce ),
    .dout( grp_fu_444_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st7_fsm_6 == ap_CS_fsm) & ~(exitcond1_fu_241_p2 == ap_const_lv1_0))) begin
        indvar1_i_reg_135 <= i_reg_526;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        indvar1_i_reg_135 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & (exitcond_reg_516 == ap_const_lv1_0))) begin
        indvar_i_reg_147 <= ap_const_lv11_0;
    end else if ((ap_ST_st158_fsm_157 == ap_CS_fsm)) begin
        indvar_i_reg_147 <= j_reg_538;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        exitcond_reg_516 <= exitcond_fu_223_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        i_reg_526 <= grp_fu_217_p2;
        tmp_i_12_reg_520 <= grp_fu_211_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st63_fsm_62 == ap_CS_fsm)) begin
        in_load_7_reg_759 <= in_r_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st64_fsm_63 == ap_CS_fsm)) begin
        in_load_8_reg_769 <= in_r_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st7_fsm_6 == ap_CS_fsm)) begin
        j_reg_538 <= grp_fu_235_p2;
        tmp6_i_reg_533 <= grp_fu_229_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st60_fsm_59 == ap_CS_fsm)) begin
        p_addr10_reg_709 <= grp_fu_427_p2;
        p_addr11_reg_704 <= grp_fu_423_p2;
        p_addr1_reg_724 <= grp_fu_444_p2;
        p_addr4_reg_719 <= grp_fu_439_p2;
        p_addr7_reg_714 <= grp_fu_434_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st18_fsm_17 == ap_CS_fsm)) begin
        p_addr2_reg_583 <= grp_fu_284_p2;
        p_addr3_reg_588 <= grp_fu_293_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        p_addr5_reg_625 <= grp_fu_328_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st54_fsm_53 == ap_CS_fsm)) begin
        p_addr6_reg_692 <= grp_fu_417_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st41_fsm_40 == ap_CS_fsm)) begin
        p_addr8_cast_reg_660 <= p_addr8_cast_fu_374_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st40_fsm_39 == ap_CS_fsm)) begin
        p_addr8_reg_655 <= grp_fu_368_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        p_addr9_reg_667 <= grp_fu_377_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st13_fsm_12 == ap_CS_fsm)) begin
        p_addr_cast_reg_569 <= p_addr_cast_fu_281_p1;
        tmp_4_i_trn_cast_reg_562[0] <= tmp_4_i_trn_cast_fu_277_p1[0];
tmp_4_i_trn_cast_reg_562[1] <= tmp_4_i_trn_cast_fu_277_p1[1];
tmp_4_i_trn_cast_reg_562[2] <= tmp_4_i_trn_cast_fu_277_p1[2];
tmp_4_i_trn_cast_reg_562[3] <= tmp_4_i_trn_cast_fu_277_p1[3];
tmp_4_i_trn_cast_reg_562[4] <= tmp_4_i_trn_cast_fu_277_p1[4];
tmp_4_i_trn_cast_reg_562[5] <= tmp_4_i_trn_cast_fu_277_p1[5];
tmp_4_i_trn_cast_reg_562[6] <= tmp_4_i_trn_cast_fu_277_p1[6];
tmp_4_i_trn_cast_reg_562[7] <= tmp_4_i_trn_cast_fu_277_p1[7];
tmp_4_i_trn_cast_reg_562[8] <= tmp_4_i_trn_cast_fu_277_p1[8];
tmp_4_i_trn_cast_reg_562[9] <= tmp_4_i_trn_cast_fu_277_p1[9];
tmp_4_i_trn_cast_reg_562[10] <= tmp_4_i_trn_cast_fu_277_p1[10];
        tmp_8_i_trn_cast_reg_576[0] <= tmp_8_i_trn_cast_fu_290_p1[0];
tmp_8_i_trn_cast_reg_576[1] <= tmp_8_i_trn_cast_fu_290_p1[1];
tmp_8_i_trn_cast_reg_576[2] <= tmp_8_i_trn_cast_fu_290_p1[2];
tmp_8_i_trn_cast_reg_576[3] <= tmp_8_i_trn_cast_fu_290_p1[3];
tmp_8_i_trn_cast_reg_576[4] <= tmp_8_i_trn_cast_fu_290_p1[4];
tmp_8_i_trn_cast_reg_576[5] <= tmp_8_i_trn_cast_fu_290_p1[5];
tmp_8_i_trn_cast_reg_576[6] <= tmp_8_i_trn_cast_fu_290_p1[6];
tmp_8_i_trn_cast_reg_576[7] <= tmp_8_i_trn_cast_fu_290_p1[7];
tmp_8_i_trn_cast_reg_576[8] <= tmp_8_i_trn_cast_fu_290_p1[8];
tmp_8_i_trn_cast_reg_576[9] <= tmp_8_i_trn_cast_fu_290_p1[9];
tmp_8_i_trn_cast_reg_576[10] <= tmp_8_i_trn_cast_fu_290_p1[10];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st12_fsm_11 == ap_CS_fsm)) begin
        p_addr_reg_557 <= grp_fu_271_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm) | (ap_ST_st48_fsm_47 == ap_CS_fsm) | (ap_ST_st62_fsm_61 == ap_CS_fsm) | (ap_ST_st63_fsm_62 == ap_CS_fsm))) begin
        reg_186 <= in_r_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st62_fsm_61 == ap_CS_fsm))) begin
        reg_190 <= in_r_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st43_fsm_42 == ap_CS_fsm) | (ap_ST_st57_fsm_56 == ap_CS_fsm) | (ap_ST_st71_fsm_70 == ap_CS_fsm) | (ap_ST_st85_fsm_84 == ap_CS_fsm) | (ap_ST_st99_fsm_98 == ap_CS_fsm) | (ap_ST_st113_fsm_112 == ap_CS_fsm) | (ap_ST_st127_fsm_126 == ap_CS_fsm))) begin
        reg_194 <= grp_fu_180_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st37_fsm_36 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st65_fsm_64 == ap_CS_fsm) | (ap_ST_st79_fsm_78 == ap_CS_fsm) | (ap_ST_st93_fsm_92 == ap_CS_fsm) | (ap_ST_st107_fsm_106 == ap_CS_fsm) | (ap_ST_st121_fsm_120 == ap_CS_fsm) | (ap_ST_st135_fsm_134 == ap_CS_fsm))) begin
        reg_199 <= grp_fu_164_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st65_fsm_64 == ap_CS_fsm) | (ap_ST_st79_fsm_78 == ap_CS_fsm) | (ap_ST_st93_fsm_92 == ap_CS_fsm) | (ap_ST_st107_fsm_106 == ap_CS_fsm) | (ap_ST_st121_fsm_120 == ap_CS_fsm) | (ap_ST_st135_fsm_134 == ap_CS_fsm) | (ap_ST_st149_fsm_148 == ap_CS_fsm))) begin
        reg_205 <= grp_fu_160_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st37_fsm_36 == ap_CS_fsm)) begin
        tmp_10_i_reg_650 <= grp_fu_169_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        tmp_12_i_trn_cast_reg_613[0] <= tmp_12_i_trn_cast_fu_325_p1[0];
tmp_12_i_trn_cast_reg_613[1] <= tmp_12_i_trn_cast_fu_325_p1[1];
tmp_12_i_trn_cast_reg_613[2] <= tmp_12_i_trn_cast_fu_325_p1[2];
tmp_12_i_trn_cast_reg_613[3] <= tmp_12_i_trn_cast_fu_325_p1[3];
tmp_12_i_trn_cast_reg_613[4] <= tmp_12_i_trn_cast_fu_325_p1[4];
tmp_12_i_trn_cast_reg_613[5] <= tmp_12_i_trn_cast_fu_325_p1[5];
tmp_12_i_trn_cast_reg_613[6] <= tmp_12_i_trn_cast_fu_325_p1[6];
tmp_12_i_trn_cast_reg_613[7] <= tmp_12_i_trn_cast_fu_325_p1[7];
tmp_12_i_trn_cast_reg_613[8] <= tmp_12_i_trn_cast_fu_325_p1[8];
tmp_12_i_trn_cast_reg_613[9] <= tmp_12_i_trn_cast_fu_325_p1[9];
tmp_12_i_trn_cast_reg_613[10] <= tmp_12_i_trn_cast_fu_325_p1[10];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st157_fsm_156 == ap_CS_fsm)) begin
        tmp_14_reg_794 <= tmp_14_fu_512_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        tmp_8_reg_729[0] <= tmp_8_fu_452_p1[0];
tmp_8_reg_729[1] <= tmp_8_fu_452_p1[1];
tmp_8_reg_729[2] <= tmp_8_fu_452_p1[2];
tmp_8_reg_729[3] <= tmp_8_fu_452_p1[3];
tmp_8_reg_729[4] <= tmp_8_fu_452_p1[4];
tmp_8_reg_729[5] <= tmp_8_fu_452_p1[5];
tmp_8_reg_729[6] <= tmp_8_fu_452_p1[6];
tmp_8_reg_729[7] <= tmp_8_fu_452_p1[7];
tmp_8_reg_729[8] <= tmp_8_fu_452_p1[8];
tmp_8_reg_729[9] <= tmp_8_fu_452_p1[9];
tmp_8_reg_729[10] <= tmp_8_fu_452_p1[10];
tmp_8_reg_729[11] <= tmp_8_fu_452_p1[11];
tmp_8_reg_729[12] <= tmp_8_fu_452_p1[12];
tmp_8_reg_729[13] <= tmp_8_fu_452_p1[13];
tmp_8_reg_729[14] <= tmp_8_fu_452_p1[14];
tmp_8_reg_729[15] <= tmp_8_fu_452_p1[15];
tmp_8_reg_729[16] <= tmp_8_fu_452_p1[16];
tmp_8_reg_729[17] <= tmp_8_fu_452_p1[17];
tmp_8_reg_729[18] <= tmp_8_fu_452_p1[18];
tmp_8_reg_729[19] <= tmp_8_fu_452_p1[19];
tmp_8_reg_729[20] <= tmp_8_fu_452_p1[20];
tmp_8_reg_729[21] <= tmp_8_fu_452_p1[21];
tmp_8_reg_729[22] <= tmp_8_fu_452_p1[22];
tmp_8_reg_729[23] <= tmp_8_fu_452_p1[23];
tmp_8_reg_729[24] <= tmp_8_fu_452_p1[24];
tmp_8_reg_729[25] <= tmp_8_fu_452_p1[25];
tmp_8_reg_729[26] <= tmp_8_fu_452_p1[26];
tmp_8_reg_729[27] <= tmp_8_fu_452_p1[27];
tmp_8_reg_729[28] <= tmp_8_fu_452_p1[28];
tmp_8_reg_729[29] <= tmp_8_fu_452_p1[29];
tmp_8_reg_729[30] <= tmp_8_fu_452_p1[30];
tmp_8_reg_729[31] <= tmp_8_fu_452_p1[31];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st29_fsm_28 == ap_CS_fsm)) begin
        tmp_i_reg_620 <= grp_fu_183_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_CS_fsm or exitcond_reg_516)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(exitcond_reg_516 == ap_const_lv1_0))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond_reg_516)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) & ~(exitcond_reg_516 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// grp_fu_160_p0 assign process. ///
always @ (ap_CS_fsm or reg_199 or reg_205)
begin
    if (((ap_ST_st52_fsm_51 == ap_CS_fsm) | (ap_ST_st66_fsm_65 == ap_CS_fsm) | (ap_ST_st80_fsm_79 == ap_CS_fsm) | (ap_ST_st94_fsm_93 == ap_CS_fsm) | (ap_ST_st108_fsm_107 == ap_CS_fsm) | (ap_ST_st122_fsm_121 == ap_CS_fsm) | (ap_ST_st136_fsm_135 == ap_CS_fsm))) begin
        grp_fu_160_p0 = reg_205;
    end else if ((ap_ST_st38_fsm_37 == ap_CS_fsm)) begin
        grp_fu_160_p0 = reg_199;
    end else begin
        grp_fu_160_p0 = reg_205;
    end
end

/// grp_fu_160_p1 assign process. ///
always @ (ap_CS_fsm or reg_199 or tmp_10_i_reg_650)
begin
    if (((ap_ST_st52_fsm_51 == ap_CS_fsm) | (ap_ST_st66_fsm_65 == ap_CS_fsm) | (ap_ST_st80_fsm_79 == ap_CS_fsm) | (ap_ST_st94_fsm_93 == ap_CS_fsm) | (ap_ST_st108_fsm_107 == ap_CS_fsm) | (ap_ST_st122_fsm_121 == ap_CS_fsm) | (ap_ST_st136_fsm_135 == ap_CS_fsm))) begin
        grp_fu_160_p1 = reg_199;
    end else if ((ap_ST_st38_fsm_37 == ap_CS_fsm)) begin
        grp_fu_160_p1 = tmp_10_i_reg_650;
    end else begin
        grp_fu_160_p1 = tmp_10_i_reg_650;
    end
end

/// grp_fu_164_p1 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st86_fsm_85 == ap_CS_fsm)) begin
        grp_fu_164_p1 = ap_const_lv32_3E19389B;
    end else if ((ap_ST_st72_fsm_71 == ap_CS_fsm)) begin
        grp_fu_164_p1 = ap_const_lv32_3EBC7736;
    end else if (((ap_ST_st58_fsm_57 == ap_CS_fsm) | (ap_ST_st114_fsm_113 == ap_CS_fsm))) begin
        grp_fu_164_p1 = ap_const_lv32_3E193AF7;
    end else if (((ap_ST_st30_fsm_29 == ap_CS_fsm) | (ap_ST_st44_fsm_43 == ap_CS_fsm) | (ap_ST_st100_fsm_99 == ap_CS_fsm) | (ap_ST_st128_fsm_127 == ap_CS_fsm))) begin
        grp_fu_164_p1 = ap_const_lv32_3D7929ED;
    end else begin
        grp_fu_164_p1 = ap_const_lv32_3E19389B;
    end
end

/// grp_fu_180_p0 assign process. ///
always @ (ap_CS_fsm or tmp_6_i3_fu_315_p1 or tmp_14_i5_fu_341_p1 or tmp_18_i6_fu_390_p1 or tmp_22_i7_fu_481_p1 or tmp_26_i8_fu_494_p1 or tmp_30_i9_fu_499_p1 or tmp_34_i1_fu_504_p1 or tmp_38_i1_fu_508_p1)
begin
    if ((ap_ST_st119_fsm_118 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_38_i1_fu_508_p1;
    end else if ((ap_ST_st105_fsm_104 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_34_i1_fu_504_p1;
    end else if ((ap_ST_st91_fsm_90 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_30_i9_fu_499_p1;
    end else if ((ap_ST_st77_fsm_76 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_26_i8_fu_494_p1;
    end else if ((ap_ST_st63_fsm_62 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_22_i7_fu_481_p1;
    end else if ((ap_ST_st49_fsm_48 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_18_i6_fu_390_p1;
    end else if ((ap_ST_st35_fsm_34 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_14_i5_fu_341_p1;
    end else if ((ap_ST_st21_fsm_20 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_6_i3_fu_315_p1;
    end else begin
        grp_fu_180_p0 = tmp_38_i1_fu_508_p1;
    end
end

/// grp_fu_271_ce assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_241_p2)
begin
    if ((((ap_ST_st7_fsm_6 == ap_CS_fsm) & (exitcond1_fu_241_p2 == ap_const_lv1_0)) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st8_fsm_7 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st10_fsm_9 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        grp_fu_271_ce = ap_const_logic_1;
    end else begin
        grp_fu_271_ce = ap_const_logic_0;
    end
end

/// in_r_address0 assign process. ///
always @ (ap_CS_fsm or tmp_8_fu_452_p1 or tmp_2_fu_302_p1 or tmp_4_fu_336_p1 or tmp_7_fu_385_p1 or tmp_11_fu_468_p1 or tmp_13_fu_489_p1)
begin
    if ((ap_ST_st63_fsm_62 == ap_CS_fsm)) begin
        in_r_address0 = tmp_13_fu_489_p1;
    end else if ((ap_ST_st62_fsm_61 == ap_CS_fsm)) begin
        in_r_address0 = tmp_11_fu_468_p1;
    end else if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        in_r_address0 = tmp_8_fu_452_p1;
    end else if ((ap_ST_st47_fsm_46 == ap_CS_fsm)) begin
        in_r_address0 = tmp_7_fu_385_p1;
    end else if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        in_r_address0 = tmp_4_fu_336_p1;
    end else if ((ap_ST_st19_fsm_18 == ap_CS_fsm)) begin
        in_r_address0 = tmp_2_fu_302_p1;
    end else begin
        in_r_address0 = tmp_13_fu_489_p1;
    end
end

/// in_r_address1 assign process. ///
always @ (ap_CS_fsm or tmp_3_fu_310_p1 or tmp_9_fu_460_p1 or tmp_12_fu_476_p1)
begin
    if ((ap_ST_st62_fsm_61 == ap_CS_fsm)) begin
        in_r_address1 = tmp_12_fu_476_p1;
    end else if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        in_r_address1 = tmp_9_fu_460_p1;
    end else if ((ap_ST_st19_fsm_18 == ap_CS_fsm)) begin
        in_r_address1 = tmp_3_fu_310_p1;
    end else begin
        in_r_address1 = tmp_12_fu_476_p1;
    end
end

/// in_r_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st62_fsm_61 == ap_CS_fsm) | (ap_ST_st63_fsm_62 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st47_fsm_46 == ap_CS_fsm) | (ap_ST_st61_fsm_60 == ap_CS_fsm))) begin
        in_r_ce0 = ap_const_logic_1;
    end else begin
        in_r_ce0 = ap_const_logic_0;
    end
end

/// in_r_ce1 assign process. ///
always @ (ap_CS_fsm)
begin
    if (((ap_ST_st62_fsm_61 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st61_fsm_60 == ap_CS_fsm))) begin
        in_r_ce1 = ap_const_logic_1;
    end else begin
        in_r_ce1 = ap_const_logic_0;
    end
end

/// out_r_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st158_fsm_157 == ap_CS_fsm)) begin
        out_r_ce0 = ap_const_logic_1;
    end else begin
        out_r_ce0 = ap_const_logic_0;
    end
end

/// out_r_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st158_fsm_157 == ap_CS_fsm)) begin
        out_r_we0 = ap_const_logic_1;
    end else begin
        out_r_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond_reg_516 or exitcond1_fu_241_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st4_fsm_3 : 
            if (~(exitcond_reg_516 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        ap_ST_st5_fsm_4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            if ((exitcond1_fu_241_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st8_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
        ap_ST_st17_fsm_16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        ap_ST_st18_fsm_17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
        ap_ST_st19_fsm_18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
        ap_ST_st20_fsm_19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
        ap_ST_st21_fsm_20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
        ap_ST_st22_fsm_21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
        ap_ST_st23_fsm_22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
        ap_ST_st24_fsm_23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        ap_ST_st26_fsm_25 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
        ap_ST_st27_fsm_26 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
        ap_ST_st28_fsm_27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
        ap_ST_st29_fsm_28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
        ap_ST_st30_fsm_29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
        ap_ST_st31_fsm_30 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
        ap_ST_st32_fsm_31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
        ap_ST_st33_fsm_32 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
        ap_ST_st34_fsm_33 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
        ap_ST_st35_fsm_34 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
        ap_ST_st36_fsm_35 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
        ap_ST_st37_fsm_36 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
        ap_ST_st38_fsm_37 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
        ap_ST_st39_fsm_38 : 
            ap_NS_fsm = ap_ST_st40_fsm_39;
        ap_ST_st40_fsm_39 : 
            ap_NS_fsm = ap_ST_st41_fsm_40;
        ap_ST_st41_fsm_40 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
        ap_ST_st42_fsm_41 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
        ap_ST_st43_fsm_42 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
        ap_ST_st44_fsm_43 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
        ap_ST_st45_fsm_44 : 
            ap_NS_fsm = ap_ST_st46_fsm_45;
        ap_ST_st46_fsm_45 : 
            ap_NS_fsm = ap_ST_st47_fsm_46;
        ap_ST_st47_fsm_46 : 
            ap_NS_fsm = ap_ST_st48_fsm_47;
        ap_ST_st48_fsm_47 : 
            ap_NS_fsm = ap_ST_st49_fsm_48;
        ap_ST_st49_fsm_48 : 
            ap_NS_fsm = ap_ST_st50_fsm_49;
        ap_ST_st50_fsm_49 : 
            ap_NS_fsm = ap_ST_st51_fsm_50;
        ap_ST_st51_fsm_50 : 
            ap_NS_fsm = ap_ST_st52_fsm_51;
        ap_ST_st52_fsm_51 : 
            ap_NS_fsm = ap_ST_st53_fsm_52;
        ap_ST_st53_fsm_52 : 
            ap_NS_fsm = ap_ST_st54_fsm_53;
        ap_ST_st54_fsm_53 : 
            ap_NS_fsm = ap_ST_st55_fsm_54;
        ap_ST_st55_fsm_54 : 
            ap_NS_fsm = ap_ST_st56_fsm_55;
        ap_ST_st56_fsm_55 : 
            ap_NS_fsm = ap_ST_st57_fsm_56;
        ap_ST_st57_fsm_56 : 
            ap_NS_fsm = ap_ST_st58_fsm_57;
        ap_ST_st58_fsm_57 : 
            ap_NS_fsm = ap_ST_st59_fsm_58;
        ap_ST_st59_fsm_58 : 
            ap_NS_fsm = ap_ST_st60_fsm_59;
        ap_ST_st60_fsm_59 : 
            ap_NS_fsm = ap_ST_st61_fsm_60;
        ap_ST_st61_fsm_60 : 
            ap_NS_fsm = ap_ST_st62_fsm_61;
        ap_ST_st62_fsm_61 : 
            ap_NS_fsm = ap_ST_st63_fsm_62;
        ap_ST_st63_fsm_62 : 
            ap_NS_fsm = ap_ST_st64_fsm_63;
        ap_ST_st64_fsm_63 : 
            ap_NS_fsm = ap_ST_st65_fsm_64;
        ap_ST_st65_fsm_64 : 
            ap_NS_fsm = ap_ST_st66_fsm_65;
        ap_ST_st66_fsm_65 : 
            ap_NS_fsm = ap_ST_st67_fsm_66;
        ap_ST_st67_fsm_66 : 
            ap_NS_fsm = ap_ST_st68_fsm_67;
        ap_ST_st68_fsm_67 : 
            ap_NS_fsm = ap_ST_st69_fsm_68;
        ap_ST_st69_fsm_68 : 
            ap_NS_fsm = ap_ST_st70_fsm_69;
        ap_ST_st70_fsm_69 : 
            ap_NS_fsm = ap_ST_st71_fsm_70;
        ap_ST_st71_fsm_70 : 
            ap_NS_fsm = ap_ST_st72_fsm_71;
        ap_ST_st72_fsm_71 : 
            ap_NS_fsm = ap_ST_st73_fsm_72;
        ap_ST_st73_fsm_72 : 
            ap_NS_fsm = ap_ST_st74_fsm_73;
        ap_ST_st74_fsm_73 : 
            ap_NS_fsm = ap_ST_st75_fsm_74;
        ap_ST_st75_fsm_74 : 
            ap_NS_fsm = ap_ST_st76_fsm_75;
        ap_ST_st76_fsm_75 : 
            ap_NS_fsm = ap_ST_st77_fsm_76;
        ap_ST_st77_fsm_76 : 
            ap_NS_fsm = ap_ST_st78_fsm_77;
        ap_ST_st78_fsm_77 : 
            ap_NS_fsm = ap_ST_st79_fsm_78;
        ap_ST_st79_fsm_78 : 
            ap_NS_fsm = ap_ST_st80_fsm_79;
        ap_ST_st80_fsm_79 : 
            ap_NS_fsm = ap_ST_st81_fsm_80;
        ap_ST_st81_fsm_80 : 
            ap_NS_fsm = ap_ST_st82_fsm_81;
        ap_ST_st82_fsm_81 : 
            ap_NS_fsm = ap_ST_st83_fsm_82;
        ap_ST_st83_fsm_82 : 
            ap_NS_fsm = ap_ST_st84_fsm_83;
        ap_ST_st84_fsm_83 : 
            ap_NS_fsm = ap_ST_st85_fsm_84;
        ap_ST_st85_fsm_84 : 
            ap_NS_fsm = ap_ST_st86_fsm_85;
        ap_ST_st86_fsm_85 : 
            ap_NS_fsm = ap_ST_st87_fsm_86;
        ap_ST_st87_fsm_86 : 
            ap_NS_fsm = ap_ST_st88_fsm_87;
        ap_ST_st88_fsm_87 : 
            ap_NS_fsm = ap_ST_st89_fsm_88;
        ap_ST_st89_fsm_88 : 
            ap_NS_fsm = ap_ST_st90_fsm_89;
        ap_ST_st90_fsm_89 : 
            ap_NS_fsm = ap_ST_st91_fsm_90;
        ap_ST_st91_fsm_90 : 
            ap_NS_fsm = ap_ST_st92_fsm_91;
        ap_ST_st92_fsm_91 : 
            ap_NS_fsm = ap_ST_st93_fsm_92;
        ap_ST_st93_fsm_92 : 
            ap_NS_fsm = ap_ST_st94_fsm_93;
        ap_ST_st94_fsm_93 : 
            ap_NS_fsm = ap_ST_st95_fsm_94;
        ap_ST_st95_fsm_94 : 
            ap_NS_fsm = ap_ST_st96_fsm_95;
        ap_ST_st96_fsm_95 : 
            ap_NS_fsm = ap_ST_st97_fsm_96;
        ap_ST_st97_fsm_96 : 
            ap_NS_fsm = ap_ST_st98_fsm_97;
        ap_ST_st98_fsm_97 : 
            ap_NS_fsm = ap_ST_st99_fsm_98;
        ap_ST_st99_fsm_98 : 
            ap_NS_fsm = ap_ST_st100_fsm_99;
        ap_ST_st100_fsm_99 : 
            ap_NS_fsm = ap_ST_st101_fsm_100;
        ap_ST_st101_fsm_100 : 
            ap_NS_fsm = ap_ST_st102_fsm_101;
        ap_ST_st102_fsm_101 : 
            ap_NS_fsm = ap_ST_st103_fsm_102;
        ap_ST_st103_fsm_102 : 
            ap_NS_fsm = ap_ST_st104_fsm_103;
        ap_ST_st104_fsm_103 : 
            ap_NS_fsm = ap_ST_st105_fsm_104;
        ap_ST_st105_fsm_104 : 
            ap_NS_fsm = ap_ST_st106_fsm_105;
        ap_ST_st106_fsm_105 : 
            ap_NS_fsm = ap_ST_st107_fsm_106;
        ap_ST_st107_fsm_106 : 
            ap_NS_fsm = ap_ST_st108_fsm_107;
        ap_ST_st108_fsm_107 : 
            ap_NS_fsm = ap_ST_st109_fsm_108;
        ap_ST_st109_fsm_108 : 
            ap_NS_fsm = ap_ST_st110_fsm_109;
        ap_ST_st110_fsm_109 : 
            ap_NS_fsm = ap_ST_st111_fsm_110;
        ap_ST_st111_fsm_110 : 
            ap_NS_fsm = ap_ST_st112_fsm_111;
        ap_ST_st112_fsm_111 : 
            ap_NS_fsm = ap_ST_st113_fsm_112;
        ap_ST_st113_fsm_112 : 
            ap_NS_fsm = ap_ST_st114_fsm_113;
        ap_ST_st114_fsm_113 : 
            ap_NS_fsm = ap_ST_st115_fsm_114;
        ap_ST_st115_fsm_114 : 
            ap_NS_fsm = ap_ST_st116_fsm_115;
        ap_ST_st116_fsm_115 : 
            ap_NS_fsm = ap_ST_st117_fsm_116;
        ap_ST_st117_fsm_116 : 
            ap_NS_fsm = ap_ST_st118_fsm_117;
        ap_ST_st118_fsm_117 : 
            ap_NS_fsm = ap_ST_st119_fsm_118;
        ap_ST_st119_fsm_118 : 
            ap_NS_fsm = ap_ST_st120_fsm_119;
        ap_ST_st120_fsm_119 : 
            ap_NS_fsm = ap_ST_st121_fsm_120;
        ap_ST_st121_fsm_120 : 
            ap_NS_fsm = ap_ST_st122_fsm_121;
        ap_ST_st122_fsm_121 : 
            ap_NS_fsm = ap_ST_st123_fsm_122;
        ap_ST_st123_fsm_122 : 
            ap_NS_fsm = ap_ST_st124_fsm_123;
        ap_ST_st124_fsm_123 : 
            ap_NS_fsm = ap_ST_st125_fsm_124;
        ap_ST_st125_fsm_124 : 
            ap_NS_fsm = ap_ST_st126_fsm_125;
        ap_ST_st126_fsm_125 : 
            ap_NS_fsm = ap_ST_st127_fsm_126;
        ap_ST_st127_fsm_126 : 
            ap_NS_fsm = ap_ST_st128_fsm_127;
        ap_ST_st128_fsm_127 : 
            ap_NS_fsm = ap_ST_st129_fsm_128;
        ap_ST_st129_fsm_128 : 
            ap_NS_fsm = ap_ST_st130_fsm_129;
        ap_ST_st130_fsm_129 : 
            ap_NS_fsm = ap_ST_st131_fsm_130;
        ap_ST_st131_fsm_130 : 
            ap_NS_fsm = ap_ST_st132_fsm_131;
        ap_ST_st132_fsm_131 : 
            ap_NS_fsm = ap_ST_st133_fsm_132;
        ap_ST_st133_fsm_132 : 
            ap_NS_fsm = ap_ST_st134_fsm_133;
        ap_ST_st134_fsm_133 : 
            ap_NS_fsm = ap_ST_st135_fsm_134;
        ap_ST_st135_fsm_134 : 
            ap_NS_fsm = ap_ST_st136_fsm_135;
        ap_ST_st136_fsm_135 : 
            ap_NS_fsm = ap_ST_st137_fsm_136;
        ap_ST_st137_fsm_136 : 
            ap_NS_fsm = ap_ST_st138_fsm_137;
        ap_ST_st138_fsm_137 : 
            ap_NS_fsm = ap_ST_st139_fsm_138;
        ap_ST_st139_fsm_138 : 
            ap_NS_fsm = ap_ST_st140_fsm_139;
        ap_ST_st140_fsm_139 : 
            ap_NS_fsm = ap_ST_st141_fsm_140;
        ap_ST_st141_fsm_140 : 
            ap_NS_fsm = ap_ST_st142_fsm_141;
        ap_ST_st142_fsm_141 : 
            ap_NS_fsm = ap_ST_st143_fsm_142;
        ap_ST_st143_fsm_142 : 
            ap_NS_fsm = ap_ST_st144_fsm_143;
        ap_ST_st144_fsm_143 : 
            ap_NS_fsm = ap_ST_st145_fsm_144;
        ap_ST_st145_fsm_144 : 
            ap_NS_fsm = ap_ST_st146_fsm_145;
        ap_ST_st146_fsm_145 : 
            ap_NS_fsm = ap_ST_st147_fsm_146;
        ap_ST_st147_fsm_146 : 
            ap_NS_fsm = ap_ST_st148_fsm_147;
        ap_ST_st148_fsm_147 : 
            ap_NS_fsm = ap_ST_st149_fsm_148;
        ap_ST_st149_fsm_148 : 
            ap_NS_fsm = ap_ST_st150_fsm_149;
        ap_ST_st150_fsm_149 : 
            ap_NS_fsm = ap_ST_st151_fsm_150;
        ap_ST_st151_fsm_150 : 
            ap_NS_fsm = ap_ST_st152_fsm_151;
        ap_ST_st152_fsm_151 : 
            ap_NS_fsm = ap_ST_st153_fsm_152;
        ap_ST_st153_fsm_152 : 
            ap_NS_fsm = ap_ST_st154_fsm_153;
        ap_ST_st154_fsm_153 : 
            ap_NS_fsm = ap_ST_st155_fsm_154;
        ap_ST_st155_fsm_154 : 
            ap_NS_fsm = ap_ST_st156_fsm_155;
        ap_ST_st156_fsm_155 : 
            ap_NS_fsm = ap_ST_st157_fsm_156;
        ap_ST_st157_fsm_156 : 
            ap_NS_fsm = ap_ST_st158_fsm_157;
        ap_ST_st158_fsm_157 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign exitcond1_fu_241_p2 = (indvar_i_reg_147 == ap_const_lv11_77E? 1'b1: 1'b0);
assign exitcond_fu_223_p2 = (indvar1_i_reg_135 == ap_const_lv11_436? 1'b1: 1'b0);
assign grp_fu_160_ce = ap_const_logic_1;
assign grp_fu_164_ce = ap_const_logic_1;
assign grp_fu_164_p0 = reg_194;
assign grp_fu_169_ce = ap_const_logic_1;
assign grp_fu_169_p0 = tmp_i_reg_620;
assign grp_fu_169_p1 = ap_const_lv32_3E193AF7;
assign grp_fu_177_ce = ap_const_logic_1;
assign grp_fu_177_p0 = reg_205;
assign grp_fu_180_ce = ap_const_logic_1;
assign grp_fu_183_ce = ap_const_logic_1;
assign grp_fu_183_p0 = $unsigned(reg_190);
assign grp_fu_211_ce = ap_const_logic_1;
assign grp_fu_211_p0 = indvar1_i_reg_135;
assign grp_fu_211_p1 = ap_const_lv11_2;
assign grp_fu_217_ce = ap_const_logic_1;
assign grp_fu_217_p0 = indvar1_i_reg_135;
assign grp_fu_217_p1 = ap_const_lv11_1;
assign grp_fu_229_ce = ap_const_logic_1;
assign grp_fu_229_p0 = indvar_i_reg_147;
assign grp_fu_229_p1 = ap_const_lv11_2;
assign grp_fu_235_ce = ap_const_logic_1;
assign grp_fu_235_p0 = indvar_i_reg_147;
assign grp_fu_235_p1 = ap_const_lv11_1;
assign grp_fu_271_p0 = $unsigned(tmp_fu_247_p3);
assign grp_fu_271_p1 = $unsigned(tmp_1_fu_259_p3);
assign grp_fu_284_ce = ap_const_logic_1;
assign grp_fu_284_p0 = p_addr_cast_fu_281_p1;
assign grp_fu_284_p1 = $unsigned(indvar_i_reg_147);
assign grp_fu_293_ce = ap_const_logic_1;
assign grp_fu_293_p0 = p_addr_cast_fu_281_p1;
assign grp_fu_293_p1 = $unsigned(j_reg_538);
assign grp_fu_328_ce = ap_const_logic_1;
assign grp_fu_328_p0 = p_addr_cast_reg_569;
assign grp_fu_328_p1 = $unsigned(tmp6_i_reg_533);
assign grp_fu_368_ce = ap_const_logic_1;
assign grp_fu_368_p0 = $unsigned(tmp_5_fu_346_p3);
assign grp_fu_368_p1 = $unsigned(tmp_6_fu_357_p3);
assign grp_fu_377_ce = ap_const_logic_1;
assign grp_fu_377_p0 = $signed(p_addr8_reg_655);
assign grp_fu_377_p1 = tmp_4_i_trn_cast_reg_562;
assign grp_fu_417_ce = ap_const_logic_1;
assign grp_fu_417_p0 = $unsigned(tmp_s_fu_395_p3);
assign grp_fu_417_p1 = $unsigned(tmp_10_fu_406_p3);
assign grp_fu_423_ce = ap_const_logic_1;
assign grp_fu_423_p0 = p_addr8_cast_reg_660;
assign grp_fu_423_p1 = tmp_8_i_trn_cast_reg_576;
assign grp_fu_427_ce = ap_const_logic_1;
assign grp_fu_427_p0 = p_addr8_cast_reg_660;
assign grp_fu_427_p1 = tmp_12_i_trn_cast_reg_613;
assign grp_fu_434_ce = ap_const_logic_1;
assign grp_fu_434_p0 = p_addr6_cast_fu_431_p1;
assign grp_fu_434_p1 = tmp_4_i_trn_cast_reg_562;
assign grp_fu_439_ce = ap_const_logic_1;
assign grp_fu_439_p0 = p_addr6_cast_fu_431_p1;
assign grp_fu_439_p1 = tmp_8_i_trn_cast_reg_576;
assign grp_fu_444_ce = ap_const_logic_1;
assign grp_fu_444_p0 = p_addr6_cast_fu_431_p1;
assign grp_fu_444_p1 = tmp_12_i_trn_cast_reg_613;
assign out_r_address0 = tmp_8_reg_729;
assign out_r_d0 = tmp_14_reg_794;
assign p_addr6_cast_fu_431_p1 = $signed(p_addr6_reg_692);
assign p_addr8_cast_fu_374_p1 = $signed(p_addr8_reg_655);
assign p_addr_cast_fu_281_p1 = $signed(p_addr_reg_557);
assign tmp_10_fu_406_p3 = {{tmp_i_12_reg_520}, {ap_const_lv7_0}};
assign tmp_11_fu_468_p0 = $signed(p_addr7_reg_714);
assign tmp_11_fu_468_p1 = $unsigned(tmp_11_fu_468_p0);
assign tmp_12_fu_476_p0 = $signed(p_addr4_reg_719);
assign tmp_12_fu_476_p1 = $unsigned(tmp_12_fu_476_p0);
assign tmp_12_i_trn_cast_fu_325_p1 = $unsigned(tmp6_i_reg_533);
assign tmp_13_fu_489_p0 = $signed(p_addr1_reg_724);
assign tmp_13_fu_489_p1 = $unsigned(tmp_13_fu_489_p0);
assign tmp_14_fu_512_p1 = grp_fu_177_p1[15:0];
assign tmp_14_i5_fu_341_p1 = $unsigned(reg_186);
assign tmp_18_i6_fu_390_p1 = $unsigned(reg_186);
assign tmp_1_fu_259_p3 = {{indvar1_i_reg_135}, {ap_const_lv7_0}};
assign tmp_22_i7_fu_481_p1 = $unsigned(reg_186);
assign tmp_26_i8_fu_494_p1 = $unsigned(reg_190);
assign tmp_2_fu_302_p0 = $signed(p_addr2_reg_583);
assign tmp_2_fu_302_p1 = $unsigned(tmp_2_fu_302_p0);
assign tmp_30_i9_fu_499_p1 = $unsigned(reg_186);
assign tmp_34_i1_fu_504_p1 = $unsigned(in_load_7_reg_759);
assign tmp_38_i1_fu_508_p1 = $unsigned(in_load_8_reg_769);
assign tmp_3_fu_310_p0 = $signed(p_addr3_reg_588);
assign tmp_3_fu_310_p1 = $unsigned(tmp_3_fu_310_p0);
assign tmp_4_fu_336_p0 = $signed(p_addr5_reg_625);
assign tmp_4_fu_336_p1 = $unsigned(tmp_4_fu_336_p0);
assign tmp_4_i_trn_cast_fu_277_p1 = $unsigned(indvar_i_reg_147);
assign tmp_5_fu_346_p3 = {{i_reg_526}, {ap_const_lv11_0}};
assign tmp_6_fu_357_p3 = {{i_reg_526}, {ap_const_lv7_0}};
assign tmp_6_i3_fu_315_p1 = $unsigned(reg_186);
assign tmp_7_fu_385_p0 = $signed(p_addr9_reg_667);
assign tmp_7_fu_385_p1 = $unsigned(tmp_7_fu_385_p0);
assign tmp_8_fu_452_p0 = $signed(p_addr11_reg_704);
assign tmp_8_fu_452_p1 = $unsigned(tmp_8_fu_452_p0);
assign tmp_8_i_trn_cast_fu_290_p1 = $unsigned(j_reg_538);
assign tmp_9_fu_460_p0 = $signed(p_addr10_reg_709);
assign tmp_9_fu_460_p1 = $unsigned(tmp_9_fu_460_p0);
assign tmp_fu_247_p3 = {{indvar1_i_reg_135}, {ap_const_lv11_0}};
assign tmp_s_fu_395_p3 = {{tmp_i_12_reg_520}, {ap_const_lv11_0}};
always @ (posedge ap_clk)
begin
    tmp_4_i_trn_cast_reg_562[23:11] <= 13'b0000000000000;
    tmp_8_i_trn_cast_reg_576[23:11] <= 13'b0000000000000;
    tmp_12_i_trn_cast_reg_613[23:11] <= 13'b0000000000000;
    tmp_8_reg_729[63:32] <= 32'b00000000000000000000000000000000;
end



endmodule //gaussian

