// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "gaussian.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic gaussian::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic gaussian::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> gaussian::ap_ST_st1_fsm_0 = "00000000";
const sc_lv<8> gaussian::ap_ST_st2_fsm_1 = "1";
const sc_lv<8> gaussian::ap_ST_st3_fsm_2 = "10";
const sc_lv<8> gaussian::ap_ST_st4_fsm_3 = "11";
const sc_lv<8> gaussian::ap_ST_st5_fsm_4 = "100";
const sc_lv<8> gaussian::ap_ST_st6_fsm_5 = "101";
const sc_lv<8> gaussian::ap_ST_st7_fsm_6 = "110";
const sc_lv<8> gaussian::ap_ST_st8_fsm_7 = "111";
const sc_lv<8> gaussian::ap_ST_st9_fsm_8 = "1000";
const sc_lv<8> gaussian::ap_ST_st10_fsm_9 = "1001";
const sc_lv<8> gaussian::ap_ST_st11_fsm_10 = "1010";
const sc_lv<8> gaussian::ap_ST_st12_fsm_11 = "1011";
const sc_lv<8> gaussian::ap_ST_st13_fsm_12 = "1100";
const sc_lv<8> gaussian::ap_ST_st14_fsm_13 = "1101";
const sc_lv<8> gaussian::ap_ST_st15_fsm_14 = "1110";
const sc_lv<8> gaussian::ap_ST_st16_fsm_15 = "1111";
const sc_lv<8> gaussian::ap_ST_st17_fsm_16 = "10000";
const sc_lv<8> gaussian::ap_ST_st18_fsm_17 = "10001";
const sc_lv<8> gaussian::ap_ST_st19_fsm_18 = "10010";
const sc_lv<8> gaussian::ap_ST_st20_fsm_19 = "10011";
const sc_lv<8> gaussian::ap_ST_st21_fsm_20 = "10100";
const sc_lv<8> gaussian::ap_ST_st22_fsm_21 = "10101";
const sc_lv<8> gaussian::ap_ST_st23_fsm_22 = "10110";
const sc_lv<8> gaussian::ap_ST_st24_fsm_23 = "10111";
const sc_lv<8> gaussian::ap_ST_st25_fsm_24 = "11000";
const sc_lv<8> gaussian::ap_ST_st26_fsm_25 = "11001";
const sc_lv<8> gaussian::ap_ST_st27_fsm_26 = "11010";
const sc_lv<8> gaussian::ap_ST_st28_fsm_27 = "11011";
const sc_lv<8> gaussian::ap_ST_st29_fsm_28 = "11100";
const sc_lv<8> gaussian::ap_ST_st30_fsm_29 = "11101";
const sc_lv<8> gaussian::ap_ST_st31_fsm_30 = "11110";
const sc_lv<8> gaussian::ap_ST_st32_fsm_31 = "11111";
const sc_lv<8> gaussian::ap_ST_st33_fsm_32 = "100000";
const sc_lv<8> gaussian::ap_ST_st34_fsm_33 = "100001";
const sc_lv<8> gaussian::ap_ST_st35_fsm_34 = "100010";
const sc_lv<8> gaussian::ap_ST_st36_fsm_35 = "100011";
const sc_lv<8> gaussian::ap_ST_st37_fsm_36 = "100100";
const sc_lv<8> gaussian::ap_ST_st38_fsm_37 = "100101";
const sc_lv<8> gaussian::ap_ST_st39_fsm_38 = "100110";
const sc_lv<8> gaussian::ap_ST_st40_fsm_39 = "100111";
const sc_lv<8> gaussian::ap_ST_st41_fsm_40 = "101000";
const sc_lv<8> gaussian::ap_ST_st42_fsm_41 = "101001";
const sc_lv<8> gaussian::ap_ST_st43_fsm_42 = "101010";
const sc_lv<8> gaussian::ap_ST_st44_fsm_43 = "101011";
const sc_lv<8> gaussian::ap_ST_st45_fsm_44 = "101100";
const sc_lv<8> gaussian::ap_ST_st46_fsm_45 = "101101";
const sc_lv<8> gaussian::ap_ST_st47_fsm_46 = "101110";
const sc_lv<8> gaussian::ap_ST_st48_fsm_47 = "101111";
const sc_lv<8> gaussian::ap_ST_st49_fsm_48 = "110000";
const sc_lv<8> gaussian::ap_ST_st50_fsm_49 = "110001";
const sc_lv<8> gaussian::ap_ST_st51_fsm_50 = "110010";
const sc_lv<8> gaussian::ap_ST_st52_fsm_51 = "110011";
const sc_lv<8> gaussian::ap_ST_st53_fsm_52 = "110100";
const sc_lv<8> gaussian::ap_ST_st54_fsm_53 = "110101";
const sc_lv<8> gaussian::ap_ST_st55_fsm_54 = "110110";
const sc_lv<8> gaussian::ap_ST_st56_fsm_55 = "110111";
const sc_lv<8> gaussian::ap_ST_st57_fsm_56 = "111000";
const sc_lv<8> gaussian::ap_ST_st58_fsm_57 = "111001";
const sc_lv<8> gaussian::ap_ST_st59_fsm_58 = "111010";
const sc_lv<8> gaussian::ap_ST_st60_fsm_59 = "111011";
const sc_lv<8> gaussian::ap_ST_st61_fsm_60 = "111100";
const sc_lv<8> gaussian::ap_ST_st62_fsm_61 = "111101";
const sc_lv<8> gaussian::ap_ST_st63_fsm_62 = "111110";
const sc_lv<8> gaussian::ap_ST_st64_fsm_63 = "111111";
const sc_lv<8> gaussian::ap_ST_st65_fsm_64 = "1000000";
const sc_lv<8> gaussian::ap_ST_st66_fsm_65 = "1000001";
const sc_lv<8> gaussian::ap_ST_st67_fsm_66 = "1000010";
const sc_lv<8> gaussian::ap_ST_st68_fsm_67 = "1000011";
const sc_lv<8> gaussian::ap_ST_st69_fsm_68 = "1000100";
const sc_lv<8> gaussian::ap_ST_st70_fsm_69 = "1000101";
const sc_lv<8> gaussian::ap_ST_st71_fsm_70 = "1000110";
const sc_lv<8> gaussian::ap_ST_st72_fsm_71 = "1000111";
const sc_lv<8> gaussian::ap_ST_st73_fsm_72 = "1001000";
const sc_lv<8> gaussian::ap_ST_st74_fsm_73 = "1001001";
const sc_lv<8> gaussian::ap_ST_st75_fsm_74 = "1001010";
const sc_lv<8> gaussian::ap_ST_st76_fsm_75 = "1001011";
const sc_lv<8> gaussian::ap_ST_st77_fsm_76 = "1001100";
const sc_lv<8> gaussian::ap_ST_st78_fsm_77 = "1001101";
const sc_lv<8> gaussian::ap_ST_st79_fsm_78 = "1001110";
const sc_lv<8> gaussian::ap_ST_st80_fsm_79 = "1001111";
const sc_lv<8> gaussian::ap_ST_st81_fsm_80 = "1010000";
const sc_lv<8> gaussian::ap_ST_st82_fsm_81 = "1010001";
const sc_lv<8> gaussian::ap_ST_st83_fsm_82 = "1010010";
const sc_lv<8> gaussian::ap_ST_st84_fsm_83 = "1010011";
const sc_lv<8> gaussian::ap_ST_st85_fsm_84 = "1010100";
const sc_lv<8> gaussian::ap_ST_st86_fsm_85 = "1010101";
const sc_lv<8> gaussian::ap_ST_st87_fsm_86 = "1010110";
const sc_lv<8> gaussian::ap_ST_st88_fsm_87 = "1010111";
const sc_lv<8> gaussian::ap_ST_st89_fsm_88 = "1011000";
const sc_lv<8> gaussian::ap_ST_st90_fsm_89 = "1011001";
const sc_lv<8> gaussian::ap_ST_st91_fsm_90 = "1011010";
const sc_lv<8> gaussian::ap_ST_st92_fsm_91 = "1011011";
const sc_lv<8> gaussian::ap_ST_st93_fsm_92 = "1011100";
const sc_lv<8> gaussian::ap_ST_st94_fsm_93 = "1011101";
const sc_lv<8> gaussian::ap_ST_st95_fsm_94 = "1011110";
const sc_lv<8> gaussian::ap_ST_st96_fsm_95 = "1011111";
const sc_lv<8> gaussian::ap_ST_st97_fsm_96 = "1100000";
const sc_lv<8> gaussian::ap_ST_st98_fsm_97 = "1100001";
const sc_lv<8> gaussian::ap_ST_st99_fsm_98 = "1100010";
const sc_lv<8> gaussian::ap_ST_st100_fsm_99 = "1100011";
const sc_lv<8> gaussian::ap_ST_st101_fsm_100 = "1100100";
const sc_lv<8> gaussian::ap_ST_st102_fsm_101 = "1100101";
const sc_lv<8> gaussian::ap_ST_st103_fsm_102 = "1100110";
const sc_lv<8> gaussian::ap_ST_st104_fsm_103 = "1100111";
const sc_lv<8> gaussian::ap_ST_st105_fsm_104 = "1101000";
const sc_lv<8> gaussian::ap_ST_st106_fsm_105 = "1101001";
const sc_lv<8> gaussian::ap_ST_st107_fsm_106 = "1101010";
const sc_lv<8> gaussian::ap_ST_st108_fsm_107 = "1101011";
const sc_lv<8> gaussian::ap_ST_st109_fsm_108 = "1101100";
const sc_lv<8> gaussian::ap_ST_st110_fsm_109 = "1101101";
const sc_lv<8> gaussian::ap_ST_st111_fsm_110 = "1101110";
const sc_lv<8> gaussian::ap_ST_st112_fsm_111 = "1101111";
const sc_lv<8> gaussian::ap_ST_st113_fsm_112 = "1110000";
const sc_lv<8> gaussian::ap_ST_st114_fsm_113 = "1110001";
const sc_lv<8> gaussian::ap_ST_st115_fsm_114 = "1110010";
const sc_lv<8> gaussian::ap_ST_st116_fsm_115 = "1110011";
const sc_lv<8> gaussian::ap_ST_st117_fsm_116 = "1110100";
const sc_lv<8> gaussian::ap_ST_st118_fsm_117 = "1110101";
const sc_lv<8> gaussian::ap_ST_st119_fsm_118 = "1110110";
const sc_lv<8> gaussian::ap_ST_st120_fsm_119 = "1110111";
const sc_lv<8> gaussian::ap_ST_st121_fsm_120 = "1111000";
const sc_lv<8> gaussian::ap_ST_st122_fsm_121 = "1111001";
const sc_lv<8> gaussian::ap_ST_st123_fsm_122 = "1111010";
const sc_lv<8> gaussian::ap_ST_st124_fsm_123 = "1111011";
const sc_lv<8> gaussian::ap_ST_st125_fsm_124 = "1111100";
const sc_lv<8> gaussian::ap_ST_st126_fsm_125 = "1111101";
const sc_lv<8> gaussian::ap_ST_st127_fsm_126 = "1111110";
const sc_lv<8> gaussian::ap_ST_st128_fsm_127 = "1111111";
const sc_lv<8> gaussian::ap_ST_st129_fsm_128 = "10000000";
const sc_lv<8> gaussian::ap_ST_st130_fsm_129 = "10000001";
const sc_lv<8> gaussian::ap_ST_st131_fsm_130 = "10000010";
const sc_lv<8> gaussian::ap_ST_st132_fsm_131 = "10000011";
const sc_lv<8> gaussian::ap_ST_st133_fsm_132 = "10000100";
const sc_lv<8> gaussian::ap_ST_st134_fsm_133 = "10000101";
const sc_lv<8> gaussian::ap_ST_st135_fsm_134 = "10000110";
const sc_lv<8> gaussian::ap_ST_st136_fsm_135 = "10000111";
const sc_lv<8> gaussian::ap_ST_st137_fsm_136 = "10001000";
const sc_lv<8> gaussian::ap_ST_st138_fsm_137 = "10001001";
const sc_lv<8> gaussian::ap_ST_st139_fsm_138 = "10001010";
const sc_lv<8> gaussian::ap_ST_st140_fsm_139 = "10001011";
const sc_lv<8> gaussian::ap_ST_st141_fsm_140 = "10001100";
const sc_lv<8> gaussian::ap_ST_st142_fsm_141 = "10001101";
const sc_lv<8> gaussian::ap_ST_st143_fsm_142 = "10001110";
const sc_lv<8> gaussian::ap_ST_st144_fsm_143 = "10001111";
const sc_lv<8> gaussian::ap_ST_st145_fsm_144 = "10010000";
const sc_lv<8> gaussian::ap_ST_st146_fsm_145 = "10010001";
const sc_lv<8> gaussian::ap_ST_st147_fsm_146 = "10010010";
const sc_lv<8> gaussian::ap_ST_st148_fsm_147 = "10010011";
const sc_lv<8> gaussian::ap_ST_st149_fsm_148 = "10010100";
const sc_lv<8> gaussian::ap_ST_st150_fsm_149 = "10010101";
const sc_lv<8> gaussian::ap_ST_st151_fsm_150 = "10010110";
const sc_lv<8> gaussian::ap_ST_st152_fsm_151 = "10010111";
const sc_lv<8> gaussian::ap_ST_st153_fsm_152 = "10011000";
const sc_lv<8> gaussian::ap_ST_st154_fsm_153 = "10011001";
const sc_lv<8> gaussian::ap_ST_st155_fsm_154 = "10011010";
const sc_lv<8> gaussian::ap_ST_st156_fsm_155 = "10011011";
const sc_lv<8> gaussian::ap_ST_st157_fsm_156 = "10011100";
const sc_lv<8> gaussian::ap_ST_st158_fsm_157 = "10011101";
const sc_lv<1> gaussian::ap_const_lv1_0 = "0";
const sc_lv<11> gaussian::ap_const_lv11_0 = "00000000000";
const sc_lv<32> gaussian::ap_const_lv32_3D7929ED = "111101011110010010100111101101";
const sc_lv<32> gaussian::ap_const_lv32_3E193AF7 = "111110000110010011101011110111";
const sc_lv<32> gaussian::ap_const_lv32_3EBC7736 = "111110101111000111011100110110";
const sc_lv<32> gaussian::ap_const_lv32_3E19389B = "111110000110010011100010011011";
const sc_lv<11> gaussian::ap_const_lv11_2 = "10";
const sc_lv<11> gaussian::ap_const_lv11_1 = "1";
const sc_lv<11> gaussian::ap_const_lv11_436 = "10000110110";
const sc_lv<11> gaussian::ap_const_lv11_77E = "11101111110";
const sc_lv<7> gaussian::ap_const_lv7_0 = "0000000";

gaussian::gaussian(sc_module_name name) : sc_module(name), mVcdFile(0) {
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1 = new gaussian_fadd_32ns_32ns_32_14_no_dsp<1,14,32,32,32>("gaussian_fadd_32ns_32ns_32_14_no_dsp_U1");
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1->clk(ap_clk);
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1->reset(ap_rst);
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1->din0(grp_fu_160_p0);
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1->din1(grp_fu_160_p1);
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1->ce(grp_fu_160_ce);
    gaussian_fadd_32ns_32ns_32_14_no_dsp_U1->dout(grp_fu_160_p2);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2 = new gaussian_fmul_32ns_32ns_32_8_max_dsp<2,8,32,32,32>("gaussian_fmul_32ns_32ns_32_8_max_dsp_U2");
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2->clk(ap_clk);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2->reset(ap_rst);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2->din0(grp_fu_164_p0);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2->din1(grp_fu_164_p1);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2->ce(grp_fu_164_ce);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U2->dout(grp_fu_164_p2);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3 = new gaussian_fmul_32ns_32ns_32_8_max_dsp<3,8,32,32,32>("gaussian_fmul_32ns_32ns_32_8_max_dsp_U3");
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3->clk(ap_clk);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3->reset(ap_rst);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3->din0(grp_fu_169_p0);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3->din1(grp_fu_169_p1);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3->ce(grp_fu_169_ce);
    gaussian_fmul_32ns_32ns_32_8_max_dsp_U3->dout(grp_fu_169_p2);
    gaussian_fptoui_32ns_64_8_U4 = new gaussian_fptoui_32ns_64_8<4,8,32,64>("gaussian_fptoui_32ns_64_8_U4");
    gaussian_fptoui_32ns_64_8_U4->clk(ap_clk);
    gaussian_fptoui_32ns_64_8_U4->reset(ap_rst);
    gaussian_fptoui_32ns_64_8_U4->din0(grp_fu_177_p0);
    gaussian_fptoui_32ns_64_8_U4->ce(grp_fu_177_ce);
    gaussian_fptoui_32ns_64_8_U4->dout(grp_fu_177_p1);
    gaussian_sitofp_64ns_32_9_U5 = new gaussian_sitofp_64ns_32_9<5,9,64,32>("gaussian_sitofp_64ns_32_9_U5");
    gaussian_sitofp_64ns_32_9_U5->clk(ap_clk);
    gaussian_sitofp_64ns_32_9_U5->reset(ap_rst);
    gaussian_sitofp_64ns_32_9_U5->din0(grp_fu_180_p0);
    gaussian_sitofp_64ns_32_9_U5->ce(grp_fu_180_ce);
    gaussian_sitofp_64ns_32_9_U5->dout(grp_fu_180_p1);
    gaussian_sitofp_64ns_32_9_U6 = new gaussian_sitofp_64ns_32_9<6,9,64,32>("gaussian_sitofp_64ns_32_9_U6");
    gaussian_sitofp_64ns_32_9_U6->clk(ap_clk);
    gaussian_sitofp_64ns_32_9_U6->reset(ap_rst);
    gaussian_sitofp_64ns_32_9_U6->din0(grp_fu_183_p0);
    gaussian_sitofp_64ns_32_9_U6->ce(grp_fu_183_ce);
    gaussian_sitofp_64ns_32_9_U6->dout(grp_fu_183_p1);
    gaussian_add_11ns_11ns_11_3_U7 = new gaussian_add_11ns_11ns_11_3<7,3,11,11,11>("gaussian_add_11ns_11ns_11_3_U7");
    gaussian_add_11ns_11ns_11_3_U7->clk(ap_clk);
    gaussian_add_11ns_11ns_11_3_U7->reset(ap_rst);
    gaussian_add_11ns_11ns_11_3_U7->din0(grp_fu_211_p0);
    gaussian_add_11ns_11ns_11_3_U7->din1(grp_fu_211_p1);
    gaussian_add_11ns_11ns_11_3_U7->ce(grp_fu_211_ce);
    gaussian_add_11ns_11ns_11_3_U7->dout(grp_fu_211_p2);
    gaussian_add_11ns_11ns_11_3_U8 = new gaussian_add_11ns_11ns_11_3<8,3,11,11,11>("gaussian_add_11ns_11ns_11_3_U8");
    gaussian_add_11ns_11ns_11_3_U8->clk(ap_clk);
    gaussian_add_11ns_11ns_11_3_U8->reset(ap_rst);
    gaussian_add_11ns_11ns_11_3_U8->din0(grp_fu_217_p0);
    gaussian_add_11ns_11ns_11_3_U8->din1(grp_fu_217_p1);
    gaussian_add_11ns_11ns_11_3_U8->ce(grp_fu_217_ce);
    gaussian_add_11ns_11ns_11_3_U8->dout(grp_fu_217_p2);
    gaussian_add_11ns_11ns_11_3_U9 = new gaussian_add_11ns_11ns_11_3<9,3,11,11,11>("gaussian_add_11ns_11ns_11_3_U9");
    gaussian_add_11ns_11ns_11_3_U9->clk(ap_clk);
    gaussian_add_11ns_11ns_11_3_U9->reset(ap_rst);
    gaussian_add_11ns_11ns_11_3_U9->din0(grp_fu_229_p0);
    gaussian_add_11ns_11ns_11_3_U9->din1(grp_fu_229_p1);
    gaussian_add_11ns_11ns_11_3_U9->ce(grp_fu_229_ce);
    gaussian_add_11ns_11ns_11_3_U9->dout(grp_fu_229_p2);
    gaussian_add_11ns_11ns_11_3_U10 = new gaussian_add_11ns_11ns_11_3<10,3,11,11,11>("gaussian_add_11ns_11ns_11_3_U10");
    gaussian_add_11ns_11ns_11_3_U10->clk(ap_clk);
    gaussian_add_11ns_11ns_11_3_U10->reset(ap_rst);
    gaussian_add_11ns_11ns_11_3_U10->din0(grp_fu_235_p0);
    gaussian_add_11ns_11ns_11_3_U10->din1(grp_fu_235_p1);
    gaussian_add_11ns_11ns_11_3_U10->ce(grp_fu_235_ce);
    gaussian_add_11ns_11ns_11_3_U10->dout(grp_fu_235_p2);
    gaussian_sub_23ns_23ns_23_6_U11 = new gaussian_sub_23ns_23ns_23_6<11,6,23,23,23>("gaussian_sub_23ns_23ns_23_6_U11");
    gaussian_sub_23ns_23ns_23_6_U11->clk(ap_clk);
    gaussian_sub_23ns_23ns_23_6_U11->reset(ap_rst);
    gaussian_sub_23ns_23ns_23_6_U11->din0(grp_fu_271_p0);
    gaussian_sub_23ns_23ns_23_6_U11->din1(grp_fu_271_p1);
    gaussian_sub_23ns_23ns_23_6_U11->ce(grp_fu_271_ce);
    gaussian_sub_23ns_23ns_23_6_U11->dout(grp_fu_271_p2);
    gaussian_add_24s_24ns_24_6_U12 = new gaussian_add_24s_24ns_24_6<12,6,24,24,24>("gaussian_add_24s_24ns_24_6_U12");
    gaussian_add_24s_24ns_24_6_U12->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U12->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U12->din0(grp_fu_284_p0);
    gaussian_add_24s_24ns_24_6_U12->din1(grp_fu_284_p1);
    gaussian_add_24s_24ns_24_6_U12->ce(grp_fu_284_ce);
    gaussian_add_24s_24ns_24_6_U12->dout(grp_fu_284_p2);
    gaussian_add_24s_24ns_24_6_U13 = new gaussian_add_24s_24ns_24_6<13,6,24,24,24>("gaussian_add_24s_24ns_24_6_U13");
    gaussian_add_24s_24ns_24_6_U13->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U13->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U13->din0(grp_fu_293_p0);
    gaussian_add_24s_24ns_24_6_U13->din1(grp_fu_293_p1);
    gaussian_add_24s_24ns_24_6_U13->ce(grp_fu_293_ce);
    gaussian_add_24s_24ns_24_6_U13->dout(grp_fu_293_p2);
    gaussian_add_24s_24ns_24_6_U14 = new gaussian_add_24s_24ns_24_6<14,6,24,24,24>("gaussian_add_24s_24ns_24_6_U14");
    gaussian_add_24s_24ns_24_6_U14->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U14->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U14->din0(grp_fu_328_p0);
    gaussian_add_24s_24ns_24_6_U14->din1(grp_fu_328_p1);
    gaussian_add_24s_24ns_24_6_U14->ce(grp_fu_328_ce);
    gaussian_add_24s_24ns_24_6_U14->dout(grp_fu_328_p2);
    gaussian_sub_23ns_23ns_23_6_U15 = new gaussian_sub_23ns_23ns_23_6<15,6,23,23,23>("gaussian_sub_23ns_23ns_23_6_U15");
    gaussian_sub_23ns_23ns_23_6_U15->clk(ap_clk);
    gaussian_sub_23ns_23ns_23_6_U15->reset(ap_rst);
    gaussian_sub_23ns_23ns_23_6_U15->din0(grp_fu_368_p0);
    gaussian_sub_23ns_23ns_23_6_U15->din1(grp_fu_368_p1);
    gaussian_sub_23ns_23ns_23_6_U15->ce(grp_fu_368_ce);
    gaussian_sub_23ns_23ns_23_6_U15->dout(grp_fu_368_p2);
    gaussian_add_24s_24ns_24_6_U16 = new gaussian_add_24s_24ns_24_6<16,6,24,24,24>("gaussian_add_24s_24ns_24_6_U16");
    gaussian_add_24s_24ns_24_6_U16->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U16->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U16->din0(grp_fu_377_p0);
    gaussian_add_24s_24ns_24_6_U16->din1(grp_fu_377_p1);
    gaussian_add_24s_24ns_24_6_U16->ce(grp_fu_377_ce);
    gaussian_add_24s_24ns_24_6_U16->dout(grp_fu_377_p2);
    gaussian_sub_23ns_23ns_23_6_U17 = new gaussian_sub_23ns_23ns_23_6<17,6,23,23,23>("gaussian_sub_23ns_23ns_23_6_U17");
    gaussian_sub_23ns_23ns_23_6_U17->clk(ap_clk);
    gaussian_sub_23ns_23ns_23_6_U17->reset(ap_rst);
    gaussian_sub_23ns_23ns_23_6_U17->din0(grp_fu_417_p0);
    gaussian_sub_23ns_23ns_23_6_U17->din1(grp_fu_417_p1);
    gaussian_sub_23ns_23ns_23_6_U17->ce(grp_fu_417_ce);
    gaussian_sub_23ns_23ns_23_6_U17->dout(grp_fu_417_p2);
    gaussian_add_24s_24ns_24_6_U18 = new gaussian_add_24s_24ns_24_6<18,6,24,24,24>("gaussian_add_24s_24ns_24_6_U18");
    gaussian_add_24s_24ns_24_6_U18->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U18->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U18->din0(grp_fu_423_p0);
    gaussian_add_24s_24ns_24_6_U18->din1(grp_fu_423_p1);
    gaussian_add_24s_24ns_24_6_U18->ce(grp_fu_423_ce);
    gaussian_add_24s_24ns_24_6_U18->dout(grp_fu_423_p2);
    gaussian_add_24s_24ns_24_6_U19 = new gaussian_add_24s_24ns_24_6<19,6,24,24,24>("gaussian_add_24s_24ns_24_6_U19");
    gaussian_add_24s_24ns_24_6_U19->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U19->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U19->din0(grp_fu_427_p0);
    gaussian_add_24s_24ns_24_6_U19->din1(grp_fu_427_p1);
    gaussian_add_24s_24ns_24_6_U19->ce(grp_fu_427_ce);
    gaussian_add_24s_24ns_24_6_U19->dout(grp_fu_427_p2);
    gaussian_add_24s_24ns_24_6_U20 = new gaussian_add_24s_24ns_24_6<20,6,24,24,24>("gaussian_add_24s_24ns_24_6_U20");
    gaussian_add_24s_24ns_24_6_U20->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U20->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U20->din0(grp_fu_434_p0);
    gaussian_add_24s_24ns_24_6_U20->din1(grp_fu_434_p1);
    gaussian_add_24s_24ns_24_6_U20->ce(grp_fu_434_ce);
    gaussian_add_24s_24ns_24_6_U20->dout(grp_fu_434_p2);
    gaussian_add_24s_24ns_24_6_U21 = new gaussian_add_24s_24ns_24_6<21,6,24,24,24>("gaussian_add_24s_24ns_24_6_U21");
    gaussian_add_24s_24ns_24_6_U21->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U21->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U21->din0(grp_fu_439_p0);
    gaussian_add_24s_24ns_24_6_U21->din1(grp_fu_439_p1);
    gaussian_add_24s_24ns_24_6_U21->ce(grp_fu_439_ce);
    gaussian_add_24s_24ns_24_6_U21->dout(grp_fu_439_p2);
    gaussian_add_24s_24ns_24_6_U22 = new gaussian_add_24s_24ns_24_6<22,6,24,24,24>("gaussian_add_24s_24ns_24_6_U22");
    gaussian_add_24s_24ns_24_6_U22->clk(ap_clk);
    gaussian_add_24s_24ns_24_6_U22->reset(ap_rst);
    gaussian_add_24s_24ns_24_6_U22->din0(grp_fu_444_p0);
    gaussian_add_24s_24ns_24_6_U22->din1(grp_fu_444_p1);
    gaussian_add_24s_24ns_24_6_U22->ce(grp_fu_444_ce);
    gaussian_add_24s_24ns_24_6_U22->dout(grp_fu_444_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_516 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_516 );

    SC_METHOD(thread_exitcond1_fu_241_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar_i_reg_147 );

    SC_METHOD(thread_exitcond_fu_223_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar1_i_reg_135 );

    SC_METHOD(thread_grp_fu_160_ce);

    SC_METHOD(thread_grp_fu_160_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_199 );
    sensitive << ( reg_205 );

    SC_METHOD(thread_grp_fu_160_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_199 );
    sensitive << ( tmp_10_i_reg_650 );

    SC_METHOD(thread_grp_fu_164_ce);

    SC_METHOD(thread_grp_fu_164_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_194 );

    SC_METHOD(thread_grp_fu_164_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_169_ce);

    SC_METHOD(thread_grp_fu_169_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_i_reg_620 );

    SC_METHOD(thread_grp_fu_169_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_177_ce);

    SC_METHOD(thread_grp_fu_177_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_205 );

    SC_METHOD(thread_grp_fu_180_ce);

    SC_METHOD(thread_grp_fu_180_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_6_i3_fu_315_p1 );
    sensitive << ( tmp_14_i5_fu_341_p1 );
    sensitive << ( tmp_18_i6_fu_390_p1 );
    sensitive << ( tmp_22_i7_fu_481_p1 );
    sensitive << ( tmp_26_i8_fu_494_p1 );
    sensitive << ( tmp_30_i9_fu_499_p1 );
    sensitive << ( tmp_34_i1_fu_504_p1 );
    sensitive << ( tmp_38_i1_fu_508_p1 );

    SC_METHOD(thread_grp_fu_183_ce);

    SC_METHOD(thread_grp_fu_183_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_190 );

    SC_METHOD(thread_grp_fu_211_ce);

    SC_METHOD(thread_grp_fu_211_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar1_i_reg_135 );

    SC_METHOD(thread_grp_fu_211_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_217_ce);

    SC_METHOD(thread_grp_fu_217_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar1_i_reg_135 );

    SC_METHOD(thread_grp_fu_217_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_229_ce);

    SC_METHOD(thread_grp_fu_229_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar_i_reg_147 );

    SC_METHOD(thread_grp_fu_229_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_235_ce);

    SC_METHOD(thread_grp_fu_235_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar_i_reg_147 );

    SC_METHOD(thread_grp_fu_235_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_271_ce);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_241_p2 );

    SC_METHOD(thread_grp_fu_271_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_241_p2 );
    sensitive << ( tmp_fu_247_p3 );

    SC_METHOD(thread_grp_fu_271_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond1_fu_241_p2 );
    sensitive << ( tmp_1_fu_259_p3 );

    SC_METHOD(thread_grp_fu_284_ce);

    SC_METHOD(thread_grp_fu_284_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr_cast_fu_281_p1 );

    SC_METHOD(thread_grp_fu_284_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar_i_reg_147 );

    SC_METHOD(thread_grp_fu_293_ce);

    SC_METHOD(thread_grp_fu_293_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr_cast_fu_281_p1 );

    SC_METHOD(thread_grp_fu_293_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_538 );

    SC_METHOD(thread_grp_fu_328_ce);

    SC_METHOD(thread_grp_fu_328_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr_cast_reg_569 );

    SC_METHOD(thread_grp_fu_328_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp6_i_reg_533 );

    SC_METHOD(thread_grp_fu_368_ce);

    SC_METHOD(thread_grp_fu_368_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_5_fu_346_p3 );

    SC_METHOD(thread_grp_fu_368_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_6_fu_357_p3 );

    SC_METHOD(thread_grp_fu_377_ce);

    SC_METHOD(thread_grp_fu_377_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr8_reg_655 );

    SC_METHOD(thread_grp_fu_377_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_4_i_trn_cast_reg_562 );

    SC_METHOD(thread_grp_fu_417_ce);

    SC_METHOD(thread_grp_fu_417_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_s_fu_395_p3 );

    SC_METHOD(thread_grp_fu_417_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_10_fu_406_p3 );

    SC_METHOD(thread_grp_fu_423_ce);

    SC_METHOD(thread_grp_fu_423_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr8_cast_reg_660 );

    SC_METHOD(thread_grp_fu_423_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_8_i_trn_cast_reg_576 );

    SC_METHOD(thread_grp_fu_427_ce);

    SC_METHOD(thread_grp_fu_427_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr8_cast_reg_660 );

    SC_METHOD(thread_grp_fu_427_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_12_i_trn_cast_reg_613 );

    SC_METHOD(thread_grp_fu_434_ce);

    SC_METHOD(thread_grp_fu_434_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr6_cast_fu_431_p1 );

    SC_METHOD(thread_grp_fu_434_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_4_i_trn_cast_reg_562 );

    SC_METHOD(thread_grp_fu_439_ce);

    SC_METHOD(thread_grp_fu_439_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr6_cast_fu_431_p1 );

    SC_METHOD(thread_grp_fu_439_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_8_i_trn_cast_reg_576 );

    SC_METHOD(thread_grp_fu_444_ce);

    SC_METHOD(thread_grp_fu_444_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr6_cast_fu_431_p1 );

    SC_METHOD(thread_grp_fu_444_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_12_i_trn_cast_reg_613 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_8_fu_452_p1 );
    sensitive << ( tmp_2_fu_302_p1 );
    sensitive << ( tmp_4_fu_336_p1 );
    sensitive << ( tmp_7_fu_385_p1 );
    sensitive << ( tmp_11_fu_468_p1 );
    sensitive << ( tmp_13_fu_489_p1 );

    SC_METHOD(thread_in_r_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_3_fu_310_p1 );
    sensitive << ( tmp_9_fu_460_p1 );
    sensitive << ( tmp_12_fu_476_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_in_r_ce1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_8_reg_729 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_14_reg_794 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_p_addr6_cast_fu_431_p1);
    sensitive << ( p_addr6_reg_692 );

    SC_METHOD(thread_p_addr8_cast_fu_374_p1);
    sensitive << ( p_addr8_reg_655 );

    SC_METHOD(thread_p_addr_cast_fu_281_p1);
    sensitive << ( p_addr_reg_557 );

    SC_METHOD(thread_tmp_10_fu_406_p3);
    sensitive << ( tmp_i_12_reg_520 );

    SC_METHOD(thread_tmp_11_fu_468_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr7_reg_714 );

    SC_METHOD(thread_tmp_11_fu_468_p1);
    sensitive << ( tmp_11_fu_468_p0 );

    SC_METHOD(thread_tmp_12_fu_476_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr4_reg_719 );

    SC_METHOD(thread_tmp_12_fu_476_p1);
    sensitive << ( tmp_12_fu_476_p0 );

    SC_METHOD(thread_tmp_12_i_trn_cast_fu_325_p1);
    sensitive << ( tmp6_i_reg_533 );

    SC_METHOD(thread_tmp_13_fu_489_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr1_reg_724 );

    SC_METHOD(thread_tmp_13_fu_489_p1);
    sensitive << ( tmp_13_fu_489_p0 );

    SC_METHOD(thread_tmp_14_fu_512_p1);
    sensitive << ( grp_fu_177_p1 );

    SC_METHOD(thread_tmp_14_i5_fu_341_p1);
    sensitive << ( reg_186 );

    SC_METHOD(thread_tmp_18_i6_fu_390_p1);
    sensitive << ( reg_186 );

    SC_METHOD(thread_tmp_1_fu_259_p3);
    sensitive << ( indvar1_i_reg_135 );

    SC_METHOD(thread_tmp_22_i7_fu_481_p1);
    sensitive << ( reg_186 );

    SC_METHOD(thread_tmp_26_i8_fu_494_p1);
    sensitive << ( reg_190 );

    SC_METHOD(thread_tmp_2_fu_302_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr2_reg_583 );

    SC_METHOD(thread_tmp_2_fu_302_p1);
    sensitive << ( tmp_2_fu_302_p0 );

    SC_METHOD(thread_tmp_30_i9_fu_499_p1);
    sensitive << ( reg_186 );

    SC_METHOD(thread_tmp_34_i1_fu_504_p1);
    sensitive << ( in_load_7_reg_759 );

    SC_METHOD(thread_tmp_38_i1_fu_508_p1);
    sensitive << ( in_load_8_reg_769 );

    SC_METHOD(thread_tmp_3_fu_310_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr3_reg_588 );

    SC_METHOD(thread_tmp_3_fu_310_p1);
    sensitive << ( tmp_3_fu_310_p0 );

    SC_METHOD(thread_tmp_4_fu_336_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr5_reg_625 );

    SC_METHOD(thread_tmp_4_fu_336_p1);
    sensitive << ( tmp_4_fu_336_p0 );

    SC_METHOD(thread_tmp_4_i_trn_cast_fu_277_p1);
    sensitive << ( indvar_i_reg_147 );

    SC_METHOD(thread_tmp_5_fu_346_p3);
    sensitive << ( i_reg_526 );

    SC_METHOD(thread_tmp_6_fu_357_p3);
    sensitive << ( i_reg_526 );

    SC_METHOD(thread_tmp_6_i3_fu_315_p1);
    sensitive << ( reg_186 );

    SC_METHOD(thread_tmp_7_fu_385_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr9_reg_667 );

    SC_METHOD(thread_tmp_7_fu_385_p1);
    sensitive << ( tmp_7_fu_385_p0 );

    SC_METHOD(thread_tmp_8_fu_452_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr11_reg_704 );

    SC_METHOD(thread_tmp_8_fu_452_p1);
    sensitive << ( tmp_8_fu_452_p0 );

    SC_METHOD(thread_tmp_8_i_trn_cast_fu_290_p1);
    sensitive << ( j_reg_538 );

    SC_METHOD(thread_tmp_9_fu_460_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr10_reg_709 );

    SC_METHOD(thread_tmp_9_fu_460_p1);
    sensitive << ( tmp_9_fu_460_p0 );

    SC_METHOD(thread_tmp_fu_247_p3);
    sensitive << ( indvar1_i_reg_135 );

    SC_METHOD(thread_tmp_s_fu_395_p3);
    sensitive << ( tmp_i_12_reg_520 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_reg_516 );
    sensitive << ( exitcond1_fu_241_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "gaussian_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, in_r_address1, "(port)in_r_address1");
    sc_trace(mVcdFile, in_r_ce1, "(port)in_r_ce1");
    sc_trace(mVcdFile, in_r_q1, "(port)in_r_q1");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, reg_186, "reg_186");
    sc_trace(mVcdFile, reg_190, "reg_190");
    sc_trace(mVcdFile, grp_fu_180_p1, "grp_fu_180_p1");
    sc_trace(mVcdFile, reg_194, "reg_194");
    sc_trace(mVcdFile, grp_fu_164_p2, "grp_fu_164_p2");
    sc_trace(mVcdFile, reg_199, "reg_199");
    sc_trace(mVcdFile, grp_fu_160_p2, "grp_fu_160_p2");
    sc_trace(mVcdFile, reg_205, "reg_205");
    sc_trace(mVcdFile, exitcond_fu_223_p2, "exitcond_fu_223_p2");
    sc_trace(mVcdFile, exitcond_reg_516, "exitcond_reg_516");
    sc_trace(mVcdFile, grp_fu_211_p2, "grp_fu_211_p2");
    sc_trace(mVcdFile, tmp_i_12_reg_520, "tmp_i_12_reg_520");
    sc_trace(mVcdFile, grp_fu_217_p2, "grp_fu_217_p2");
    sc_trace(mVcdFile, i_reg_526, "i_reg_526");
    sc_trace(mVcdFile, grp_fu_229_p2, "grp_fu_229_p2");
    sc_trace(mVcdFile, tmp6_i_reg_533, "tmp6_i_reg_533");
    sc_trace(mVcdFile, grp_fu_235_p2, "grp_fu_235_p2");
    sc_trace(mVcdFile, j_reg_538, "j_reg_538");
    sc_trace(mVcdFile, exitcond1_fu_241_p2, "exitcond1_fu_241_p2");
    sc_trace(mVcdFile, grp_fu_271_p2, "grp_fu_271_p2");
    sc_trace(mVcdFile, p_addr_reg_557, "p_addr_reg_557");
    sc_trace(mVcdFile, tmp_4_i_trn_cast_fu_277_p1, "tmp_4_i_trn_cast_fu_277_p1");
    sc_trace(mVcdFile, tmp_4_i_trn_cast_reg_562, "tmp_4_i_trn_cast_reg_562");
    sc_trace(mVcdFile, p_addr_cast_fu_281_p1, "p_addr_cast_fu_281_p1");
    sc_trace(mVcdFile, p_addr_cast_reg_569, "p_addr_cast_reg_569");
    sc_trace(mVcdFile, tmp_8_i_trn_cast_fu_290_p1, "tmp_8_i_trn_cast_fu_290_p1");
    sc_trace(mVcdFile, tmp_8_i_trn_cast_reg_576, "tmp_8_i_trn_cast_reg_576");
    sc_trace(mVcdFile, grp_fu_284_p2, "grp_fu_284_p2");
    sc_trace(mVcdFile, p_addr2_reg_583, "p_addr2_reg_583");
    sc_trace(mVcdFile, grp_fu_293_p2, "grp_fu_293_p2");
    sc_trace(mVcdFile, p_addr3_reg_588, "p_addr3_reg_588");
    sc_trace(mVcdFile, tmp_6_i3_fu_315_p1, "tmp_6_i3_fu_315_p1");
    sc_trace(mVcdFile, tmp_12_i_trn_cast_fu_325_p1, "tmp_12_i_trn_cast_fu_325_p1");
    sc_trace(mVcdFile, tmp_12_i_trn_cast_reg_613, "tmp_12_i_trn_cast_reg_613");
    sc_trace(mVcdFile, grp_fu_183_p1, "grp_fu_183_p1");
    sc_trace(mVcdFile, tmp_i_reg_620, "tmp_i_reg_620");
    sc_trace(mVcdFile, grp_fu_328_p2, "grp_fu_328_p2");
    sc_trace(mVcdFile, p_addr5_reg_625, "p_addr5_reg_625");
    sc_trace(mVcdFile, tmp_14_i5_fu_341_p1, "tmp_14_i5_fu_341_p1");
    sc_trace(mVcdFile, grp_fu_169_p2, "grp_fu_169_p2");
    sc_trace(mVcdFile, tmp_10_i_reg_650, "tmp_10_i_reg_650");
    sc_trace(mVcdFile, grp_fu_368_p2, "grp_fu_368_p2");
    sc_trace(mVcdFile, p_addr8_reg_655, "p_addr8_reg_655");
    sc_trace(mVcdFile, p_addr8_cast_fu_374_p1, "p_addr8_cast_fu_374_p1");
    sc_trace(mVcdFile, p_addr8_cast_reg_660, "p_addr8_cast_reg_660");
    sc_trace(mVcdFile, grp_fu_377_p2, "grp_fu_377_p2");
    sc_trace(mVcdFile, p_addr9_reg_667, "p_addr9_reg_667");
    sc_trace(mVcdFile, tmp_18_i6_fu_390_p1, "tmp_18_i6_fu_390_p1");
    sc_trace(mVcdFile, grp_fu_417_p2, "grp_fu_417_p2");
    sc_trace(mVcdFile, p_addr6_reg_692, "p_addr6_reg_692");
    sc_trace(mVcdFile, p_addr6_cast_fu_431_p1, "p_addr6_cast_fu_431_p1");
    sc_trace(mVcdFile, grp_fu_423_p2, "grp_fu_423_p2");
    sc_trace(mVcdFile, p_addr11_reg_704, "p_addr11_reg_704");
    sc_trace(mVcdFile, grp_fu_427_p2, "grp_fu_427_p2");
    sc_trace(mVcdFile, p_addr10_reg_709, "p_addr10_reg_709");
    sc_trace(mVcdFile, grp_fu_434_p2, "grp_fu_434_p2");
    sc_trace(mVcdFile, p_addr7_reg_714, "p_addr7_reg_714");
    sc_trace(mVcdFile, grp_fu_439_p2, "grp_fu_439_p2");
    sc_trace(mVcdFile, p_addr4_reg_719, "p_addr4_reg_719");
    sc_trace(mVcdFile, grp_fu_444_p2, "grp_fu_444_p2");
    sc_trace(mVcdFile, p_addr1_reg_724, "p_addr1_reg_724");
    sc_trace(mVcdFile, tmp_8_fu_452_p1, "tmp_8_fu_452_p1");
    sc_trace(mVcdFile, tmp_8_reg_729, "tmp_8_reg_729");
    sc_trace(mVcdFile, tmp_22_i7_fu_481_p1, "tmp_22_i7_fu_481_p1");
    sc_trace(mVcdFile, in_load_7_reg_759, "in_load_7_reg_759");
    sc_trace(mVcdFile, in_load_8_reg_769, "in_load_8_reg_769");
    sc_trace(mVcdFile, tmp_26_i8_fu_494_p1, "tmp_26_i8_fu_494_p1");
    sc_trace(mVcdFile, tmp_30_i9_fu_499_p1, "tmp_30_i9_fu_499_p1");
    sc_trace(mVcdFile, tmp_34_i1_fu_504_p1, "tmp_34_i1_fu_504_p1");
    sc_trace(mVcdFile, tmp_38_i1_fu_508_p1, "tmp_38_i1_fu_508_p1");
    sc_trace(mVcdFile, tmp_14_fu_512_p1, "tmp_14_fu_512_p1");
    sc_trace(mVcdFile, tmp_14_reg_794, "tmp_14_reg_794");
    sc_trace(mVcdFile, indvar1_i_reg_135, "indvar1_i_reg_135");
    sc_trace(mVcdFile, indvar_i_reg_147, "indvar_i_reg_147");
    sc_trace(mVcdFile, tmp_2_fu_302_p1, "tmp_2_fu_302_p1");
    sc_trace(mVcdFile, tmp_3_fu_310_p1, "tmp_3_fu_310_p1");
    sc_trace(mVcdFile, tmp_4_fu_336_p1, "tmp_4_fu_336_p1");
    sc_trace(mVcdFile, tmp_7_fu_385_p1, "tmp_7_fu_385_p1");
    sc_trace(mVcdFile, tmp_9_fu_460_p1, "tmp_9_fu_460_p1");
    sc_trace(mVcdFile, tmp_11_fu_468_p1, "tmp_11_fu_468_p1");
    sc_trace(mVcdFile, tmp_12_fu_476_p1, "tmp_12_fu_476_p1");
    sc_trace(mVcdFile, tmp_13_fu_489_p1, "tmp_13_fu_489_p1");
    sc_trace(mVcdFile, grp_fu_160_p0, "grp_fu_160_p0");
    sc_trace(mVcdFile, grp_fu_160_p1, "grp_fu_160_p1");
    sc_trace(mVcdFile, grp_fu_164_p0, "grp_fu_164_p0");
    sc_trace(mVcdFile, grp_fu_164_p1, "grp_fu_164_p1");
    sc_trace(mVcdFile, grp_fu_169_p0, "grp_fu_169_p0");
    sc_trace(mVcdFile, grp_fu_169_p1, "grp_fu_169_p1");
    sc_trace(mVcdFile, grp_fu_177_p0, "grp_fu_177_p0");
    sc_trace(mVcdFile, grp_fu_180_p0, "grp_fu_180_p0");
    sc_trace(mVcdFile, grp_fu_183_p0, "grp_fu_183_p0");
    sc_trace(mVcdFile, grp_fu_211_p0, "grp_fu_211_p0");
    sc_trace(mVcdFile, grp_fu_211_p1, "grp_fu_211_p1");
    sc_trace(mVcdFile, grp_fu_217_p0, "grp_fu_217_p0");
    sc_trace(mVcdFile, grp_fu_217_p1, "grp_fu_217_p1");
    sc_trace(mVcdFile, grp_fu_229_p0, "grp_fu_229_p0");
    sc_trace(mVcdFile, grp_fu_229_p1, "grp_fu_229_p1");
    sc_trace(mVcdFile, grp_fu_235_p0, "grp_fu_235_p0");
    sc_trace(mVcdFile, grp_fu_235_p1, "grp_fu_235_p1");
    sc_trace(mVcdFile, tmp_fu_247_p3, "tmp_fu_247_p3");
    sc_trace(mVcdFile, tmp_1_fu_259_p3, "tmp_1_fu_259_p3");
    sc_trace(mVcdFile, grp_fu_271_p0, "grp_fu_271_p0");
    sc_trace(mVcdFile, grp_fu_271_p1, "grp_fu_271_p1");
    sc_trace(mVcdFile, grp_fu_284_p0, "grp_fu_284_p0");
    sc_trace(mVcdFile, grp_fu_284_p1, "grp_fu_284_p1");
    sc_trace(mVcdFile, grp_fu_293_p0, "grp_fu_293_p0");
    sc_trace(mVcdFile, grp_fu_293_p1, "grp_fu_293_p1");
    sc_trace(mVcdFile, tmp_2_fu_302_p0, "tmp_2_fu_302_p0");
    sc_trace(mVcdFile, tmp_3_fu_310_p0, "tmp_3_fu_310_p0");
    sc_trace(mVcdFile, grp_fu_328_p0, "grp_fu_328_p0");
    sc_trace(mVcdFile, grp_fu_328_p1, "grp_fu_328_p1");
    sc_trace(mVcdFile, tmp_4_fu_336_p0, "tmp_4_fu_336_p0");
    sc_trace(mVcdFile, tmp_5_fu_346_p3, "tmp_5_fu_346_p3");
    sc_trace(mVcdFile, tmp_6_fu_357_p3, "tmp_6_fu_357_p3");
    sc_trace(mVcdFile, grp_fu_368_p0, "grp_fu_368_p0");
    sc_trace(mVcdFile, grp_fu_368_p1, "grp_fu_368_p1");
    sc_trace(mVcdFile, grp_fu_377_p0, "grp_fu_377_p0");
    sc_trace(mVcdFile, grp_fu_377_p1, "grp_fu_377_p1");
    sc_trace(mVcdFile, tmp_7_fu_385_p0, "tmp_7_fu_385_p0");
    sc_trace(mVcdFile, tmp_s_fu_395_p3, "tmp_s_fu_395_p3");
    sc_trace(mVcdFile, tmp_10_fu_406_p3, "tmp_10_fu_406_p3");
    sc_trace(mVcdFile, grp_fu_417_p0, "grp_fu_417_p0");
    sc_trace(mVcdFile, grp_fu_417_p1, "grp_fu_417_p1");
    sc_trace(mVcdFile, grp_fu_423_p0, "grp_fu_423_p0");
    sc_trace(mVcdFile, grp_fu_423_p1, "grp_fu_423_p1");
    sc_trace(mVcdFile, grp_fu_427_p0, "grp_fu_427_p0");
    sc_trace(mVcdFile, grp_fu_427_p1, "grp_fu_427_p1");
    sc_trace(mVcdFile, grp_fu_434_p0, "grp_fu_434_p0");
    sc_trace(mVcdFile, grp_fu_434_p1, "grp_fu_434_p1");
    sc_trace(mVcdFile, grp_fu_439_p0, "grp_fu_439_p0");
    sc_trace(mVcdFile, grp_fu_439_p1, "grp_fu_439_p1");
    sc_trace(mVcdFile, grp_fu_444_p0, "grp_fu_444_p0");
    sc_trace(mVcdFile, grp_fu_444_p1, "grp_fu_444_p1");
    sc_trace(mVcdFile, tmp_8_fu_452_p0, "tmp_8_fu_452_p0");
    sc_trace(mVcdFile, tmp_9_fu_460_p0, "tmp_9_fu_460_p0");
    sc_trace(mVcdFile, tmp_11_fu_468_p0, "tmp_11_fu_468_p0");
    sc_trace(mVcdFile, tmp_12_fu_476_p0, "tmp_12_fu_476_p0");
    sc_trace(mVcdFile, tmp_13_fu_489_p0, "tmp_13_fu_489_p0");
    sc_trace(mVcdFile, grp_fu_177_p1, "grp_fu_177_p1");
    sc_trace(mVcdFile, grp_fu_160_ce, "grp_fu_160_ce");
    sc_trace(mVcdFile, grp_fu_164_ce, "grp_fu_164_ce");
    sc_trace(mVcdFile, grp_fu_169_ce, "grp_fu_169_ce");
    sc_trace(mVcdFile, grp_fu_177_ce, "grp_fu_177_ce");
    sc_trace(mVcdFile, grp_fu_180_ce, "grp_fu_180_ce");
    sc_trace(mVcdFile, grp_fu_183_ce, "grp_fu_183_ce");
    sc_trace(mVcdFile, grp_fu_211_ce, "grp_fu_211_ce");
    sc_trace(mVcdFile, grp_fu_217_ce, "grp_fu_217_ce");
    sc_trace(mVcdFile, grp_fu_229_ce, "grp_fu_229_ce");
    sc_trace(mVcdFile, grp_fu_235_ce, "grp_fu_235_ce");
    sc_trace(mVcdFile, grp_fu_271_ce, "grp_fu_271_ce");
    sc_trace(mVcdFile, grp_fu_284_ce, "grp_fu_284_ce");
    sc_trace(mVcdFile, grp_fu_293_ce, "grp_fu_293_ce");
    sc_trace(mVcdFile, grp_fu_328_ce, "grp_fu_328_ce");
    sc_trace(mVcdFile, grp_fu_368_ce, "grp_fu_368_ce");
    sc_trace(mVcdFile, grp_fu_377_ce, "grp_fu_377_ce");
    sc_trace(mVcdFile, grp_fu_417_ce, "grp_fu_417_ce");
    sc_trace(mVcdFile, grp_fu_423_ce, "grp_fu_423_ce");
    sc_trace(mVcdFile, grp_fu_427_ce, "grp_fu_427_ce");
    sc_trace(mVcdFile, grp_fu_434_ce, "grp_fu_434_ce");
    sc_trace(mVcdFile, grp_fu_439_ce, "grp_fu_439_ce");
    sc_trace(mVcdFile, grp_fu_444_ce, "grp_fu_444_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");

    }
    mHdltvinHandle.open("gaussian.hdltvin.dat");
    mHdltvoutHandle.open("gaussian.hdltvout.dat");
}

gaussian::~gaussian() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete gaussian_fadd_32ns_32ns_32_14_no_dsp_U1;
    delete gaussian_fmul_32ns_32ns_32_8_max_dsp_U2;
    delete gaussian_fmul_32ns_32ns_32_8_max_dsp_U3;
    delete gaussian_fptoui_32ns_64_8_U4;
    delete gaussian_sitofp_64ns_32_9_U5;
    delete gaussian_sitofp_64ns_32_9_U6;
    delete gaussian_add_11ns_11ns_11_3_U7;
    delete gaussian_add_11ns_11ns_11_3_U8;
    delete gaussian_add_11ns_11ns_11_3_U9;
    delete gaussian_add_11ns_11ns_11_3_U10;
    delete gaussian_sub_23ns_23ns_23_6_U11;
    delete gaussian_add_24s_24ns_24_6_U12;
    delete gaussian_add_24s_24ns_24_6_U13;
    delete gaussian_add_24s_24ns_24_6_U14;
    delete gaussian_sub_23ns_23ns_23_6_U15;
    delete gaussian_add_24s_24ns_24_6_U16;
    delete gaussian_sub_23ns_23ns_23_6_U17;
    delete gaussian_add_24s_24ns_24_6_U18;
    delete gaussian_add_24s_24ns_24_6_U19;
    delete gaussian_add_24s_24ns_24_6_U20;
    delete gaussian_add_24s_24ns_24_6_U21;
    delete gaussian_add_24s_24ns_24_6_U22;
}

void gaussian::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,8,8>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond1_fu_241_p2.read(), ap_const_lv1_0))) {
        indvar1_i_reg_135 = i_reg_526.read();
    } else if ((esl_seteq<1,8,8>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar1_i_reg_135 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,8,8>(ap_ST_st4_fsm_3, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond_reg_516.read(), ap_const_lv1_0))) {
        indvar_i_reg_147 = ap_const_lv11_0;
    } else if (esl_seteq<1,8,8>(ap_ST_st158_fsm_157, ap_CS_fsm.read())) {
        indvar_i_reg_147 = j_reg_538.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        exitcond_reg_516 = exitcond_fu_223_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        i_reg_526 = grp_fu_217_p2.read();
        tmp_i_12_reg_520 = grp_fu_211_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st63_fsm_62, ap_CS_fsm.read())) {
        in_load_7_reg_759 = in_r_q1.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st64_fsm_63, ap_CS_fsm.read())) {
        in_load_8_reg_769 = in_r_q0.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st7_fsm_6, ap_CS_fsm.read())) {
        j_reg_538 = grp_fu_235_p2.read();
        tmp6_i_reg_533 = grp_fu_229_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st60_fsm_59, ap_CS_fsm.read())) {
        p_addr10_reg_709 = grp_fu_427_p2.read();
        p_addr11_reg_704 = grp_fu_423_p2.read();
        p_addr1_reg_724 = grp_fu_444_p2.read();
        p_addr4_reg_719 = grp_fu_439_p2.read();
        p_addr7_reg_714 = grp_fu_434_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st18_fsm_17, ap_CS_fsm.read())) {
        p_addr2_reg_583 = grp_fu_284_p2.read();
        p_addr3_reg_588 = grp_fu_293_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st32_fsm_31, ap_CS_fsm.read())) {
        p_addr5_reg_625 = grp_fu_328_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st54_fsm_53, ap_CS_fsm.read())) {
        p_addr6_reg_692 = grp_fu_417_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st41_fsm_40, ap_CS_fsm.read())) {
        p_addr8_cast_reg_660 = p_addr8_cast_fu_374_p1.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st40_fsm_39, ap_CS_fsm.read())) {
        p_addr8_reg_655 = grp_fu_368_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st46_fsm_45, ap_CS_fsm.read())) {
        p_addr9_reg_667 = grp_fu_377_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st13_fsm_12, ap_CS_fsm.read())) {
        p_addr_cast_reg_569 = p_addr_cast_fu_281_p1.read();
        tmp_4_i_trn_cast_reg_562 = tmp_4_i_trn_cast_fu_277_p1.read();
        tmp_8_i_trn_cast_reg_576 = tmp_8_i_trn_cast_fu_290_p1.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st12_fsm_11, ap_CS_fsm.read())) {
        p_addr_reg_557 = grp_fu_271_p2.read();
    }
    if ((esl_seteq<1,8,8>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st34_fsm_33, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st48_fsm_47, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st62_fsm_61, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st63_fsm_62, ap_CS_fsm.read()))) {
        reg_186 = in_r_q0.read();
    }
    if ((esl_seteq<1,8,8>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st62_fsm_61, ap_CS_fsm.read()))) {
        reg_190 = in_r_q1.read();
    }
    if ((esl_seteq<1,8,8>(ap_ST_st29_fsm_28, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st43_fsm_42, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st57_fsm_56, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st71_fsm_70, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st85_fsm_84, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st99_fsm_98, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st113_fsm_112, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st127_fsm_126, ap_CS_fsm.read()))) {
        reg_194 = grp_fu_180_p1.read();
    }
    if ((esl_seteq<1,8,8>(ap_ST_st37_fsm_36, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st51_fsm_50, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st65_fsm_64, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st79_fsm_78, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st93_fsm_92, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st107_fsm_106, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st121_fsm_120, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st135_fsm_134, ap_CS_fsm.read()))) {
        reg_199 = grp_fu_164_p2.read();
    }
    if ((esl_seteq<1,8,8>(ap_ST_st51_fsm_50, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st65_fsm_64, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st79_fsm_78, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st93_fsm_92, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st107_fsm_106, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st121_fsm_120, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st135_fsm_134, ap_CS_fsm.read()) || esl_seteq<1,8,8>(ap_ST_st149_fsm_148, ap_CS_fsm.read()))) {
        reg_205 = grp_fu_160_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st37_fsm_36, ap_CS_fsm.read())) {
        tmp_10_i_reg_650 = grp_fu_169_p2.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st27_fsm_26, ap_CS_fsm.read())) {
        tmp_12_i_trn_cast_reg_613 = tmp_12_i_trn_cast_fu_325_p1.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st157_fsm_156, ap_CS_fsm.read())) {
        tmp_14_reg_794 = tmp_14_fu_512_p1.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st61_fsm_60, ap_CS_fsm.read())) {
        tmp_8_reg_729 = tmp_8_fu_452_p1.read();
    }
    if (esl_seteq<1,8,8>(ap_ST_st29_fsm_28, ap_CS_fsm.read())) {
        tmp_i_reg_620 = grp_fu_183_p1.read();
    }
}

void gaussian::thread_ap_done() {
    if ((esl_seteq<1,8,8>(ap_ST_st4_fsm_3, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond_reg_516.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void gaussian::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,8,8>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void gaussian::thread_ap_ready() {
    if ((esl_seteq<1,8,8>(ap_ST_st4_fsm_3, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond_reg_516.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void gaussian::thread_exitcond1_fu_241_p2() {
    exitcond1_fu_241_p2 = (!indvar_i_reg_147.read().is_01() || !ap_const_lv11_77E.is_01())? sc_lv<1>(): sc_lv<1>(indvar_i_reg_147.read() == ap_const_lv11_77E);
}

void gaussian::thread_exitcond_fu_223_p2() {
    exitcond_fu_223_p2 = (!indvar1_i_reg_135.read().is_01() || !ap_const_lv11_436.is_01())? sc_lv<1>(): sc_lv<1>(indvar1_i_reg_135.read() == ap_const_lv11_436);
}

void gaussian::thread_grp_fu_160_ce() {
    grp_fu_160_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_160_p0() {
    if ((esl_seteq<1,8,8>(ap_ST_st52_fsm_51, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st66_fsm_65, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st80_fsm_79, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st94_fsm_93, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st108_fsm_107, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st122_fsm_121, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st136_fsm_135, ap_CS_fsm.read()))) {
        grp_fu_160_p0 = reg_205.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st38_fsm_37, ap_CS_fsm.read())) {
        grp_fu_160_p0 = reg_199.read();
    } else {
        grp_fu_160_p0 = reg_205.read();
    }
}

void gaussian::thread_grp_fu_160_p1() {
    if ((esl_seteq<1,8,8>(ap_ST_st52_fsm_51, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st66_fsm_65, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st80_fsm_79, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st94_fsm_93, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st108_fsm_107, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st122_fsm_121, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st136_fsm_135, ap_CS_fsm.read()))) {
        grp_fu_160_p1 = reg_199.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st38_fsm_37, ap_CS_fsm.read())) {
        grp_fu_160_p1 = tmp_10_i_reg_650.read();
    } else {
        grp_fu_160_p1 = tmp_10_i_reg_650.read();
    }
}

void gaussian::thread_grp_fu_164_ce() {
    grp_fu_164_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_164_p0() {
    grp_fu_164_p0 = reg_194.read();
}

void gaussian::thread_grp_fu_164_p1() {
    if (esl_seteq<1,8,8>(ap_ST_st86_fsm_85, ap_CS_fsm.read())) {
        grp_fu_164_p1 = ap_const_lv32_3E19389B;
    } else if (esl_seteq<1,8,8>(ap_ST_st72_fsm_71, ap_CS_fsm.read())) {
        grp_fu_164_p1 = ap_const_lv32_3EBC7736;
    } else if ((esl_seteq<1,8,8>(ap_ST_st58_fsm_57, ap_CS_fsm.read()) || 
                esl_seteq<1,8,8>(ap_ST_st114_fsm_113, ap_CS_fsm.read()))) {
        grp_fu_164_p1 = ap_const_lv32_3E193AF7;
    } else if ((esl_seteq<1,8,8>(ap_ST_st30_fsm_29, ap_CS_fsm.read()) || 
                esl_seteq<1,8,8>(ap_ST_st44_fsm_43, ap_CS_fsm.read()) || 
                esl_seteq<1,8,8>(ap_ST_st100_fsm_99, ap_CS_fsm.read()) || 
                esl_seteq<1,8,8>(ap_ST_st128_fsm_127, ap_CS_fsm.read()))) {
        grp_fu_164_p1 = ap_const_lv32_3D7929ED;
    } else {
        grp_fu_164_p1 = ap_const_lv32_3E19389B;
    }
}

void gaussian::thread_grp_fu_169_ce() {
    grp_fu_169_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_169_p0() {
    grp_fu_169_p0 = tmp_i_reg_620.read();
}

void gaussian::thread_grp_fu_169_p1() {
    grp_fu_169_p1 = ap_const_lv32_3E193AF7;
}

void gaussian::thread_grp_fu_177_ce() {
    grp_fu_177_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_177_p0() {
    grp_fu_177_p0 = reg_205.read();
}

void gaussian::thread_grp_fu_180_ce() {
    grp_fu_180_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_180_p0() {
    if (esl_seteq<1,8,8>(ap_ST_st119_fsm_118, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_38_i1_fu_508_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st105_fsm_104, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_34_i1_fu_504_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st91_fsm_90, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_30_i9_fu_499_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st77_fsm_76, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_26_i8_fu_494_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st63_fsm_62, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_22_i7_fu_481_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st49_fsm_48, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_18_i6_fu_390_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st35_fsm_34, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_14_i5_fu_341_p1.read();
    } else if (esl_seteq<1,8,8>(ap_ST_st21_fsm_20, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_6_i3_fu_315_p1.read();
    } else {
        grp_fu_180_p0 = tmp_38_i1_fu_508_p1.read();
    }
}

void gaussian::thread_grp_fu_183_ce() {
    grp_fu_183_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_183_p0() {
    grp_fu_183_p0 = esl_zext<64,16>(reg_190.read());
}

void gaussian::thread_grp_fu_211_ce() {
    grp_fu_211_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_211_p0() {
    grp_fu_211_p0 = indvar1_i_reg_135.read();
}

void gaussian::thread_grp_fu_211_p1() {
    grp_fu_211_p1 = ap_const_lv11_2;
}

void gaussian::thread_grp_fu_217_ce() {
    grp_fu_217_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_217_p0() {
    grp_fu_217_p0 = indvar1_i_reg_135.read();
}

void gaussian::thread_grp_fu_217_p1() {
    grp_fu_217_p1 = ap_const_lv11_1;
}

void gaussian::thread_grp_fu_229_ce() {
    grp_fu_229_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_229_p0() {
    grp_fu_229_p0 = indvar_i_reg_147.read();
}

void gaussian::thread_grp_fu_229_p1() {
    grp_fu_229_p1 = ap_const_lv11_2;
}

void gaussian::thread_grp_fu_235_ce() {
    grp_fu_235_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_235_p0() {
    grp_fu_235_p0 = indvar_i_reg_147.read();
}

void gaussian::thread_grp_fu_235_p1() {
    grp_fu_235_p1 = ap_const_lv11_1;
}

void gaussian::thread_grp_fu_271_ce() {
    if (((esl_seteq<1,8,8>(ap_ST_st7_fsm_6, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(exitcond1_fu_241_p2.read(), ap_const_lv1_0)) || 
         esl_seteq<1,8,8>(ap_ST_st12_fsm_11, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st8_fsm_7, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st9_fsm_8, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st11_fsm_10, ap_CS_fsm.read()))) {
        grp_fu_271_ce = ap_const_logic_1;
    } else {
        grp_fu_271_ce = ap_const_logic_0;
    }
}

void gaussian::thread_grp_fu_271_p0() {
    grp_fu_271_p0 = esl_zext<23,22>(tmp_fu_247_p3.read());
}

void gaussian::thread_grp_fu_271_p1() {
    grp_fu_271_p1 = esl_zext<23,18>(tmp_1_fu_259_p3.read());
}

void gaussian::thread_grp_fu_284_ce() {
    grp_fu_284_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_284_p0() {
    grp_fu_284_p0 = p_addr_cast_fu_281_p1.read();
}

void gaussian::thread_grp_fu_284_p1() {
    grp_fu_284_p1 = esl_zext<24,11>(indvar_i_reg_147.read());
}

void gaussian::thread_grp_fu_293_ce() {
    grp_fu_293_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_293_p0() {
    grp_fu_293_p0 = p_addr_cast_fu_281_p1.read();
}

void gaussian::thread_grp_fu_293_p1() {
    grp_fu_293_p1 = esl_zext<24,11>(j_reg_538.read());
}

void gaussian::thread_grp_fu_328_ce() {
    grp_fu_328_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_328_p0() {
    grp_fu_328_p0 = p_addr_cast_reg_569.read();
}

void gaussian::thread_grp_fu_328_p1() {
    grp_fu_328_p1 = esl_zext<24,11>(tmp6_i_reg_533.read());
}

void gaussian::thread_grp_fu_368_ce() {
    grp_fu_368_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_368_p0() {
    grp_fu_368_p0 = esl_zext<23,22>(tmp_5_fu_346_p3.read());
}

void gaussian::thread_grp_fu_368_p1() {
    grp_fu_368_p1 = esl_zext<23,18>(tmp_6_fu_357_p3.read());
}

void gaussian::thread_grp_fu_377_ce() {
    grp_fu_377_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_377_p0() {
    grp_fu_377_p0 = esl_sext<24,23>(p_addr8_reg_655.read());
}

void gaussian::thread_grp_fu_377_p1() {
    grp_fu_377_p1 = tmp_4_i_trn_cast_reg_562.read();
}

void gaussian::thread_grp_fu_417_ce() {
    grp_fu_417_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_417_p0() {
    grp_fu_417_p0 = esl_zext<23,22>(tmp_s_fu_395_p3.read());
}

void gaussian::thread_grp_fu_417_p1() {
    grp_fu_417_p1 = esl_zext<23,18>(tmp_10_fu_406_p3.read());
}

void gaussian::thread_grp_fu_423_ce() {
    grp_fu_423_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_423_p0() {
    grp_fu_423_p0 = p_addr8_cast_reg_660.read();
}

void gaussian::thread_grp_fu_423_p1() {
    grp_fu_423_p1 = tmp_8_i_trn_cast_reg_576.read();
}

void gaussian::thread_grp_fu_427_ce() {
    grp_fu_427_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_427_p0() {
    grp_fu_427_p0 = p_addr8_cast_reg_660.read();
}

void gaussian::thread_grp_fu_427_p1() {
    grp_fu_427_p1 = tmp_12_i_trn_cast_reg_613.read();
}

void gaussian::thread_grp_fu_434_ce() {
    grp_fu_434_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_434_p0() {
    grp_fu_434_p0 = p_addr6_cast_fu_431_p1.read();
}

void gaussian::thread_grp_fu_434_p1() {
    grp_fu_434_p1 = tmp_4_i_trn_cast_reg_562.read();
}

void gaussian::thread_grp_fu_439_ce() {
    grp_fu_439_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_439_p0() {
    grp_fu_439_p0 = p_addr6_cast_fu_431_p1.read();
}

void gaussian::thread_grp_fu_439_p1() {
    grp_fu_439_p1 = tmp_8_i_trn_cast_reg_576.read();
}

void gaussian::thread_grp_fu_444_ce() {
    grp_fu_444_ce = ap_const_logic_1;
}

void gaussian::thread_grp_fu_444_p0() {
    grp_fu_444_p0 = p_addr6_cast_fu_431_p1.read();
}

void gaussian::thread_grp_fu_444_p1() {
    grp_fu_444_p1 = tmp_12_i_trn_cast_reg_613.read();
}

void gaussian::thread_in_r_address0() {
    if (esl_seteq<1,8,8>(ap_ST_st63_fsm_62, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_13_fu_489_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st62_fsm_61, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_11_fu_468_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st61_fsm_60, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_8_fu_452_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st47_fsm_46, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_7_fu_385_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st33_fsm_32, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_4_fu_336_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_2_fu_302_p1.read());
    } else {
        in_r_address0 =  (sc_lv<21>) (tmp_13_fu_489_p1.read());
    }
}

void gaussian::thread_in_r_address1() {
    if (esl_seteq<1,8,8>(ap_ST_st62_fsm_61, ap_CS_fsm.read())) {
        in_r_address1 =  (sc_lv<21>) (tmp_12_fu_476_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st61_fsm_60, ap_CS_fsm.read())) {
        in_r_address1 =  (sc_lv<21>) (tmp_9_fu_460_p1.read());
    } else if (esl_seteq<1,8,8>(ap_ST_st19_fsm_18, ap_CS_fsm.read())) {
        in_r_address1 =  (sc_lv<21>) (tmp_3_fu_310_p1.read());
    } else {
        in_r_address1 =  (sc_lv<21>) (tmp_12_fu_476_p1.read());
    }
}

void gaussian::thread_in_r_ce0() {
    if ((esl_seteq<1,8,8>(ap_ST_st62_fsm_61, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st63_fsm_62, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st33_fsm_32, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st47_fsm_46, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st61_fsm_60, ap_CS_fsm.read()))) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void gaussian::thread_in_r_ce1() {
    if ((esl_seteq<1,8,8>(ap_ST_st62_fsm_61, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || 
         esl_seteq<1,8,8>(ap_ST_st61_fsm_60, ap_CS_fsm.read()))) {
        in_r_ce1 = ap_const_logic_1;
    } else {
        in_r_ce1 = ap_const_logic_0;
    }
}

void gaussian::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<21>) (tmp_8_reg_729.read());
}

void gaussian::thread_out_r_ce0() {
    if (esl_seteq<1,8,8>(ap_ST_st158_fsm_157, ap_CS_fsm.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void gaussian::thread_out_r_d0() {
    out_r_d0 = tmp_14_reg_794.read();
}

void gaussian::thread_out_r_we0() {
    if ((esl_seteq<1,8,8>(ap_ST_st158_fsm_157, ap_CS_fsm.read()))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void gaussian::thread_p_addr6_cast_fu_431_p1() {
    p_addr6_cast_fu_431_p1 = esl_sext<24,23>(p_addr6_reg_692.read());
}

void gaussian::thread_p_addr8_cast_fu_374_p1() {
    p_addr8_cast_fu_374_p1 = esl_sext<24,23>(p_addr8_reg_655.read());
}

void gaussian::thread_p_addr_cast_fu_281_p1() {
    p_addr_cast_fu_281_p1 = esl_sext<24,23>(p_addr_reg_557.read());
}

void gaussian::thread_tmp_10_fu_406_p3() {
    tmp_10_fu_406_p3 = esl_concat<11,7>(tmp_i_12_reg_520.read(), ap_const_lv7_0);
}

void gaussian::thread_tmp_11_fu_468_p0() {
    tmp_11_fu_468_p0 = esl_sext<32,24>(p_addr7_reg_714.read());
}

void gaussian::thread_tmp_11_fu_468_p1() {
    tmp_11_fu_468_p1 = esl_zext<64,32>(tmp_11_fu_468_p0.read());
}

void gaussian::thread_tmp_12_fu_476_p0() {
    tmp_12_fu_476_p0 = esl_sext<32,24>(p_addr4_reg_719.read());
}

void gaussian::thread_tmp_12_fu_476_p1() {
    tmp_12_fu_476_p1 = esl_zext<64,32>(tmp_12_fu_476_p0.read());
}

void gaussian::thread_tmp_12_i_trn_cast_fu_325_p1() {
    tmp_12_i_trn_cast_fu_325_p1 = esl_zext<24,11>(tmp6_i_reg_533.read());
}

void gaussian::thread_tmp_13_fu_489_p0() {
    tmp_13_fu_489_p0 = esl_sext<32,24>(p_addr1_reg_724.read());
}

void gaussian::thread_tmp_13_fu_489_p1() {
    tmp_13_fu_489_p1 = esl_zext<64,32>(tmp_13_fu_489_p0.read());
}

void gaussian::thread_tmp_14_fu_512_p1() {
    tmp_14_fu_512_p1 = grp_fu_177_p1.read().range(16-1, 0);
}

void gaussian::thread_tmp_14_i5_fu_341_p1() {
    tmp_14_i5_fu_341_p1 = esl_zext<64,16>(reg_186.read());
}

void gaussian::thread_tmp_18_i6_fu_390_p1() {
    tmp_18_i6_fu_390_p1 = esl_zext<64,16>(reg_186.read());
}

void gaussian::thread_tmp_1_fu_259_p3() {
    tmp_1_fu_259_p3 = esl_concat<11,7>(indvar1_i_reg_135.read(), ap_const_lv7_0);
}

void gaussian::thread_tmp_22_i7_fu_481_p1() {
    tmp_22_i7_fu_481_p1 = esl_zext<64,16>(reg_186.read());
}

void gaussian::thread_tmp_26_i8_fu_494_p1() {
    tmp_26_i8_fu_494_p1 = esl_zext<64,16>(reg_190.read());
}

void gaussian::thread_tmp_2_fu_302_p0() {
    tmp_2_fu_302_p0 = esl_sext<32,24>(p_addr2_reg_583.read());
}

void gaussian::thread_tmp_2_fu_302_p1() {
    tmp_2_fu_302_p1 = esl_zext<64,32>(tmp_2_fu_302_p0.read());
}

void gaussian::thread_tmp_30_i9_fu_499_p1() {
    tmp_30_i9_fu_499_p1 = esl_zext<64,16>(reg_186.read());
}

void gaussian::thread_tmp_34_i1_fu_504_p1() {
    tmp_34_i1_fu_504_p1 = esl_zext<64,16>(in_load_7_reg_759.read());
}

void gaussian::thread_tmp_38_i1_fu_508_p1() {
    tmp_38_i1_fu_508_p1 = esl_zext<64,16>(in_load_8_reg_769.read());
}

void gaussian::thread_tmp_3_fu_310_p0() {
    tmp_3_fu_310_p0 = esl_sext<32,24>(p_addr3_reg_588.read());
}

void gaussian::thread_tmp_3_fu_310_p1() {
    tmp_3_fu_310_p1 = esl_zext<64,32>(tmp_3_fu_310_p0.read());
}

void gaussian::thread_tmp_4_fu_336_p0() {
    tmp_4_fu_336_p0 = esl_sext<32,24>(p_addr5_reg_625.read());
}

void gaussian::thread_tmp_4_fu_336_p1() {
    tmp_4_fu_336_p1 = esl_zext<64,32>(tmp_4_fu_336_p0.read());
}

void gaussian::thread_tmp_4_i_trn_cast_fu_277_p1() {
    tmp_4_i_trn_cast_fu_277_p1 = esl_zext<24,11>(indvar_i_reg_147.read());
}

void gaussian::thread_tmp_5_fu_346_p3() {
    tmp_5_fu_346_p3 = esl_concat<11,11>(i_reg_526.read(), ap_const_lv11_0);
}

void gaussian::thread_tmp_6_fu_357_p3() {
    tmp_6_fu_357_p3 = esl_concat<11,7>(i_reg_526.read(), ap_const_lv7_0);
}

void gaussian::thread_tmp_6_i3_fu_315_p1() {
    tmp_6_i3_fu_315_p1 = esl_zext<64,16>(reg_186.read());
}

void gaussian::thread_tmp_7_fu_385_p0() {
    tmp_7_fu_385_p0 = esl_sext<32,24>(p_addr9_reg_667.read());
}

void gaussian::thread_tmp_7_fu_385_p1() {
    tmp_7_fu_385_p1 = esl_zext<64,32>(tmp_7_fu_385_p0.read());
}

void gaussian::thread_tmp_8_fu_452_p0() {
    tmp_8_fu_452_p0 = esl_sext<32,24>(p_addr11_reg_704.read());
}

void gaussian::thread_tmp_8_fu_452_p1() {
    tmp_8_fu_452_p1 = esl_zext<64,32>(tmp_8_fu_452_p0.read());
}

void gaussian::thread_tmp_8_i_trn_cast_fu_290_p1() {
    tmp_8_i_trn_cast_fu_290_p1 = esl_zext<24,11>(j_reg_538.read());
}

void gaussian::thread_tmp_9_fu_460_p0() {
    tmp_9_fu_460_p0 = esl_sext<32,24>(p_addr10_reg_709.read());
}

void gaussian::thread_tmp_9_fu_460_p1() {
    tmp_9_fu_460_p1 = esl_zext<64,32>(tmp_9_fu_460_p0.read());
}

void gaussian::thread_tmp_fu_247_p3() {
    tmp_fu_247_p3 = esl_concat<11,11>(indvar1_i_reg_135.read(), ap_const_lv11_0);
}

void gaussian::thread_tmp_s_fu_395_p3() {
    tmp_s_fu_395_p3 = esl_concat<11,11>(tmp_i_12_reg_520.read(), ap_const_lv11_0);
}

void gaussian::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 3 : 
            if (!esl_seteq<1,1,1>(exitcond_reg_516.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st5_fsm_4;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 6 : 
            if (esl_seteq<1,1,1>(exitcond1_fu_241_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st8_fsm_7;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
            break;
        case 24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
            break;
        case 25 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
            break;
        case 26 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
            break;
        case 27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
            break;
        case 28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
            break;
        case 29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
            break;
        case 30 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
            break;
        case 31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
            break;
        case 33 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
            break;
        case 34 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
            break;
        case 35 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
            break;
        case 36 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
            break;
        case 37 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
            break;
        case 38 : 
            ap_NS_fsm = ap_ST_st40_fsm_39;
            break;
        case 39 : 
            ap_NS_fsm = ap_ST_st41_fsm_40;
            break;
        case 40 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
            break;
        case 41 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
            break;
        case 42 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
            break;
        case 43 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
            break;
        case 44 : 
            ap_NS_fsm = ap_ST_st46_fsm_45;
            break;
        case 45 : 
            ap_NS_fsm = ap_ST_st47_fsm_46;
            break;
        case 46 : 
            ap_NS_fsm = ap_ST_st48_fsm_47;
            break;
        case 47 : 
            ap_NS_fsm = ap_ST_st49_fsm_48;
            break;
        case 48 : 
            ap_NS_fsm = ap_ST_st50_fsm_49;
            break;
        case 49 : 
            ap_NS_fsm = ap_ST_st51_fsm_50;
            break;
        case 50 : 
            ap_NS_fsm = ap_ST_st52_fsm_51;
            break;
        case 51 : 
            ap_NS_fsm = ap_ST_st53_fsm_52;
            break;
        case 52 : 
            ap_NS_fsm = ap_ST_st54_fsm_53;
            break;
        case 53 : 
            ap_NS_fsm = ap_ST_st55_fsm_54;
            break;
        case 54 : 
            ap_NS_fsm = ap_ST_st56_fsm_55;
            break;
        case 55 : 
            ap_NS_fsm = ap_ST_st57_fsm_56;
            break;
        case 56 : 
            ap_NS_fsm = ap_ST_st58_fsm_57;
            break;
        case 57 : 
            ap_NS_fsm = ap_ST_st59_fsm_58;
            break;
        case 58 : 
            ap_NS_fsm = ap_ST_st60_fsm_59;
            break;
        case 59 : 
            ap_NS_fsm = ap_ST_st61_fsm_60;
            break;
        case 60 : 
            ap_NS_fsm = ap_ST_st62_fsm_61;
            break;
        case 61 : 
            ap_NS_fsm = ap_ST_st63_fsm_62;
            break;
        case 62 : 
            ap_NS_fsm = ap_ST_st64_fsm_63;
            break;
        case 63 : 
            ap_NS_fsm = ap_ST_st65_fsm_64;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st66_fsm_65;
            break;
        case 65 : 
            ap_NS_fsm = ap_ST_st67_fsm_66;
            break;
        case 66 : 
            ap_NS_fsm = ap_ST_st68_fsm_67;
            break;
        case 67 : 
            ap_NS_fsm = ap_ST_st69_fsm_68;
            break;
        case 68 : 
            ap_NS_fsm = ap_ST_st70_fsm_69;
            break;
        case 69 : 
            ap_NS_fsm = ap_ST_st71_fsm_70;
            break;
        case 70 : 
            ap_NS_fsm = ap_ST_st72_fsm_71;
            break;
        case 71 : 
            ap_NS_fsm = ap_ST_st73_fsm_72;
            break;
        case 72 : 
            ap_NS_fsm = ap_ST_st74_fsm_73;
            break;
        case 73 : 
            ap_NS_fsm = ap_ST_st75_fsm_74;
            break;
        case 74 : 
            ap_NS_fsm = ap_ST_st76_fsm_75;
            break;
        case 75 : 
            ap_NS_fsm = ap_ST_st77_fsm_76;
            break;
        case 76 : 
            ap_NS_fsm = ap_ST_st78_fsm_77;
            break;
        case 77 : 
            ap_NS_fsm = ap_ST_st79_fsm_78;
            break;
        case 78 : 
            ap_NS_fsm = ap_ST_st80_fsm_79;
            break;
        case 79 : 
            ap_NS_fsm = ap_ST_st81_fsm_80;
            break;
        case 80 : 
            ap_NS_fsm = ap_ST_st82_fsm_81;
            break;
        case 81 : 
            ap_NS_fsm = ap_ST_st83_fsm_82;
            break;
        case 82 : 
            ap_NS_fsm = ap_ST_st84_fsm_83;
            break;
        case 83 : 
            ap_NS_fsm = ap_ST_st85_fsm_84;
            break;
        case 84 : 
            ap_NS_fsm = ap_ST_st86_fsm_85;
            break;
        case 85 : 
            ap_NS_fsm = ap_ST_st87_fsm_86;
            break;
        case 86 : 
            ap_NS_fsm = ap_ST_st88_fsm_87;
            break;
        case 87 : 
            ap_NS_fsm = ap_ST_st89_fsm_88;
            break;
        case 88 : 
            ap_NS_fsm = ap_ST_st90_fsm_89;
            break;
        case 89 : 
            ap_NS_fsm = ap_ST_st91_fsm_90;
            break;
        case 90 : 
            ap_NS_fsm = ap_ST_st92_fsm_91;
            break;
        case 91 : 
            ap_NS_fsm = ap_ST_st93_fsm_92;
            break;
        case 92 : 
            ap_NS_fsm = ap_ST_st94_fsm_93;
            break;
        case 93 : 
            ap_NS_fsm = ap_ST_st95_fsm_94;
            break;
        case 94 : 
            ap_NS_fsm = ap_ST_st96_fsm_95;
            break;
        case 95 : 
            ap_NS_fsm = ap_ST_st97_fsm_96;
            break;
        case 96 : 
            ap_NS_fsm = ap_ST_st98_fsm_97;
            break;
        case 97 : 
            ap_NS_fsm = ap_ST_st99_fsm_98;
            break;
        case 98 : 
            ap_NS_fsm = ap_ST_st100_fsm_99;
            break;
        case 99 : 
            ap_NS_fsm = ap_ST_st101_fsm_100;
            break;
        case 100 : 
            ap_NS_fsm = ap_ST_st102_fsm_101;
            break;
        case 101 : 
            ap_NS_fsm = ap_ST_st103_fsm_102;
            break;
        case 102 : 
            ap_NS_fsm = ap_ST_st104_fsm_103;
            break;
        case 103 : 
            ap_NS_fsm = ap_ST_st105_fsm_104;
            break;
        case 104 : 
            ap_NS_fsm = ap_ST_st106_fsm_105;
            break;
        case 105 : 
            ap_NS_fsm = ap_ST_st107_fsm_106;
            break;
        case 106 : 
            ap_NS_fsm = ap_ST_st108_fsm_107;
            break;
        case 107 : 
            ap_NS_fsm = ap_ST_st109_fsm_108;
            break;
        case 108 : 
            ap_NS_fsm = ap_ST_st110_fsm_109;
            break;
        case 109 : 
            ap_NS_fsm = ap_ST_st111_fsm_110;
            break;
        case 110 : 
            ap_NS_fsm = ap_ST_st112_fsm_111;
            break;
        case 111 : 
            ap_NS_fsm = ap_ST_st113_fsm_112;
            break;
        case 112 : 
            ap_NS_fsm = ap_ST_st114_fsm_113;
            break;
        case 113 : 
            ap_NS_fsm = ap_ST_st115_fsm_114;
            break;
        case 114 : 
            ap_NS_fsm = ap_ST_st116_fsm_115;
            break;
        case 115 : 
            ap_NS_fsm = ap_ST_st117_fsm_116;
            break;
        case 116 : 
            ap_NS_fsm = ap_ST_st118_fsm_117;
            break;
        case 117 : 
            ap_NS_fsm = ap_ST_st119_fsm_118;
            break;
        case 118 : 
            ap_NS_fsm = ap_ST_st120_fsm_119;
            break;
        case 119 : 
            ap_NS_fsm = ap_ST_st121_fsm_120;
            break;
        case 120 : 
            ap_NS_fsm = ap_ST_st122_fsm_121;
            break;
        case 121 : 
            ap_NS_fsm = ap_ST_st123_fsm_122;
            break;
        case 122 : 
            ap_NS_fsm = ap_ST_st124_fsm_123;
            break;
        case 123 : 
            ap_NS_fsm = ap_ST_st125_fsm_124;
            break;
        case 124 : 
            ap_NS_fsm = ap_ST_st126_fsm_125;
            break;
        case 125 : 
            ap_NS_fsm = ap_ST_st127_fsm_126;
            break;
        case 126 : 
            ap_NS_fsm = ap_ST_st128_fsm_127;
            break;
        case 127 : 
            ap_NS_fsm = ap_ST_st129_fsm_128;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st130_fsm_129;
            break;
        case 129 : 
            ap_NS_fsm = ap_ST_st131_fsm_130;
            break;
        case 130 : 
            ap_NS_fsm = ap_ST_st132_fsm_131;
            break;
        case 131 : 
            ap_NS_fsm = ap_ST_st133_fsm_132;
            break;
        case 132 : 
            ap_NS_fsm = ap_ST_st134_fsm_133;
            break;
        case 133 : 
            ap_NS_fsm = ap_ST_st135_fsm_134;
            break;
        case 134 : 
            ap_NS_fsm = ap_ST_st136_fsm_135;
            break;
        case 135 : 
            ap_NS_fsm = ap_ST_st137_fsm_136;
            break;
        case 136 : 
            ap_NS_fsm = ap_ST_st138_fsm_137;
            break;
        case 137 : 
            ap_NS_fsm = ap_ST_st139_fsm_138;
            break;
        case 138 : 
            ap_NS_fsm = ap_ST_st140_fsm_139;
            break;
        case 139 : 
            ap_NS_fsm = ap_ST_st141_fsm_140;
            break;
        case 140 : 
            ap_NS_fsm = ap_ST_st142_fsm_141;
            break;
        case 141 : 
            ap_NS_fsm = ap_ST_st143_fsm_142;
            break;
        case 142 : 
            ap_NS_fsm = ap_ST_st144_fsm_143;
            break;
        case 143 : 
            ap_NS_fsm = ap_ST_st145_fsm_144;
            break;
        case 144 : 
            ap_NS_fsm = ap_ST_st146_fsm_145;
            break;
        case 145 : 
            ap_NS_fsm = ap_ST_st147_fsm_146;
            break;
        case 146 : 
            ap_NS_fsm = ap_ST_st148_fsm_147;
            break;
        case 147 : 
            ap_NS_fsm = ap_ST_st149_fsm_148;
            break;
        case 148 : 
            ap_NS_fsm = ap_ST_st150_fsm_149;
            break;
        case 149 : 
            ap_NS_fsm = ap_ST_st151_fsm_150;
            break;
        case 150 : 
            ap_NS_fsm = ap_ST_st152_fsm_151;
            break;
        case 151 : 
            ap_NS_fsm = ap_ST_st153_fsm_152;
            break;
        case 152 : 
            ap_NS_fsm = ap_ST_st154_fsm_153;
            break;
        case 153 : 
            ap_NS_fsm = ap_ST_st155_fsm_154;
            break;
        case 154 : 
            ap_NS_fsm = ap_ST_st156_fsm_155;
            break;
        case 155 : 
            ap_NS_fsm = ap_ST_st157_fsm_156;
            break;
        case 156 : 
            ap_NS_fsm = ap_ST_st158_fsm_157;
            break;
        case 157 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}
void gaussian::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_address0\" :  \"" << in_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_ce0\" :  \"" << in_r_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_q0\" :  \"" << in_r_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_address1\" :  \"" << in_r_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_ce1\" :  \"" << in_r_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_q1\" :  \"" << in_r_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_address0\" :  \"" << out_r_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_ce0\" :  \"" << out_r_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_we0\" :  \"" << out_r_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_d0\" :  \"" << out_r_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

