// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gaussian_sep (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_r_address1,
        in_r_ce1,
        in_r_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [20:0] in_r_address0;
output   in_r_ce0;
input  [15:0] in_r_q0;
output  [20:0] in_r_address1;
output   in_r_ce1;
input  [15:0] in_r_q1;
output  [20:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [15:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[20:0] in_r_address0;
reg in_r_ce0;
reg in_r_ce1;
reg out_r_ce0;
reg out_r_we0;
reg   [5:0] ap_CS_fsm = 6'b000000;
reg   [20:0] tmp_address0;
reg    tmp_ce0;
reg    tmp_we0;
wire   [31:0] tmp_d0;
wire   [31:0] tmp_q0;
wire   [20:0] tmp_address1;
reg    tmp_ce1;
wire   [31:0] tmp_q1;
reg   [15:0] reg_196;
wire   [31:0] grp_fu_190_p1;
reg   [31:0] reg_200;
wire   [31:0] grp_fu_175_p2;
reg   [31:0] reg_205;
wire   [31:0] grp_fu_180_p2;
reg   [31:0] reg_211;
wire   [31:0] grp_fu_171_p2;
reg   [31:0] reg_216;
wire   [10:0] tmp_1_1_fu_228_p2;
reg   [10:0] tmp_1_1_reg_542;
wire   [10:0] i_fu_234_p2;
reg   [10:0] i_reg_548;
wire   [10:0] j_2_fu_252_p2;
reg   [10:0] j_2_reg_561;
wire   [0:0] exitcond2_fu_246_p2;
wire   [63:0] tmp_16_fu_353_p1;
reg   [63:0] tmp_16_reg_571;
wire   [23:0] p_addr1_fu_390_p2;
reg   [23:0] p_addr1_reg_581;
reg   [15:0] in_load_1_reg_586;
wire   [63:0] tmp_6_fu_404_p1;
wire   [31:0] grp_fu_193_p1;
reg   [31:0] tmp_s_reg_606;
wire   [63:0] tmp_12_fu_413_p1;
wire   [10:0] i_2_fu_424_p2;
reg   [10:0] i_2_reg_619;
wire   [10:0] j_1_fu_436_p2;
reg   [10:0] j_1_reg_624;
wire   [0:0] exitcond3_fu_442_p2;
wire   [63:0] tmp_29_fu_515_p1;
reg   [63:0] tmp_29_reg_637;
wire   [23:0] tmp_addr4_fu_524_p2;
reg   [23:0] tmp_addr4_reg_647;
wire   [15:0] tmp_1_2_fu_538_p1;
reg   [15:0] tmp_1_2_reg_662;
reg   [10:0] indvar3_reg_124;
reg   [10:0] j_reg_136;
wire   [0:0] exitcond1_fu_240_p2;
reg   [10:0] i_1_reg_147;
reg   [10:0] indvar_reg_159;
wire   [0:0] exitcond_fu_418_p2;
wire   [63:0] tmp_3_fu_306_p1;
wire   [63:0] tmp_25_fu_399_p1;
wire   [63:0] tmp_28_fu_496_p1;
wire   [63:0] tmp_30_fu_533_p1;
reg   [31:0] grp_fu_171_p0;
reg   [31:0] grp_fu_171_p1;
reg   [31:0] grp_fu_175_p0;
wire   [31:0] grp_fu_175_p1;
reg   [31:0] grp_fu_180_p0;
wire   [31:0] grp_fu_180_p1;
wire   [31:0] grp_fu_187_p0;
reg   [63:0] grp_fu_190_p0;
wire   [63:0] grp_fu_193_p0;
wire   [21:0] tmp_1_fu_262_p3;
wire   [17:0] tmp_2_fu_274_p3;
wire   [22:0] p_shl_cast_fu_270_p1;
wire   [22:0] p_shl1_cast_fu_282_p1;
wire   [22:0] p_addr6_fu_286_p2;
wire   [23:0] p_addr7_fu_296_p0;
wire   [23:0] tmp_5_trn5_cast_fu_258_p1;
wire   [23:0] p_addr7_fu_296_p2;
wire   [31:0] tmp_3_fu_306_p0;
wire   [21:0] tmp_4_fu_311_p3;
wire   [17:0] tmp_5_fu_322_p3;
wire   [22:0] p_shl2_cast_fu_318_p1;
wire   [22:0] p_shl3_cast_fu_329_p1;
wire   [22:0] p_addr3_fu_333_p2;
wire   [23:0] p_addr4_fu_343_p0;
wire   [23:0] p_addr4_fu_343_p2;
wire   [31:0] tmp_16_fu_353_p0;
wire   [21:0] tmp_18_fu_358_p3;
wire   [17:0] tmp_21_fu_369_p3;
wire   [22:0] p_shl4_cast_fu_365_p1;
wire   [22:0] p_shl5_cast_fu_376_p1;
wire   [22:0] p_addr_fu_380_p2;
wire   [23:0] p_addr1_fu_390_p0;
wire   [31:0] tmp_25_fu_399_p0;
wire   [21:0] tmp_26_fu_452_p3;
wire   [17:0] tmp_27_fu_464_p3;
wire   [22:0] p_shl6_cast_fu_460_p1;
wire   [22:0] p_shl7_cast_fu_472_p1;
wire   [22:0] tmp_addr1_fu_476_p2;
wire   [23:0] tmp_addr2_fu_486_p0;
wire   [23:0] tmp_addr1_cast_fu_482_p1;
wire   [23:0] tmp_16_trn_cast_fu_448_p1;
wire   [23:0] tmp_addr2_fu_486_p2;
wire   [31:0] tmp_28_fu_496_p0;
wire   [23:0] tmp_addr3_fu_505_p0;
wire   [23:0] tmp_18_trn_cast_fu_501_p1;
wire   [23:0] tmp_addr3_fu_505_p2;
wire   [31:0] tmp_29_fu_515_p0;
wire   [10:0] tmp8_fu_430_p2;
wire   [23:0] tmp_addr4_fu_524_p0;
wire   [23:0] tmp_21_trn_cast_fu_520_p1;
wire   [31:0] tmp_30_fu_533_p0;
wire   [63:0] grp_fu_187_p1;
wire    grp_fu_171_ce;
wire    grp_fu_175_ce;
wire    grp_fu_180_ce;
wire    grp_fu_187_ce;
wire    grp_fu_190_ce;
wire    grp_fu_193_ce;
reg   [5:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b000000;
parameter    ap_ST_st2_fsm_1 = 6'b1;
parameter    ap_ST_st3_fsm_2 = 6'b10;
parameter    ap_ST_st4_fsm_3 = 6'b11;
parameter    ap_ST_st5_fsm_4 = 6'b100;
parameter    ap_ST_st6_fsm_5 = 6'b101;
parameter    ap_ST_st7_fsm_6 = 6'b110;
parameter    ap_ST_st8_fsm_7 = 6'b111;
parameter    ap_ST_st9_fsm_8 = 6'b1000;
parameter    ap_ST_st10_fsm_9 = 6'b1001;
parameter    ap_ST_st11_fsm_10 = 6'b1010;
parameter    ap_ST_st12_fsm_11 = 6'b1011;
parameter    ap_ST_st13_fsm_12 = 6'b1100;
parameter    ap_ST_st14_fsm_13 = 6'b1101;
parameter    ap_ST_st15_fsm_14 = 6'b1110;
parameter    ap_ST_st16_fsm_15 = 6'b1111;
parameter    ap_ST_st17_fsm_16 = 6'b10000;
parameter    ap_ST_st18_fsm_17 = 6'b10001;
parameter    ap_ST_st19_fsm_18 = 6'b10010;
parameter    ap_ST_st20_fsm_19 = 6'b10011;
parameter    ap_ST_st21_fsm_20 = 6'b10100;
parameter    ap_ST_st22_fsm_21 = 6'b10101;
parameter    ap_ST_st23_fsm_22 = 6'b10110;
parameter    ap_ST_st24_fsm_23 = 6'b10111;
parameter    ap_ST_st25_fsm_24 = 6'b11000;
parameter    ap_ST_st26_fsm_25 = 6'b11001;
parameter    ap_ST_st27_fsm_26 = 6'b11010;
parameter    ap_ST_st28_fsm_27 = 6'b11011;
parameter    ap_ST_st29_fsm_28 = 6'b11100;
parameter    ap_ST_st30_fsm_29 = 6'b11101;
parameter    ap_ST_st31_fsm_30 = 6'b11110;
parameter    ap_ST_st32_fsm_31 = 6'b11111;
parameter    ap_ST_st33_fsm_32 = 6'b100000;
parameter    ap_ST_st34_fsm_33 = 6'b100001;
parameter    ap_ST_st35_fsm_34 = 6'b100010;
parameter    ap_ST_st36_fsm_35 = 6'b100011;
parameter    ap_ST_st37_fsm_36 = 6'b100100;
parameter    ap_ST_st38_fsm_37 = 6'b100101;
parameter    ap_ST_st39_fsm_38 = 6'b100110;
parameter    ap_ST_st40_fsm_39 = 6'b100111;
parameter    ap_ST_st41_fsm_40 = 6'b101000;
parameter    ap_ST_st42_fsm_41 = 6'b101001;
parameter    ap_ST_st43_fsm_42 = 6'b101010;
parameter    ap_ST_st44_fsm_43 = 6'b101011;
parameter    ap_ST_st45_fsm_44 = 6'b101100;
parameter    ap_ST_st46_fsm_45 = 6'b101101;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3E7C8F32 = 32'b111110011111001000111100110010;
parameter    ap_const_lv32_3F1B5159 = 32'b111111000110110101000101011001;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_436 = 11'b10000110110;
parameter    ap_const_lv11_780 = 11'b11110000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv11_438 = 11'b10000111000;
parameter    ap_const_lv11_77E = 11'b11101111110;
parameter    ap_true = 1'b1;


gaussian_sep_tmp #(
    .DataWidth( 32 ),
    .AddressRange( 2073600 ),
    .AddressWidth( 21 ))
tmp_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( tmp_address0 ),
    .ce0( tmp_ce0 ),
    .we0( tmp_we0 ),
    .d0( tmp_d0 ),
    .q0( tmp_q0 ),
    .address1( tmp_address1 ),
    .ce1( tmp_ce1 ),
    .q1( tmp_q1 )
);

gaussian_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fadd_32ns_32ns_32_5_full_dsp_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_171_p0 ),
    .din1( grp_fu_171_p1 ),
    .ce( grp_fu_171_ce ),
    .dout( grp_fu_171_p2 )
);

gaussian_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 2 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_4_max_dsp_U2(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_175_p0 ),
    .din1( grp_fu_175_p1 ),
    .ce( grp_fu_175_ce ),
    .dout( grp_fu_175_p2 )
);

gaussian_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 3 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_4_max_dsp_U3(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_180_p0 ),
    .din1( grp_fu_180_p1 ),
    .ce( grp_fu_180_ce ),
    .dout( grp_fu_180_p2 )
);

gaussian_fptoui_32ns_64_4 #(
    .ID( 4 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
gaussian_fptoui_32ns_64_4_U4(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_187_p0 ),
    .ce( grp_fu_187_ce ),
    .dout( grp_fu_187_p1 )
);

gaussian_sitofp_64ns_32_6 #(
    .ID( 5 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_6_U5(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_190_p0 ),
    .ce( grp_fu_190_ce ),
    .dout( grp_fu_190_p1 )
);

gaussian_sitofp_64ns_32_6 #(
    .ID( 6 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_6_U6(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_193_p0 ),
    .ce( grp_fu_193_ce ),
    .dout( grp_fu_193_p1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st27_fsm_26 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond3_fu_442_p2))) begin
        i_1_reg_147 <= i_2_reg_619;
    end else if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_240_p2))) begin
        i_1_reg_147 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & ~(exitcond2_fu_246_p2 == ap_const_lv1_0))) begin
        indvar3_reg_124 <= i_reg_548;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        indvar3_reg_124 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond_fu_418_p2))) begin
        indvar_reg_159 <= ap_const_lv11_0;
    end else if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        indvar_reg_159 <= j_1_reg_624;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_240_p2))) begin
        j_reg_136 <= ap_const_lv11_0;
    end else if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        j_reg_136 <= j_2_reg_561;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        i_2_reg_619 <= i_2_fu_424_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_reg_548 <= i_fu_234_p2;
        tmp_1_1_reg_542 <= tmp_1_1_fu_228_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        in_load_1_reg_586 <= in_r_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        j_1_reg_624 <= j_1_fu_436_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        j_2_reg_561 <= j_2_fu_252_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (exitcond2_fu_246_p2 == ap_const_lv1_0))) begin
        p_addr1_reg_581 <= p_addr1_fu_390_p2;
        tmp_16_reg_571[0] <= tmp_16_fu_353_p1[0];
tmp_16_reg_571[1] <= tmp_16_fu_353_p1[1];
tmp_16_reg_571[2] <= tmp_16_fu_353_p1[2];
tmp_16_reg_571[3] <= tmp_16_fu_353_p1[3];
tmp_16_reg_571[4] <= tmp_16_fu_353_p1[4];
tmp_16_reg_571[5] <= tmp_16_fu_353_p1[5];
tmp_16_reg_571[6] <= tmp_16_fu_353_p1[6];
tmp_16_reg_571[7] <= tmp_16_fu_353_p1[7];
tmp_16_reg_571[8] <= tmp_16_fu_353_p1[8];
tmp_16_reg_571[9] <= tmp_16_fu_353_p1[9];
tmp_16_reg_571[10] <= tmp_16_fu_353_p1[10];
tmp_16_reg_571[11] <= tmp_16_fu_353_p1[11];
tmp_16_reg_571[12] <= tmp_16_fu_353_p1[12];
tmp_16_reg_571[13] <= tmp_16_fu_353_p1[13];
tmp_16_reg_571[14] <= tmp_16_fu_353_p1[14];
tmp_16_reg_571[15] <= tmp_16_fu_353_p1[15];
tmp_16_reg_571[16] <= tmp_16_fu_353_p1[16];
tmp_16_reg_571[17] <= tmp_16_fu_353_p1[17];
tmp_16_reg_571[18] <= tmp_16_fu_353_p1[18];
tmp_16_reg_571[19] <= tmp_16_fu_353_p1[19];
tmp_16_reg_571[20] <= tmp_16_fu_353_p1[20];
tmp_16_reg_571[21] <= tmp_16_fu_353_p1[21];
tmp_16_reg_571[22] <= tmp_16_fu_353_p1[22];
tmp_16_reg_571[23] <= tmp_16_fu_353_p1[23];
tmp_16_reg_571[24] <= tmp_16_fu_353_p1[24];
tmp_16_reg_571[25] <= tmp_16_fu_353_p1[25];
tmp_16_reg_571[26] <= tmp_16_fu_353_p1[26];
tmp_16_reg_571[27] <= tmp_16_fu_353_p1[27];
tmp_16_reg_571[28] <= tmp_16_fu_353_p1[28];
tmp_16_reg_571[29] <= tmp_16_fu_353_p1[29];
tmp_16_reg_571[30] <= tmp_16_fu_353_p1[30];
tmp_16_reg_571[31] <= tmp_16_fu_353_p1[31];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) | (ap_ST_st5_fsm_4 == ap_CS_fsm))) begin
        reg_196 <= in_r_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm))) begin
        reg_200 <= grp_fu_190_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st31_fsm_30 == ap_CS_fsm) | (ap_ST_st36_fsm_35 == ap_CS_fsm))) begin
        reg_205 <= grp_fu_175_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st31_fsm_30 == ap_CS_fsm))) begin
        reg_211 <= grp_fu_180_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st36_fsm_35 == ap_CS_fsm) | (ap_ST_st24_fsm_23 == ap_CS_fsm) | (ap_ST_st41_fsm_40 == ap_CS_fsm))) begin
        reg_216 <= grp_fu_171_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st45_fsm_44 == ap_CS_fsm)) begin
        tmp_1_2_reg_662 <= tmp_1_2_fu_538_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st27_fsm_26 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_442_p2))) begin
        tmp_29_reg_637[0] <= tmp_29_fu_515_p1[0];
tmp_29_reg_637[1] <= tmp_29_fu_515_p1[1];
tmp_29_reg_637[2] <= tmp_29_fu_515_p1[2];
tmp_29_reg_637[3] <= tmp_29_fu_515_p1[3];
tmp_29_reg_637[4] <= tmp_29_fu_515_p1[4];
tmp_29_reg_637[5] <= tmp_29_fu_515_p1[5];
tmp_29_reg_637[6] <= tmp_29_fu_515_p1[6];
tmp_29_reg_637[7] <= tmp_29_fu_515_p1[7];
tmp_29_reg_637[8] <= tmp_29_fu_515_p1[8];
tmp_29_reg_637[9] <= tmp_29_fu_515_p1[9];
tmp_29_reg_637[10] <= tmp_29_fu_515_p1[10];
tmp_29_reg_637[11] <= tmp_29_fu_515_p1[11];
tmp_29_reg_637[12] <= tmp_29_fu_515_p1[12];
tmp_29_reg_637[13] <= tmp_29_fu_515_p1[13];
tmp_29_reg_637[14] <= tmp_29_fu_515_p1[14];
tmp_29_reg_637[15] <= tmp_29_fu_515_p1[15];
tmp_29_reg_637[16] <= tmp_29_fu_515_p1[16];
tmp_29_reg_637[17] <= tmp_29_fu_515_p1[17];
tmp_29_reg_637[18] <= tmp_29_fu_515_p1[18];
tmp_29_reg_637[19] <= tmp_29_fu_515_p1[19];
tmp_29_reg_637[20] <= tmp_29_fu_515_p1[20];
tmp_29_reg_637[21] <= tmp_29_fu_515_p1[21];
tmp_29_reg_637[22] <= tmp_29_fu_515_p1[22];
tmp_29_reg_637[23] <= tmp_29_fu_515_p1[23];
tmp_29_reg_637[24] <= tmp_29_fu_515_p1[24];
tmp_29_reg_637[25] <= tmp_29_fu_515_p1[25];
tmp_29_reg_637[26] <= tmp_29_fu_515_p1[26];
tmp_29_reg_637[27] <= tmp_29_fu_515_p1[27];
tmp_29_reg_637[28] <= tmp_29_fu_515_p1[28];
tmp_29_reg_637[29] <= tmp_29_fu_515_p1[29];
tmp_29_reg_637[30] <= tmp_29_fu_515_p1[30];
tmp_29_reg_637[31] <= tmp_29_fu_515_p1[31];
        tmp_addr4_reg_647 <= tmp_addr4_fu_524_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        tmp_s_reg_606 <= grp_fu_193_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond_fu_418_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st26_fsm_25 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_418_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond_fu_418_p2)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond_fu_418_p2))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// grp_fu_171_p0 assign process. ///
always @ (ap_CS_fsm or reg_205 or reg_216)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm))) begin
        grp_fu_171_p0 = reg_216;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) | (ap_ST_st32_fsm_31 == ap_CS_fsm))) begin
        grp_fu_171_p0 = reg_205;
    end else begin
        grp_fu_171_p0 = reg_216;
    end
end

/// grp_fu_171_p1 assign process. ///
always @ (ap_CS_fsm or reg_205 or reg_211)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm))) begin
        grp_fu_171_p1 = reg_205;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) | (ap_ST_st32_fsm_31 == ap_CS_fsm))) begin
        grp_fu_171_p1 = reg_211;
    end else begin
        grp_fu_171_p1 = reg_211;
    end
end

/// grp_fu_175_p0 assign process. ///
always @ (ap_CS_fsm or tmp_q0 or reg_200)
begin
    if (((ap_ST_st28_fsm_27 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm))) begin
        grp_fu_175_p0 = tmp_q0;
    end else if (((ap_ST_st11_fsm_10 == ap_CS_fsm) | (ap_ST_st16_fsm_15 == ap_CS_fsm))) begin
        grp_fu_175_p0 = reg_200;
    end else begin
        grp_fu_175_p0 = reg_200;
    end
end

/// grp_fu_180_p0 assign process. ///
always @ (ap_CS_fsm or tmp_q1 or tmp_s_reg_606)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_q1;
    end else if ((ap_ST_st11_fsm_10 == ap_CS_fsm)) begin
        grp_fu_180_p0 = tmp_s_reg_606;
    end else begin
        grp_fu_180_p0 = tmp_s_reg_606;
    end
end

/// grp_fu_190_p0 assign process. ///
always @ (ap_CS_fsm or tmp_6_fu_404_p1 or tmp_12_fu_413_p1)
begin
    if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        grp_fu_190_p0 = tmp_12_fu_413_p1;
    end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        grp_fu_190_p0 = tmp_6_fu_404_p1;
    end else begin
        grp_fu_190_p0 = tmp_12_fu_413_p1;
    end
end

/// in_r_address0 assign process. ///
always @ (ap_CS_fsm or tmp_3_fu_306_p1 or tmp_25_fu_399_p1)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        in_r_address0 = tmp_25_fu_399_p1;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        in_r_address0 = tmp_3_fu_306_p1;
    end else begin
        in_r_address0 = tmp_25_fu_399_p1;
    end
end

/// in_r_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond2_fu_246_p2)
begin
    if (((ap_ST_st4_fsm_3 == ap_CS_fsm) | ((ap_ST_st3_fsm_2 == ap_CS_fsm) & (exitcond2_fu_246_p2 == ap_const_lv1_0)))) begin
        in_r_ce0 = ap_const_logic_1;
    end else begin
        in_r_ce0 = ap_const_logic_0;
    end
end

/// in_r_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond2_fu_246_p2)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) & (exitcond2_fu_246_p2 == ap_const_lv1_0))) begin
        in_r_ce1 = ap_const_logic_1;
    end else begin
        in_r_ce1 = ap_const_logic_0;
    end
end

/// out_r_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        out_r_ce0 = ap_const_logic_1;
    end else begin
        out_r_ce0 = ap_const_logic_0;
    end
end

/// out_r_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st46_fsm_45 == ap_CS_fsm)) begin
        out_r_we0 = ap_const_logic_1;
    end else begin
        out_r_we0 = ap_const_logic_0;
    end
end

/// tmp_address0 assign process. ///
always @ (ap_CS_fsm or tmp_16_reg_571 or tmp_28_fu_496_p1 or tmp_30_fu_533_p1)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        tmp_address0 = tmp_16_reg_571;
    end else if ((ap_ST_st32_fsm_31 == ap_CS_fsm)) begin
        tmp_address0 = tmp_30_fu_533_p1;
    end else if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        tmp_address0 = tmp_28_fu_496_p1;
    end else begin
        tmp_address0 = tmp_16_reg_571;
    end
end

/// tmp_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_442_p2)
begin
    if ((((ap_ST_st27_fsm_26 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_442_p2)) | (ap_ST_st32_fsm_31 == ap_CS_fsm) | (ap_ST_st25_fsm_24 == ap_CS_fsm))) begin
        tmp_ce0 = ap_const_logic_1;
    end else begin
        tmp_ce0 = ap_const_logic_0;
    end
end

/// tmp_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond3_fu_442_p2)
begin
    if (((ap_ST_st27_fsm_26 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond3_fu_442_p2))) begin
        tmp_ce1 = ap_const_logic_1;
    end else begin
        tmp_ce1 = ap_const_logic_0;
    end
end

/// tmp_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        tmp_we0 = ap_const_logic_1;
    end else begin
        tmp_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond2_fu_246_p2 or exitcond3_fu_442_p2 or exitcond1_fu_240_p2 or exitcond_fu_418_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(ap_const_lv1_0 == exitcond1_fu_240_p2)) begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            if ((exitcond2_fu_246_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
        ap_ST_st5_fsm_4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
        ap_ST_st17_fsm_16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        ap_ST_st18_fsm_17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
        ap_ST_st19_fsm_18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
        ap_ST_st20_fsm_19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
        ap_ST_st21_fsm_20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
        ap_ST_st22_fsm_21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
        ap_ST_st23_fsm_22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
        ap_ST_st24_fsm_23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
        ap_ST_st26_fsm_25 : 
            if (~(ap_const_lv1_0 == exitcond_fu_418_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end
        ap_ST_st27_fsm_26 : 
            if ((ap_const_lv1_0 == exitcond3_fu_442_p2)) begin
                ap_NS_fsm = ap_ST_st28_fsm_27;
            end else begin
                ap_NS_fsm = ap_ST_st26_fsm_25;
            end
        ap_ST_st28_fsm_27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
        ap_ST_st29_fsm_28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
        ap_ST_st30_fsm_29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
        ap_ST_st31_fsm_30 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
        ap_ST_st32_fsm_31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
        ap_ST_st33_fsm_32 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
        ap_ST_st34_fsm_33 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
        ap_ST_st35_fsm_34 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
        ap_ST_st36_fsm_35 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
        ap_ST_st37_fsm_36 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
        ap_ST_st38_fsm_37 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
        ap_ST_st39_fsm_38 : 
            ap_NS_fsm = ap_ST_st40_fsm_39;
        ap_ST_st40_fsm_39 : 
            ap_NS_fsm = ap_ST_st41_fsm_40;
        ap_ST_st41_fsm_40 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
        ap_ST_st42_fsm_41 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
        ap_ST_st43_fsm_42 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
        ap_ST_st44_fsm_43 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
        ap_ST_st45_fsm_44 : 
            ap_NS_fsm = ap_ST_st46_fsm_45;
        ap_ST_st46_fsm_45 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign exitcond1_fu_240_p2 = (indvar3_reg_124 == ap_const_lv11_436? 1'b1: 1'b0);
assign exitcond2_fu_246_p2 = (j_reg_136 == ap_const_lv11_780? 1'b1: 1'b0);
assign exitcond3_fu_442_p2 = (indvar_reg_159 == ap_const_lv11_77E? 1'b1: 1'b0);
assign exitcond_fu_418_p2 = (i_1_reg_147 == ap_const_lv11_438? 1'b1: 1'b0);
assign grp_fu_171_ce = ap_const_logic_1;
assign grp_fu_175_ce = ap_const_logic_1;
assign grp_fu_175_p1 = ap_const_lv32_3E7C8F32;
assign grp_fu_180_ce = ap_const_logic_1;
assign grp_fu_180_p1 = ap_const_lv32_3F1B5159;
assign grp_fu_187_ce = ap_const_logic_1;
assign grp_fu_187_p0 = reg_216;
assign grp_fu_190_ce = ap_const_logic_1;
assign grp_fu_193_ce = ap_const_logic_1;
assign grp_fu_193_p0 = $unsigned(in_load_1_reg_586);
assign i_2_fu_424_p2 = (i_1_reg_147 + ap_const_lv11_1);
assign i_fu_234_p2 = (indvar3_reg_124 + ap_const_lv11_1);
assign in_r_address1 = tmp_16_fu_353_p1;
assign j_1_fu_436_p2 = (indvar_reg_159 + ap_const_lv11_1);
assign j_2_fu_252_p2 = (j_reg_136 + ap_const_lv11_1);
assign out_r_address0 = tmp_29_reg_637;
assign out_r_d0 = tmp_1_2_reg_662;
assign p_addr1_fu_390_p0 = $signed(p_addr_fu_380_p2);
assign p_addr1_fu_390_p2 = (p_addr1_fu_390_p0 + tmp_5_trn5_cast_fu_258_p1);
assign p_addr3_fu_333_p2 = (p_shl2_cast_fu_318_p1 - p_shl3_cast_fu_329_p1);
assign p_addr4_fu_343_p0 = $signed(p_addr3_fu_333_p2);
assign p_addr4_fu_343_p2 = (p_addr4_fu_343_p0 + tmp_5_trn5_cast_fu_258_p1);
assign p_addr6_fu_286_p2 = (p_shl_cast_fu_270_p1 - p_shl1_cast_fu_282_p1);
assign p_addr7_fu_296_p0 = $signed(p_addr6_fu_286_p2);
assign p_addr7_fu_296_p2 = (p_addr7_fu_296_p0 + tmp_5_trn5_cast_fu_258_p1);
assign p_addr_fu_380_p2 = (p_shl4_cast_fu_365_p1 - p_shl5_cast_fu_376_p1);
assign p_shl1_cast_fu_282_p1 = $unsigned(tmp_2_fu_274_p3);
assign p_shl2_cast_fu_318_p1 = $unsigned(tmp_4_fu_311_p3);
assign p_shl3_cast_fu_329_p1 = $unsigned(tmp_5_fu_322_p3);
assign p_shl4_cast_fu_365_p1 = $unsigned(tmp_18_fu_358_p3);
assign p_shl5_cast_fu_376_p1 = $unsigned(tmp_21_fu_369_p3);
assign p_shl6_cast_fu_460_p1 = $unsigned(tmp_26_fu_452_p3);
assign p_shl7_cast_fu_472_p1 = $unsigned(tmp_27_fu_464_p3);
assign p_shl_cast_fu_270_p1 = $unsigned(tmp_1_fu_262_p3);
assign tmp8_fu_430_p2 = (indvar_reg_159 + ap_const_lv11_2);
assign tmp_12_fu_413_p1 = $unsigned(reg_196);
assign tmp_16_fu_353_p0 = $signed(p_addr4_fu_343_p2);
assign tmp_16_fu_353_p1 = $unsigned(tmp_16_fu_353_p0);
assign tmp_16_trn_cast_fu_448_p1 = $unsigned(indvar_reg_159);
assign tmp_18_fu_358_p3 = {{tmp_1_1_reg_542}, {ap_const_lv11_0}};
assign tmp_18_trn_cast_fu_501_p1 = $unsigned(j_1_fu_436_p2);
assign tmp_1_1_fu_228_p2 = (indvar3_reg_124 + ap_const_lv11_2);
assign tmp_1_2_fu_538_p1 = grp_fu_187_p1[15:0];
assign tmp_1_fu_262_p3 = {{indvar3_reg_124}, {ap_const_lv11_0}};
assign tmp_21_fu_369_p3 = {{tmp_1_1_reg_542}, {ap_const_lv7_0}};
assign tmp_21_trn_cast_fu_520_p1 = $unsigned(tmp8_fu_430_p2);
assign tmp_25_fu_399_p0 = $signed(p_addr1_reg_581);
assign tmp_25_fu_399_p1 = $unsigned(tmp_25_fu_399_p0);
assign tmp_26_fu_452_p3 = {{i_1_reg_147}, {ap_const_lv11_0}};
assign tmp_27_fu_464_p3 = {{i_1_reg_147}, {ap_const_lv7_0}};
assign tmp_28_fu_496_p0 = $signed(tmp_addr2_fu_486_p2);
assign tmp_28_fu_496_p1 = $unsigned(tmp_28_fu_496_p0);
assign tmp_29_fu_515_p0 = $signed(tmp_addr3_fu_505_p2);
assign tmp_29_fu_515_p1 = $unsigned(tmp_29_fu_515_p0);
assign tmp_2_fu_274_p3 = {{indvar3_reg_124}, {ap_const_lv7_0}};
assign tmp_30_fu_533_p0 = $signed(tmp_addr4_reg_647);
assign tmp_30_fu_533_p1 = $unsigned(tmp_30_fu_533_p0);
assign tmp_3_fu_306_p0 = $signed(p_addr7_fu_296_p2);
assign tmp_3_fu_306_p1 = $unsigned(tmp_3_fu_306_p0);
assign tmp_4_fu_311_p3 = {{i_reg_548}, {ap_const_lv11_0}};
assign tmp_5_fu_322_p3 = {{i_reg_548}, {ap_const_lv7_0}};
assign tmp_5_trn5_cast_fu_258_p1 = $unsigned(j_reg_136);
assign tmp_6_fu_404_p1 = $unsigned(reg_196);
assign tmp_addr1_cast_fu_482_p1 = $signed(tmp_addr1_fu_476_p2);
assign tmp_addr1_fu_476_p2 = (p_shl6_cast_fu_460_p1 - p_shl7_cast_fu_472_p1);
assign tmp_addr2_fu_486_p0 = tmp_addr1_cast_fu_482_p1;
assign tmp_addr2_fu_486_p2 = (tmp_addr2_fu_486_p0 + tmp_16_trn_cast_fu_448_p1);
assign tmp_addr3_fu_505_p0 = tmp_addr1_cast_fu_482_p1;
assign tmp_addr3_fu_505_p2 = (tmp_addr3_fu_505_p0 + tmp_18_trn_cast_fu_501_p1);
assign tmp_addr4_fu_524_p0 = tmp_addr1_cast_fu_482_p1;
assign tmp_addr4_fu_524_p2 = (tmp_addr4_fu_524_p0 + tmp_21_trn_cast_fu_520_p1);
assign tmp_address1 = tmp_29_fu_515_p1;
assign tmp_d0 = reg_216;
always @ (posedge ap_clk)
begin
    tmp_16_reg_571[63:32] <= 32'b00000000000000000000000000000000;
    tmp_29_reg_637[63:32] <= 32'b00000000000000000000000000000000;
end



endmodule //gaussian_sep

