// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module gaussian_scalarized (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_r_address0,
        in_r_ce0,
        in_r_q0,
        in_r_address1,
        in_r_ce1,
        in_r_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0
);

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [20:0] in_r_address0;
output   in_r_ce0;
input  [15:0] in_r_q0;
output  [20:0] in_r_address1;
output   in_r_ce1;
input  [15:0] in_r_q1;
output  [20:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [15:0] out_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[20:0] in_r_address0;
reg in_r_ce0;
reg[20:0] in_r_address1;
reg in_r_ce1;
reg out_r_ce0;
reg out_r_we0;
reg   [5:0] ap_CS_fsm = 6'b000000;
reg   [15:0] reg_223;
reg   [15:0] reg_227;
wire   [31:0] grp_fu_211_p1;
reg   [31:0] reg_231;
wire   [31:0] grp_fu_214_p1;
reg   [31:0] reg_236;
wire   [31:0] grp_fu_185_p2;
reg   [31:0] reg_241;
wire   [31:0] grp_fu_190_p2;
reg   [31:0] reg_247;
wire   [31:0] grp_fu_177_p2;
reg   [31:0] reg_253;
wire   [31:0] grp_fu_181_p2;
reg   [31:0] reg_259;
reg   [31:0] reg_265;
reg   [31:0] reg_271;
wire   [10:0] tmp_fu_278_p2;
reg   [10:0] tmp_reg_626;
wire   [10:0] i_fu_284_p2;
reg   [10:0] i_reg_632;
wire   [22:0] p_addr_fu_320_p2;
reg   [22:0] p_addr_reg_640;
wire   [0:0] exitcond_fu_290_p2;
wire   [22:0] p_addr2_fu_359_p2;
reg   [22:0] p_addr2_reg_650;
reg   [21:0] tmp_45_reg_660;
reg   [21:0] tmp_48_reg_665;
reg   [15:0] in_load_3_reg_680;
reg   [15:0] in_load_4_reg_685;
wire   [63:0] tmp_2_fu_426_p1;
wire   [63:0] tmp_6_fu_431_p1;
wire   [22:0] p_addr3_fu_466_p2;
reg   [22:0] p_addr3_reg_710;
wire   [63:0] tmp_s_fu_508_p1;
wire   [31:0] grp_fu_217_p1;
reg   [31:0] tmp_13_reg_730;
wire   [31:0] grp_fu_220_p1;
reg   [31:0] tmp_16_reg_735;
wire   [63:0] tmp_19_fu_513_p1;
wire   [31:0] grp_fu_195_p2;
reg   [31:0] tmp_14_reg_745;
wire   [31:0] grp_fu_200_p2;
reg   [31:0] tmp_17_reg_750;
wire   [23:0] p_addr_cast1_fu_518_p1;
reg   [23:0] p_addr_cast1_reg_755;
wire   [23:0] p_addr2_cast1_fu_521_p1;
reg   [23:0] p_addr2_cast1_reg_760;
wire   [23:0] p_addr3_cast1_fu_524_p1;
reg   [23:0] p_addr3_cast1_reg_766;
wire   [10:0] tmp6_fu_527_p2;
reg   [10:0] tmp6_reg_771;
wire   [0:0] exitcond1_fu_539_p2;
wire   [23:0] p_addr1_fu_577_p2;
reg   [23:0] p_addr1_reg_789;
wire   [23:0] p_addr9_fu_586_p2;
reg   [23:0] p_addr9_reg_794;
wire   [63:0] tmp_22_fu_599_p1;
wire   [63:0] tmp_26_fu_604_p1;
wire   [63:0] tmp_30_fu_609_p1;
wire   [15:0] tmp_58_fu_614_p1;
reg   [15:0] tmp_58_reg_819;
reg   [10:0] indvar1_reg_133;
reg   [10:0] indvar_reg_144;
reg   [31:0] tmp0_2_reg_155;
reg   [31:0] tmp0_1_reg_165;
wire   [63:0] tmp_23_fu_330_p1;
wire   [63:0] tmp_41_fu_369_p1;
wire   [63:0] tmp_47_fu_405_p1;
wire   [63:0] tmp_50_fu_421_p1;
wire   [63:0] tmp_44_fu_476_p1;
wire   [63:0] tmp_52_fu_503_p1;
wire   [63:0] tmp_53_fu_558_p1;
wire   [63:0] tmp_54_fu_572_p1;
wire   [63:0] tmp_55_fu_594_p1;
wire   [63:0] tmp_56_fu_621_p1;
reg   [31:0] grp_fu_177_p0;
reg   [31:0] grp_fu_177_p1;
reg   [31:0] grp_fu_181_p0;
reg   [31:0] grp_fu_181_p1;
reg   [31:0] grp_fu_185_p0;
wire   [31:0] grp_fu_185_p1;
reg   [31:0] grp_fu_190_p0;
reg   [31:0] grp_fu_190_p1;
wire   [31:0] grp_fu_195_p0;
wire   [31:0] grp_fu_195_p1;
wire   [31:0] grp_fu_200_p0;
wire   [31:0] grp_fu_200_p1;
wire   [31:0] grp_fu_208_p0;
reg   [63:0] grp_fu_211_p0;
reg   [63:0] grp_fu_214_p0;
wire   [63:0] grp_fu_217_p0;
wire   [63:0] grp_fu_220_p0;
wire   [21:0] tmp_1_fu_296_p3;
wire   [17:0] tmp_5_fu_308_p3;
wire   [22:0] p_shl_cast_fu_304_p1;
wire   [22:0] p_shl1_cast_fu_316_p1;
wire   [31:0] tmp_23_fu_330_p0;
wire   [21:0] tmp_39_fu_335_p3;
wire   [17:0] tmp_40_fu_347_p3;
wire   [22:0] p_shl2_cast_fu_343_p1;
wire   [22:0] p_shl3_cast_fu_355_p1;
wire   [31:0] tmp_41_fu_369_p0;
wire   [22:0] tmp_46_fu_394_p3;
wire   [31:0] tmp_47_fu_405_p0;
wire   [22:0] tmp_49_fu_410_p3;
wire   [31:0] tmp_50_fu_421_p0;
wire   [21:0] tmp_42_fu_444_p3;
wire   [17:0] tmp_43_fu_455_p3;
wire   [22:0] p_shl4_cast_fu_451_p1;
wire   [22:0] p_shl5_cast_fu_462_p1;
wire   [31:0] tmp_44_fu_476_p0;
wire   [21:0] tmp_51_fu_481_p4;
wire   [22:0] tmp_57_fu_491_p3;
wire   [31:0] tmp_52_fu_503_p0;
wire   [10:0] j_fu_533_p2;
wire   [23:0] tmp_23_trn5_cast_fu_545_p1;
wire   [23:0] p_addr7_fu_549_p2;
wire   [31:0] tmp_53_fu_558_p0;
wire   [23:0] p_addr4_fu_563_p2;
wire   [31:0] tmp_54_fu_572_p0;
wire   [23:0] tmp_40_trn_cast_fu_582_p1;
wire   [31:0] tmp_55_fu_594_p0;
wire   [63:0] grp_fu_208_p1;
wire   [31:0] tmp_56_fu_621_p0;
wire    grp_fu_177_ce;
wire    grp_fu_181_ce;
reg    grp_fu_185_ce;
reg    grp_fu_190_ce;
wire    grp_fu_195_ce;
wire    grp_fu_200_ce;
wire    grp_fu_208_ce;
wire    grp_fu_211_ce;
wire    grp_fu_214_ce;
wire    grp_fu_217_ce;
wire    grp_fu_220_ce;
reg   [5:0] ap_NS_fsm;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 6'b000000;
parameter    ap_ST_st2_fsm_1 = 6'b1;
parameter    ap_ST_st3_fsm_2 = 6'b10;
parameter    ap_ST_st4_fsm_3 = 6'b11;
parameter    ap_ST_st5_fsm_4 = 6'b100;
parameter    ap_ST_st6_fsm_5 = 6'b101;
parameter    ap_ST_st7_fsm_6 = 6'b110;
parameter    ap_ST_st8_fsm_7 = 6'b111;
parameter    ap_ST_st9_fsm_8 = 6'b1000;
parameter    ap_ST_st10_fsm_9 = 6'b1001;
parameter    ap_ST_st11_fsm_10 = 6'b1010;
parameter    ap_ST_st12_fsm_11 = 6'b1011;
parameter    ap_ST_st13_fsm_12 = 6'b1100;
parameter    ap_ST_st14_fsm_13 = 6'b1101;
parameter    ap_ST_st15_fsm_14 = 6'b1110;
parameter    ap_ST_st16_fsm_15 = 6'b1111;
parameter    ap_ST_st17_fsm_16 = 6'b10000;
parameter    ap_ST_st18_fsm_17 = 6'b10001;
parameter    ap_ST_st19_fsm_18 = 6'b10010;
parameter    ap_ST_st20_fsm_19 = 6'b10011;
parameter    ap_ST_st21_fsm_20 = 6'b10100;
parameter    ap_ST_st22_fsm_21 = 6'b10101;
parameter    ap_ST_st23_fsm_22 = 6'b10110;
parameter    ap_ST_st24_fsm_23 = 6'b10111;
parameter    ap_ST_st25_fsm_24 = 6'b11000;
parameter    ap_ST_st26_fsm_25 = 6'b11001;
parameter    ap_ST_st27_fsm_26 = 6'b11010;
parameter    ap_ST_st28_fsm_27 = 6'b11011;
parameter    ap_ST_st29_fsm_28 = 6'b11100;
parameter    ap_ST_st30_fsm_29 = 6'b11101;
parameter    ap_ST_st31_fsm_30 = 6'b11110;
parameter    ap_ST_st32_fsm_31 = 6'b11111;
parameter    ap_ST_st33_fsm_32 = 6'b100000;
parameter    ap_ST_st34_fsm_33 = 6'b100001;
parameter    ap_ST_st35_fsm_34 = 6'b100010;
parameter    ap_ST_st36_fsm_35 = 6'b100011;
parameter    ap_ST_st37_fsm_36 = 6'b100100;
parameter    ap_ST_st38_fsm_37 = 6'b100101;
parameter    ap_ST_st39_fsm_38 = 6'b100110;
parameter    ap_ST_st40_fsm_39 = 6'b100111;
parameter    ap_ST_st41_fsm_40 = 6'b101000;
parameter    ap_ST_st42_fsm_41 = 6'b101001;
parameter    ap_ST_st43_fsm_42 = 6'b101010;
parameter    ap_ST_st44_fsm_43 = 6'b101011;
parameter    ap_ST_st45_fsm_44 = 6'b101100;
parameter    ap_ST_st46_fsm_45 = 6'b101101;
parameter    ap_ST_st47_fsm_46 = 6'b101110;
parameter    ap_ST_st48_fsm_47 = 6'b101111;
parameter    ap_ST_st49_fsm_48 = 6'b110000;
parameter    ap_ST_st50_fsm_49 = 6'b110001;
parameter    ap_ST_st51_fsm_50 = 6'b110010;
parameter    ap_ST_st52_fsm_51 = 6'b110011;
parameter    ap_ST_st53_fsm_52 = 6'b110100;
parameter    ap_ST_st54_fsm_53 = 6'b110101;
parameter    ap_ST_st55_fsm_54 = 6'b110110;
parameter    ap_ST_st56_fsm_55 = 6'b110111;
parameter    ap_ST_st57_fsm_56 = 6'b111000;
parameter    ap_ST_st58_fsm_57 = 6'b111001;
parameter    ap_ST_st59_fsm_58 = 6'b111010;
parameter    ap_ST_st60_fsm_59 = 6'b111011;
parameter    ap_ST_st61_fsm_60 = 6'b111100;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv32_3E7C8F32 = 32'b111110011111001000111100110010;
parameter    ap_const_lv32_3F1B5159 = 32'b111111000110110101000101011001;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv11_437 = 11'b10000110111;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv11_77E = 11'b11101111110;
parameter    ap_true = 1'b1;


gaussian_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fadd_32ns_32ns_32_5_full_dsp_U1(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_177_p0 ),
    .din1( grp_fu_177_p1 ),
    .ce( grp_fu_177_ce ),
    .dout( grp_fu_177_p2 )
);

gaussian_fadd_32ns_32ns_32_5_full_dsp #(
    .ID( 2 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fadd_32ns_32ns_32_5_full_dsp_U2(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_181_p0 ),
    .din1( grp_fu_181_p1 ),
    .ce( grp_fu_181_ce ),
    .dout( grp_fu_181_p2 )
);

gaussian_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 3 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_4_max_dsp_U3(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_185_p0 ),
    .din1( grp_fu_185_p1 ),
    .ce( grp_fu_185_ce ),
    .dout( grp_fu_185_p2 )
);

gaussian_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 4 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_4_max_dsp_U4(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_190_p0 ),
    .din1( grp_fu_190_p1 ),
    .ce( grp_fu_190_ce ),
    .dout( grp_fu_190_p2 )
);

gaussian_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 5 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_4_max_dsp_U5(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_195_p0 ),
    .din1( grp_fu_195_p1 ),
    .ce( grp_fu_195_ce ),
    .dout( grp_fu_195_p2 )
);

gaussian_fmul_32ns_32ns_32_4_max_dsp #(
    .ID( 6 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
gaussian_fmul_32ns_32ns_32_4_max_dsp_U6(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_200_p0 ),
    .din1( grp_fu_200_p1 ),
    .ce( grp_fu_200_ce ),
    .dout( grp_fu_200_p2 )
);

gaussian_fptoui_32ns_64_4 #(
    .ID( 7 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
gaussian_fptoui_32ns_64_4_U7(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_208_p0 ),
    .ce( grp_fu_208_ce ),
    .dout( grp_fu_208_p1 )
);

gaussian_sitofp_64ns_32_6 #(
    .ID( 8 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_6_U8(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_211_p0 ),
    .ce( grp_fu_211_ce ),
    .dout( grp_fu_211_p1 )
);

gaussian_sitofp_64ns_32_6 #(
    .ID( 9 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_6_U9(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_214_p0 ),
    .ce( grp_fu_214_ce ),
    .dout( grp_fu_214_p1 )
);

gaussian_sitofp_64ns_32_6 #(
    .ID( 10 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_6_U10(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_217_p0 ),
    .ce( grp_fu_217_ce ),
    .dout( grp_fu_217_p1 )
);

gaussian_sitofp_64ns_32_6 #(
    .ID( 11 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
gaussian_sitofp_64ns_32_6_U11(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_220_p0 ),
    .ce( grp_fu_220_ce ),
    .dout( grp_fu_220_p1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) & ~(ap_const_lv1_0 == exitcond1_fu_539_p2))) begin
        indvar1_reg_133 <= i_reg_632;
    end else if (((ap_ST_st1_fsm_0 == ap_CS_fsm) & ~(ap_start == ap_const_logic_0))) begin
        indvar1_reg_133 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        indvar_reg_144 <= ap_const_lv11_0;
    end else if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        indvar_reg_144 <= tmp6_reg_771;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        tmp0_1_reg_165 <= reg_253;
    end else if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        tmp0_1_reg_165 <= tmp0_2_reg_155;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        tmp0_2_reg_155 <= reg_259;
    end else if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        tmp0_2_reg_155 <= reg_271;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        i_reg_632 <= i_fu_284_p2;
        tmp_reg_626 <= tmp_fu_278_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st4_fsm_3 == ap_CS_fsm)) begin
        in_load_3_reg_680 <= in_r_q0;
        in_load_4_reg_685 <= in_r_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2))) begin
        p_addr1_reg_789 <= p_addr1_fu_577_p2;
        p_addr9_reg_794 <= p_addr9_fu_586_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st25_fsm_24 == ap_CS_fsm)) begin
        p_addr2_cast1_reg_760[7] <= p_addr2_cast1_fu_521_p1[7];
p_addr2_cast1_reg_760[8] <= p_addr2_cast1_fu_521_p1[8];
p_addr2_cast1_reg_760[9] <= p_addr2_cast1_fu_521_p1[9];
p_addr2_cast1_reg_760[10] <= p_addr2_cast1_fu_521_p1[10];
p_addr2_cast1_reg_760[11] <= p_addr2_cast1_fu_521_p1[11];
p_addr2_cast1_reg_760[12] <= p_addr2_cast1_fu_521_p1[12];
p_addr2_cast1_reg_760[13] <= p_addr2_cast1_fu_521_p1[13];
p_addr2_cast1_reg_760[14] <= p_addr2_cast1_fu_521_p1[14];
p_addr2_cast1_reg_760[15] <= p_addr2_cast1_fu_521_p1[15];
p_addr2_cast1_reg_760[16] <= p_addr2_cast1_fu_521_p1[16];
p_addr2_cast1_reg_760[17] <= p_addr2_cast1_fu_521_p1[17];
p_addr2_cast1_reg_760[18] <= p_addr2_cast1_fu_521_p1[18];
p_addr2_cast1_reg_760[19] <= p_addr2_cast1_fu_521_p1[19];
p_addr2_cast1_reg_760[20] <= p_addr2_cast1_fu_521_p1[20];
p_addr2_cast1_reg_760[21] <= p_addr2_cast1_fu_521_p1[21];
p_addr2_cast1_reg_760[22] <= p_addr2_cast1_fu_521_p1[22];
p_addr2_cast1_reg_760[23] <= p_addr2_cast1_fu_521_p1[23];
        p_addr3_cast1_reg_766[7] <= p_addr3_cast1_fu_524_p1[7];
p_addr3_cast1_reg_766[8] <= p_addr3_cast1_fu_524_p1[8];
p_addr3_cast1_reg_766[9] <= p_addr3_cast1_fu_524_p1[9];
p_addr3_cast1_reg_766[10] <= p_addr3_cast1_fu_524_p1[10];
p_addr3_cast1_reg_766[11] <= p_addr3_cast1_fu_524_p1[11];
p_addr3_cast1_reg_766[12] <= p_addr3_cast1_fu_524_p1[12];
p_addr3_cast1_reg_766[13] <= p_addr3_cast1_fu_524_p1[13];
p_addr3_cast1_reg_766[14] <= p_addr3_cast1_fu_524_p1[14];
p_addr3_cast1_reg_766[15] <= p_addr3_cast1_fu_524_p1[15];
p_addr3_cast1_reg_766[16] <= p_addr3_cast1_fu_524_p1[16];
p_addr3_cast1_reg_766[17] <= p_addr3_cast1_fu_524_p1[17];
p_addr3_cast1_reg_766[18] <= p_addr3_cast1_fu_524_p1[18];
p_addr3_cast1_reg_766[19] <= p_addr3_cast1_fu_524_p1[19];
p_addr3_cast1_reg_766[20] <= p_addr3_cast1_fu_524_p1[20];
p_addr3_cast1_reg_766[21] <= p_addr3_cast1_fu_524_p1[21];
p_addr3_cast1_reg_766[22] <= p_addr3_cast1_fu_524_p1[22];
p_addr3_cast1_reg_766[23] <= p_addr3_cast1_fu_524_p1[23];
        p_addr_cast1_reg_755[7] <= p_addr_cast1_fu_518_p1[7];
p_addr_cast1_reg_755[8] <= p_addr_cast1_fu_518_p1[8];
p_addr_cast1_reg_755[9] <= p_addr_cast1_fu_518_p1[9];
p_addr_cast1_reg_755[10] <= p_addr_cast1_fu_518_p1[10];
p_addr_cast1_reg_755[11] <= p_addr_cast1_fu_518_p1[11];
p_addr_cast1_reg_755[12] <= p_addr_cast1_fu_518_p1[12];
p_addr_cast1_reg_755[13] <= p_addr_cast1_fu_518_p1[13];
p_addr_cast1_reg_755[14] <= p_addr_cast1_fu_518_p1[14];
p_addr_cast1_reg_755[15] <= p_addr_cast1_fu_518_p1[15];
p_addr_cast1_reg_755[16] <= p_addr_cast1_fu_518_p1[16];
p_addr_cast1_reg_755[17] <= p_addr_cast1_fu_518_p1[17];
p_addr_cast1_reg_755[18] <= p_addr_cast1_fu_518_p1[18];
p_addr_cast1_reg_755[19] <= p_addr_cast1_fu_518_p1[19];
p_addr_cast1_reg_755[20] <= p_addr_cast1_fu_518_p1[20];
p_addr_cast1_reg_755[21] <= p_addr_cast1_fu_518_p1[21];
p_addr_cast1_reg_755[22] <= p_addr_cast1_fu_518_p1[22];
p_addr_cast1_reg_755[23] <= p_addr_cast1_fu_518_p1[23];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_290_p2 == ap_const_lv1_0))) begin
        p_addr2_reg_650[7] <= p_addr2_fu_359_p2[7];
p_addr2_reg_650[8] <= p_addr2_fu_359_p2[8];
p_addr2_reg_650[9] <= p_addr2_fu_359_p2[9];
p_addr2_reg_650[10] <= p_addr2_fu_359_p2[10];
p_addr2_reg_650[11] <= p_addr2_fu_359_p2[11];
p_addr2_reg_650[12] <= p_addr2_fu_359_p2[12];
p_addr2_reg_650[13] <= p_addr2_fu_359_p2[13];
p_addr2_reg_650[14] <= p_addr2_fu_359_p2[14];
p_addr2_reg_650[15] <= p_addr2_fu_359_p2[15];
p_addr2_reg_650[16] <= p_addr2_fu_359_p2[16];
p_addr2_reg_650[17] <= p_addr2_fu_359_p2[17];
p_addr2_reg_650[18] <= p_addr2_fu_359_p2[18];
p_addr2_reg_650[19] <= p_addr2_fu_359_p2[19];
p_addr2_reg_650[20] <= p_addr2_fu_359_p2[20];
p_addr2_reg_650[21] <= p_addr2_fu_359_p2[21];
p_addr2_reg_650[22] <= p_addr2_fu_359_p2[22];
        p_addr_reg_640[7] <= p_addr_fu_320_p2[7];
p_addr_reg_640[8] <= p_addr_fu_320_p2[8];
p_addr_reg_640[9] <= p_addr_fu_320_p2[9];
p_addr_reg_640[10] <= p_addr_fu_320_p2[10];
p_addr_reg_640[11] <= p_addr_fu_320_p2[11];
p_addr_reg_640[12] <= p_addr_fu_320_p2[12];
p_addr_reg_640[13] <= p_addr_fu_320_p2[13];
p_addr_reg_640[14] <= p_addr_fu_320_p2[14];
p_addr_reg_640[15] <= p_addr_fu_320_p2[15];
p_addr_reg_640[16] <= p_addr_fu_320_p2[16];
p_addr_reg_640[17] <= p_addr_fu_320_p2[17];
p_addr_reg_640[18] <= p_addr_fu_320_p2[18];
p_addr_reg_640[19] <= p_addr_fu_320_p2[19];
p_addr_reg_640[20] <= p_addr_fu_320_p2[20];
p_addr_reg_640[21] <= p_addr_fu_320_p2[21];
p_addr_reg_640[22] <= p_addr_fu_320_p2[22];
        tmp_45_reg_660 <= {{p_addr_fu_320_p2[ap_const_lv32_16 : ap_const_lv32_1]}};
        tmp_48_reg_665 <= {{p_addr2_fu_359_p2[ap_const_lv32_16 : ap_const_lv32_1]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        p_addr3_reg_710[7] <= p_addr3_fu_466_p2[7];
p_addr3_reg_710[8] <= p_addr3_fu_466_p2[8];
p_addr3_reg_710[9] <= p_addr3_fu_466_p2[9];
p_addr3_reg_710[10] <= p_addr3_fu_466_p2[10];
p_addr3_reg_710[11] <= p_addr3_fu_466_p2[11];
p_addr3_reg_710[12] <= p_addr3_fu_466_p2[12];
p_addr3_reg_710[13] <= p_addr3_fu_466_p2[13];
p_addr3_reg_710[14] <= p_addr3_fu_466_p2[14];
p_addr3_reg_710[15] <= p_addr3_fu_466_p2[15];
p_addr3_reg_710[16] <= p_addr3_fu_466_p2[16];
p_addr3_reg_710[17] <= p_addr3_fu_466_p2[17];
p_addr3_reg_710[18] <= p_addr3_fu_466_p2[18];
p_addr3_reg_710[19] <= p_addr3_fu_466_p2[19];
p_addr3_reg_710[20] <= p_addr3_fu_466_p2[20];
p_addr3_reg_710[21] <= p_addr3_fu_466_p2[21];
p_addr3_reg_710[22] <= p_addr3_fu_466_p2[22];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm) | (ap_ST_st28_fsm_27 == ap_CS_fsm))) begin
        reg_223 <= in_r_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st9_fsm_8 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm))) begin
        reg_227 <= in_r_q1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm) | (ap_ST_st38_fsm_37 == ap_CS_fsm))) begin
        reg_231 <= grp_fu_211_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st10_fsm_9 == ap_CS_fsm) | (ap_ST_st15_fsm_14 == ap_CS_fsm) | (ap_ST_st33_fsm_32 == ap_CS_fsm))) begin
        reg_236 <= grp_fu_214_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm) | (ap_ST_st42_fsm_41 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm))) begin
        reg_241 <= grp_fu_185_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm))) begin
        reg_247 <= grp_fu_190_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st24_fsm_23 == ap_CS_fsm))) begin
        reg_253 <= grp_fu_177_p2;
        reg_259 <= grp_fu_181_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st34_fsm_33 == ap_CS_fsm) | (ap_ST_st56_fsm_55 == ap_CS_fsm))) begin
        reg_265 <= grp_fu_177_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_ST_st42_fsm_41 == ap_CS_fsm) | (ap_ST_st47_fsm_46 == ap_CS_fsm))) begin
        reg_271 <= grp_fu_177_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        tmp6_reg_771 <= tmp6_fu_527_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        tmp_13_reg_730 <= grp_fu_217_p1;
        tmp_16_reg_735 <= grp_fu_220_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st14_fsm_13 == ap_CS_fsm)) begin
        tmp_14_reg_745 <= grp_fu_195_p2;
        tmp_17_reg_750 <= grp_fu_200_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_ST_st60_fsm_59 == ap_CS_fsm)) begin
        tmp_58_reg_819 <= tmp_58_fu_614_p1;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_CS_fsm or exitcond_fu_290_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm)) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond_fu_290_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_CS_fsm)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_ST_st1_fsm_0 == ap_CS_fsm))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_CS_fsm or exitcond_fu_290_p2)
begin
    if (((ap_ST_st2_fsm_1 == ap_CS_fsm) & ~(exitcond_fu_290_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// grp_fu_177_p0 assign process. ///
always @ (ap_CS_fsm or reg_241 or reg_253 or reg_265 or reg_271)
begin
    if ((ap_ST_st52_fsm_51 == ap_CS_fsm)) begin
        grp_fu_177_p0 = reg_265;
    end else if ((ap_ST_st43_fsm_42 == ap_CS_fsm)) begin
        grp_fu_177_p0 = reg_271;
    end else if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        grp_fu_177_p0 = reg_253;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) | (ap_ST_st38_fsm_37 == ap_CS_fsm) | (ap_ST_st30_fsm_29 == ap_CS_fsm))) begin
        grp_fu_177_p0 = reg_241;
    end else begin
        grp_fu_177_p0 = reg_271;
    end
end

/// grp_fu_177_p1 assign process. ///
always @ (ap_CS_fsm or reg_241 or reg_247)
begin
    if (((ap_ST_st20_fsm_19 == ap_CS_fsm) | (ap_ST_st43_fsm_42 == ap_CS_fsm) | (ap_ST_st52_fsm_51 == ap_CS_fsm))) begin
        grp_fu_177_p1 = reg_241;
    end else if (((ap_ST_st15_fsm_14 == ap_CS_fsm) | (ap_ST_st38_fsm_37 == ap_CS_fsm) | (ap_ST_st30_fsm_29 == ap_CS_fsm))) begin
        grp_fu_177_p1 = reg_247;
    end else begin
        grp_fu_177_p1 = reg_247;
    end
end

/// grp_fu_181_p0 assign process. ///
always @ (ap_CS_fsm or reg_259 or tmp_14_reg_745)
begin
    if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        grp_fu_181_p0 = reg_259;
    end else if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        grp_fu_181_p0 = tmp_14_reg_745;
    end else begin
        grp_fu_181_p0 = tmp_14_reg_745;
    end
end

/// grp_fu_181_p1 assign process. ///
always @ (ap_CS_fsm or reg_247 or tmp_17_reg_750)
begin
    if ((ap_ST_st20_fsm_19 == ap_CS_fsm)) begin
        grp_fu_181_p1 = reg_247;
    end else if ((ap_ST_st15_fsm_14 == ap_CS_fsm)) begin
        grp_fu_181_p1 = tmp_17_reg_750;
    end else begin
        grp_fu_181_p1 = tmp_17_reg_750;
    end
end

/// grp_fu_185_ce assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_539_p2)
begin
    if (((ap_ST_st27_fsm_26 == ap_CS_fsm) | (ap_ST_st28_fsm_27 == ap_CS_fsm) | (ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm) | (ap_ST_st42_fsm_41 == ap_CS_fsm) | (ap_ST_st51_fsm_50 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm) | ((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2)) | (ap_ST_st11_fsm_10 == ap_CS_fsm) | (ap_ST_st16_fsm_15 == ap_CS_fsm) | (ap_ST_st39_fsm_38 == ap_CS_fsm) | (ap_ST_st48_fsm_47 == ap_CS_fsm) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st18_fsm_17 == ap_CS_fsm) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st36_fsm_35 == ap_CS_fsm) | (ap_ST_st40_fsm_39 == ap_CS_fsm) | (ap_ST_st41_fsm_40 == ap_CS_fsm) | (ap_ST_st49_fsm_48 == ap_CS_fsm) | (ap_ST_st50_fsm_49 == ap_CS_fsm))) begin
        grp_fu_185_ce = ap_const_logic_1;
    end else begin
        grp_fu_185_ce = ap_const_logic_0;
    end
end

/// grp_fu_185_p0 assign process. ///
always @ (ap_CS_fsm or reg_231 or reg_271 or exitcond1_fu_539_p2 or tmp0_1_reg_165)
begin
    if ((ap_ST_st48_fsm_47 == ap_CS_fsm)) begin
        grp_fu_185_p0 = reg_271;
    end else if (((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2))) begin
        grp_fu_185_p0 = tmp0_1_reg_165;
    end else if (((ap_ST_st34_fsm_33 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm) | (ap_ST_st16_fsm_15 == ap_CS_fsm) | (ap_ST_st39_fsm_38 == ap_CS_fsm))) begin
        grp_fu_185_p0 = reg_231;
    end else begin
        grp_fu_185_p0 = tmp0_1_reg_165;
    end
end

/// grp_fu_190_ce assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_539_p2)
begin
    if (((ap_ST_st27_fsm_26 == ap_CS_fsm) | (ap_ST_st28_fsm_27 == ap_CS_fsm) | (ap_ST_st14_fsm_13 == ap_CS_fsm) | (ap_ST_st19_fsm_18 == ap_CS_fsm) | (ap_ST_st29_fsm_28 == ap_CS_fsm) | (ap_ST_st37_fsm_36 == ap_CS_fsm) | (ap_ST_st34_fsm_33 == ap_CS_fsm) | ((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2)) | (ap_ST_st11_fsm_10 == ap_CS_fsm) | (ap_ST_st16_fsm_15 == ap_CS_fsm) | (ap_ST_st12_fsm_11 == ap_CS_fsm) | (ap_ST_st13_fsm_12 == ap_CS_fsm) | (ap_ST_st17_fsm_16 == ap_CS_fsm) | (ap_ST_st18_fsm_17 == ap_CS_fsm) | (ap_ST_st35_fsm_34 == ap_CS_fsm) | (ap_ST_st36_fsm_35 == ap_CS_fsm))) begin
        grp_fu_190_ce = ap_const_logic_1;
    end else begin
        grp_fu_190_ce = ap_const_logic_0;
    end
end

/// grp_fu_190_p0 assign process. ///
always @ (ap_CS_fsm or reg_236 or exitcond1_fu_539_p2 or tmp0_2_reg_155)
begin
    if (((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2))) begin
        grp_fu_190_p0 = tmp0_2_reg_155;
    end else if (((ap_ST_st34_fsm_33 == ap_CS_fsm) | (ap_ST_st11_fsm_10 == ap_CS_fsm) | (ap_ST_st16_fsm_15 == ap_CS_fsm))) begin
        grp_fu_190_p0 = reg_236;
    end else begin
        grp_fu_190_p0 = tmp0_2_reg_155;
    end
end

/// grp_fu_190_p1 assign process. ///
always @ (ap_CS_fsm or exitcond1_fu_539_p2)
begin
    if ((ap_ST_st16_fsm_15 == ap_CS_fsm)) begin
        grp_fu_190_p1 = ap_const_lv32_3E7C8F32;
    end else if (((ap_ST_st34_fsm_33 == ap_CS_fsm) | ((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2)) | (ap_ST_st11_fsm_10 == ap_CS_fsm))) begin
        grp_fu_190_p1 = ap_const_lv32_3F1B5159;
    end else begin
        grp_fu_190_p1 = ap_const_lv32_3F1B5159;
    end
end

/// grp_fu_211_p0 assign process. ///
always @ (ap_CS_fsm or tmp_2_fu_426_p1 or tmp_s_fu_508_p1 or tmp_22_fu_599_p1 or tmp_30_fu_609_p1)
begin
    if ((ap_ST_st33_fsm_32 == ap_CS_fsm)) begin
        grp_fu_211_p0 = tmp_30_fu_609_p1;
    end else if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        grp_fu_211_p0 = tmp_22_fu_599_p1;
    end else if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        grp_fu_211_p0 = tmp_s_fu_508_p1;
    end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        grp_fu_211_p0 = tmp_2_fu_426_p1;
    end else begin
        grp_fu_211_p0 = tmp_30_fu_609_p1;
    end
end

/// grp_fu_214_p0 assign process. ///
always @ (ap_CS_fsm or tmp_6_fu_431_p1 or tmp_19_fu_513_p1 or tmp_26_fu_604_p1)
begin
    if ((ap_ST_st28_fsm_27 == ap_CS_fsm)) begin
        grp_fu_214_p0 = tmp_26_fu_604_p1;
    end else if ((ap_ST_st10_fsm_9 == ap_CS_fsm)) begin
        grp_fu_214_p0 = tmp_19_fu_513_p1;
    end else if ((ap_ST_st5_fsm_4 == ap_CS_fsm)) begin
        grp_fu_214_p0 = tmp_6_fu_431_p1;
    end else begin
        grp_fu_214_p0 = tmp_26_fu_604_p1;
    end
end

/// in_r_address0 assign process. ///
always @ (ap_CS_fsm or tmp_23_fu_330_p1 or tmp_47_fu_405_p1 or tmp_44_fu_476_p1 or tmp_53_fu_558_p1 or tmp_55_fu_594_p1)
begin
    if ((ap_ST_st27_fsm_26 == ap_CS_fsm)) begin
        in_r_address0 = tmp_55_fu_594_p1;
    end else if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        in_r_address0 = tmp_53_fu_558_p1;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        in_r_address0 = tmp_44_fu_476_p1;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        in_r_address0 = tmp_47_fu_405_p1;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        in_r_address0 = tmp_23_fu_330_p1;
    end else begin
        in_r_address0 = tmp_55_fu_594_p1;
    end
end

/// in_r_address1 assign process. ///
always @ (ap_CS_fsm or tmp_41_fu_369_p1 or tmp_50_fu_421_p1 or tmp_52_fu_503_p1 or tmp_54_fu_572_p1)
begin
    if ((ap_ST_st26_fsm_25 == ap_CS_fsm)) begin
        in_r_address1 = tmp_54_fu_572_p1;
    end else if ((ap_ST_st8_fsm_7 == ap_CS_fsm)) begin
        in_r_address1 = tmp_52_fu_503_p1;
    end else if ((ap_ST_st3_fsm_2 == ap_CS_fsm)) begin
        in_r_address1 = tmp_50_fu_421_p1;
    end else if ((ap_ST_st2_fsm_1 == ap_CS_fsm)) begin
        in_r_address1 = tmp_41_fu_369_p1;
    end else begin
        in_r_address1 = tmp_54_fu_572_p1;
    end
end

/// in_r_ce0 assign process. ///
always @ (ap_CS_fsm or exitcond_fu_290_p2 or exitcond1_fu_539_p2)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | (ap_ST_st27_fsm_26 == ap_CS_fsm) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_290_p2 == ap_const_lv1_0)) | (ap_ST_st8_fsm_7 == ap_CS_fsm) | ((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2)))) begin
        in_r_ce0 = ap_const_logic_1;
    end else begin
        in_r_ce0 = ap_const_logic_0;
    end
end

/// in_r_ce1 assign process. ///
always @ (ap_CS_fsm or exitcond_fu_290_p2 or exitcond1_fu_539_p2)
begin
    if (((ap_ST_st3_fsm_2 == ap_CS_fsm) | ((ap_ST_st2_fsm_1 == ap_CS_fsm) & (exitcond_fu_290_p2 == ap_const_lv1_0)) | (ap_ST_st8_fsm_7 == ap_CS_fsm) | ((ap_ST_st26_fsm_25 == ap_CS_fsm) & (ap_const_lv1_0 == exitcond1_fu_539_p2)))) begin
        in_r_ce1 = ap_const_logic_1;
    end else begin
        in_r_ce1 = ap_const_logic_0;
    end
end

/// out_r_ce0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        out_r_ce0 = ap_const_logic_1;
    end else begin
        out_r_ce0 = ap_const_logic_0;
    end
end

/// out_r_we0 assign process. ///
always @ (ap_CS_fsm)
begin
    if ((ap_ST_st61_fsm_60 == ap_CS_fsm)) begin
        out_r_we0 = ap_const_logic_1;
    end else begin
        out_r_we0 = ap_const_logic_0;
    end
end
always @ (ap_start or ap_CS_fsm or exitcond_fu_290_p2 or exitcond1_fu_539_p2)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        ap_ST_st2_fsm_1 : 
            if (~(exitcond_fu_290_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        ap_ST_st3_fsm_2 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
        ap_ST_st4_fsm_3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
        ap_ST_st5_fsm_4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
        ap_ST_st6_fsm_5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
        ap_ST_st7_fsm_6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
        ap_ST_st8_fsm_7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
        ap_ST_st9_fsm_8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
        ap_ST_st10_fsm_9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
        ap_ST_st11_fsm_10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
        ap_ST_st12_fsm_11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
        ap_ST_st13_fsm_12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
        ap_ST_st14_fsm_13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
        ap_ST_st15_fsm_14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
        ap_ST_st16_fsm_15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
        ap_ST_st17_fsm_16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
        ap_ST_st18_fsm_17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
        ap_ST_st19_fsm_18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
        ap_ST_st20_fsm_19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
        ap_ST_st21_fsm_20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
        ap_ST_st22_fsm_21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
        ap_ST_st23_fsm_22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
        ap_ST_st24_fsm_23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
        ap_ST_st25_fsm_24 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        ap_ST_st26_fsm_25 : 
            if ((ap_const_lv1_0 == exitcond1_fu_539_p2)) begin
                ap_NS_fsm = ap_ST_st27_fsm_26;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        ap_ST_st27_fsm_26 : 
            ap_NS_fsm = ap_ST_st28_fsm_27;
        ap_ST_st28_fsm_27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
        ap_ST_st29_fsm_28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
        ap_ST_st30_fsm_29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
        ap_ST_st31_fsm_30 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
        ap_ST_st32_fsm_31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
        ap_ST_st33_fsm_32 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
        ap_ST_st34_fsm_33 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
        ap_ST_st35_fsm_34 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
        ap_ST_st36_fsm_35 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
        ap_ST_st37_fsm_36 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
        ap_ST_st38_fsm_37 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
        ap_ST_st39_fsm_38 : 
            ap_NS_fsm = ap_ST_st40_fsm_39;
        ap_ST_st40_fsm_39 : 
            ap_NS_fsm = ap_ST_st41_fsm_40;
        ap_ST_st41_fsm_40 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
        ap_ST_st42_fsm_41 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
        ap_ST_st43_fsm_42 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
        ap_ST_st44_fsm_43 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
        ap_ST_st45_fsm_44 : 
            ap_NS_fsm = ap_ST_st46_fsm_45;
        ap_ST_st46_fsm_45 : 
            ap_NS_fsm = ap_ST_st47_fsm_46;
        ap_ST_st47_fsm_46 : 
            ap_NS_fsm = ap_ST_st48_fsm_47;
        ap_ST_st48_fsm_47 : 
            ap_NS_fsm = ap_ST_st49_fsm_48;
        ap_ST_st49_fsm_48 : 
            ap_NS_fsm = ap_ST_st50_fsm_49;
        ap_ST_st50_fsm_49 : 
            ap_NS_fsm = ap_ST_st51_fsm_50;
        ap_ST_st51_fsm_50 : 
            ap_NS_fsm = ap_ST_st52_fsm_51;
        ap_ST_st52_fsm_51 : 
            ap_NS_fsm = ap_ST_st53_fsm_52;
        ap_ST_st53_fsm_52 : 
            ap_NS_fsm = ap_ST_st54_fsm_53;
        ap_ST_st54_fsm_53 : 
            ap_NS_fsm = ap_ST_st55_fsm_54;
        ap_ST_st55_fsm_54 : 
            ap_NS_fsm = ap_ST_st56_fsm_55;
        ap_ST_st56_fsm_55 : 
            ap_NS_fsm = ap_ST_st57_fsm_56;
        ap_ST_st57_fsm_56 : 
            ap_NS_fsm = ap_ST_st58_fsm_57;
        ap_ST_st58_fsm_57 : 
            ap_NS_fsm = ap_ST_st59_fsm_58;
        ap_ST_st59_fsm_58 : 
            ap_NS_fsm = ap_ST_st60_fsm_59;
        ap_ST_st60_fsm_59 : 
            ap_NS_fsm = ap_ST_st61_fsm_60;
        ap_ST_st61_fsm_60 : 
            ap_NS_fsm = ap_ST_st26_fsm_25;
        default : 
            ap_NS_fsm = 'bx;
    endcase
end
assign exitcond1_fu_539_p2 = (indvar_reg_144 == ap_const_lv11_77E? 1'b1: 1'b0);
assign exitcond_fu_290_p2 = (indvar1_reg_133 == ap_const_lv11_437? 1'b1: 1'b0);
assign grp_fu_177_ce = ap_const_logic_1;
assign grp_fu_181_ce = ap_const_logic_1;
assign grp_fu_185_p1 = ap_const_lv32_3E7C8F32;
assign grp_fu_195_ce = ap_const_logic_1;
assign grp_fu_195_p0 = tmp_13_reg_730;
assign grp_fu_195_p1 = ap_const_lv32_3E7C8F32;
assign grp_fu_200_ce = ap_const_logic_1;
assign grp_fu_200_p0 = tmp_16_reg_735;
assign grp_fu_200_p1 = ap_const_lv32_3F1B5159;
assign grp_fu_208_ce = ap_const_logic_1;
assign grp_fu_208_p0 = reg_265;
assign grp_fu_211_ce = ap_const_logic_1;
assign grp_fu_214_ce = ap_const_logic_1;
assign grp_fu_217_ce = ap_const_logic_1;
assign grp_fu_217_p0 = $unsigned(in_load_3_reg_680);
assign grp_fu_220_ce = ap_const_logic_1;
assign grp_fu_220_p0 = $unsigned(in_load_4_reg_685);
assign i_fu_284_p2 = (indvar1_reg_133 + ap_const_lv11_1);
assign j_fu_533_p2 = (indvar_reg_144 + ap_const_lv11_2);
assign out_r_address0 = tmp_56_fu_621_p1;
assign out_r_d0 = tmp_58_reg_819;
assign p_addr1_fu_577_p2 = (p_addr3_cast1_reg_766 + tmp_23_trn5_cast_fu_545_p1);
assign p_addr2_cast1_fu_521_p1 = $signed(p_addr2_reg_650);
assign p_addr2_fu_359_p2 = (p_shl2_cast_fu_343_p1 - p_shl3_cast_fu_355_p1);
assign p_addr3_cast1_fu_524_p1 = $signed(p_addr3_reg_710);
assign p_addr3_fu_466_p2 = (p_shl4_cast_fu_451_p1 - p_shl5_cast_fu_462_p1);
assign p_addr4_fu_563_p2 = (p_addr2_cast1_reg_760 + tmp_23_trn5_cast_fu_545_p1);
assign p_addr7_fu_549_p2 = (p_addr_cast1_reg_755 + tmp_23_trn5_cast_fu_545_p1);
assign p_addr9_fu_586_p2 = (p_addr2_cast1_reg_760 + tmp_40_trn_cast_fu_582_p1);
assign p_addr_cast1_fu_518_p1 = $signed(p_addr_reg_640);
assign p_addr_fu_320_p2 = (p_shl_cast_fu_304_p1 - p_shl1_cast_fu_316_p1);
assign p_shl1_cast_fu_316_p1 = $unsigned(tmp_5_fu_308_p3);
assign p_shl2_cast_fu_343_p1 = $unsigned(tmp_39_fu_335_p3);
assign p_shl3_cast_fu_355_p1 = $unsigned(tmp_40_fu_347_p3);
assign p_shl4_cast_fu_451_p1 = $unsigned(tmp_42_fu_444_p3);
assign p_shl5_cast_fu_462_p1 = $unsigned(tmp_43_fu_455_p3);
assign p_shl_cast_fu_304_p1 = $unsigned(tmp_1_fu_296_p3);
assign tmp6_fu_527_p2 = (indvar_reg_144 + ap_const_lv11_1);
assign tmp_19_fu_513_p1 = $unsigned(reg_227);
assign tmp_1_fu_296_p3 = {{indvar1_reg_133}, {ap_const_lv11_0}};
assign tmp_22_fu_599_p1 = $unsigned(reg_223);
assign tmp_23_fu_330_p0 = $signed(p_addr_fu_320_p2);
assign tmp_23_fu_330_p1 = $unsigned(tmp_23_fu_330_p0);
assign tmp_23_trn5_cast_fu_545_p1 = $unsigned(j_fu_533_p2);
assign tmp_26_fu_604_p1 = $unsigned(reg_227);
assign tmp_2_fu_426_p1 = $unsigned(reg_223);
assign tmp_30_fu_609_p1 = $unsigned(reg_223);
assign tmp_39_fu_335_p3 = {{i_fu_284_p2}, {ap_const_lv11_0}};
assign tmp_40_fu_347_p3 = {{i_fu_284_p2}, {ap_const_lv7_0}};
assign tmp_40_trn_cast_fu_582_p1 = $unsigned(tmp6_fu_527_p2);
assign tmp_41_fu_369_p0 = $signed(p_addr2_fu_359_p2);
assign tmp_41_fu_369_p1 = $unsigned(tmp_41_fu_369_p0);
assign tmp_42_fu_444_p3 = {{tmp_reg_626}, {ap_const_lv11_0}};
assign tmp_43_fu_455_p3 = {{tmp_reg_626}, {ap_const_lv7_0}};
assign tmp_44_fu_476_p0 = $signed(p_addr3_fu_466_p2);
assign tmp_44_fu_476_p1 = $unsigned(tmp_44_fu_476_p0);
assign tmp_46_fu_394_p3 = {{tmp_45_reg_660}, {ap_const_lv1_1}};
assign tmp_47_fu_405_p0 = $signed(tmp_46_fu_394_p3);
assign tmp_47_fu_405_p1 = $unsigned(tmp_47_fu_405_p0);
assign tmp_49_fu_410_p3 = {{tmp_48_reg_665}, {ap_const_lv1_1}};
assign tmp_50_fu_421_p0 = $signed(tmp_49_fu_410_p3);
assign tmp_50_fu_421_p1 = $unsigned(tmp_50_fu_421_p0);
assign tmp_51_fu_481_p4 = {{p_addr3_fu_466_p2[ap_const_lv32_16 : ap_const_lv32_1]}};
assign tmp_52_fu_503_p0 = $signed(tmp_57_fu_491_p3);
assign tmp_52_fu_503_p1 = $unsigned(tmp_52_fu_503_p0);
assign tmp_53_fu_558_p0 = $signed(p_addr7_fu_549_p2);
assign tmp_53_fu_558_p1 = $unsigned(tmp_53_fu_558_p0);
assign tmp_54_fu_572_p0 = $signed(p_addr4_fu_563_p2);
assign tmp_54_fu_572_p1 = $unsigned(tmp_54_fu_572_p0);
assign tmp_55_fu_594_p0 = $signed(p_addr1_reg_789);
assign tmp_55_fu_594_p1 = $unsigned(tmp_55_fu_594_p0);
assign tmp_56_fu_621_p0 = $signed(p_addr9_reg_794);
assign tmp_56_fu_621_p1 = $unsigned(tmp_56_fu_621_p0);
assign tmp_57_fu_491_p3 = {{tmp_51_fu_481_p4}, {ap_const_lv1_1}};
assign tmp_58_fu_614_p1 = grp_fu_208_p1[15:0];
assign tmp_5_fu_308_p3 = {{indvar1_reg_133}, {ap_const_lv7_0}};
assign tmp_6_fu_431_p1 = $unsigned(reg_227);
assign tmp_fu_278_p2 = (indvar1_reg_133 + ap_const_lv11_2);
assign tmp_s_fu_508_p1 = $unsigned(reg_223);
always @ (posedge ap_clk)
begin
    p_addr_reg_640[6:0] <= 7'b0000000;
    p_addr2_reg_650[6:0] <= 7'b0000000;
    p_addr3_reg_710[6:0] <= 7'b0000000;
    p_addr_cast1_reg_755[6:0] <= 7'b0000000;
    p_addr2_cast1_reg_760[6:0] <= 7'b0000000;
    p_addr3_cast1_reg_766[6:0] <= 7'b0000000;
end



endmodule //gaussian_scalarized

