// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __gaussian_fptoui_32ns_64_6__HH__
#define __gaussian_fptoui_32ns_64_6__HH__
#include "ACMP_fptoui.h"
#include <systemc>

template<
    int ID,
    int NUM_STAGE,
    int din0_WIDTH,
    int dout_WIDTH>
SC_MODULE(gaussian_fptoui_32ns_64_6) {
    sc_core::sc_in_clk clk;
    sc_core::sc_in<sc_dt::sc_logic> reset;
    sc_core::sc_in<sc_dt::sc_logic> ce;
    sc_core::sc_in< sc_dt::sc_lv<din0_WIDTH> >   din0;
    sc_core::sc_out< sc_dt::sc_lv<dout_WIDTH> >   dout;



    ACMP_fptoui<ID, 6, din0_WIDTH, dout_WIDTH> ACMP_fptoui_U;

    SC_CTOR(gaussian_fptoui_32ns_64_6):  ACMP_fptoui_U ("ACMP_fptoui_U") {
        ACMP_fptoui_U.clk(clk);
        ACMP_fptoui_U.reset(reset);
        ACMP_fptoui_U.ce(ce);
        ACMP_fptoui_U.din0(din0);
        ACMP_fptoui_U.dout(dout);

    }

};

#endif //
