// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2013.2
// Copyright (C) 2013 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "gaussian_sep.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic gaussian_sep::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic gaussian_sep::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> gaussian_sep::ap_ST_st1_fsm_0 = "000000";
const sc_lv<6> gaussian_sep::ap_ST_st2_fsm_1 = "1";
const sc_lv<6> gaussian_sep::ap_ST_st3_fsm_2 = "10";
const sc_lv<6> gaussian_sep::ap_ST_st4_fsm_3 = "11";
const sc_lv<6> gaussian_sep::ap_ST_st5_fsm_4 = "100";
const sc_lv<6> gaussian_sep::ap_ST_st6_fsm_5 = "101";
const sc_lv<6> gaussian_sep::ap_ST_st7_fsm_6 = "110";
const sc_lv<6> gaussian_sep::ap_ST_st8_fsm_7 = "111";
const sc_lv<6> gaussian_sep::ap_ST_st9_fsm_8 = "1000";
const sc_lv<6> gaussian_sep::ap_ST_st10_fsm_9 = "1001";
const sc_lv<6> gaussian_sep::ap_ST_st11_fsm_10 = "1010";
const sc_lv<6> gaussian_sep::ap_ST_st12_fsm_11 = "1011";
const sc_lv<6> gaussian_sep::ap_ST_st13_fsm_12 = "1100";
const sc_lv<6> gaussian_sep::ap_ST_st14_fsm_13 = "1101";
const sc_lv<6> gaussian_sep::ap_ST_st15_fsm_14 = "1110";
const sc_lv<6> gaussian_sep::ap_ST_st16_fsm_15 = "1111";
const sc_lv<6> gaussian_sep::ap_ST_st17_fsm_16 = "10000";
const sc_lv<6> gaussian_sep::ap_ST_st18_fsm_17 = "10001";
const sc_lv<6> gaussian_sep::ap_ST_st19_fsm_18 = "10010";
const sc_lv<6> gaussian_sep::ap_ST_st20_fsm_19 = "10011";
const sc_lv<6> gaussian_sep::ap_ST_st21_fsm_20 = "10100";
const sc_lv<6> gaussian_sep::ap_ST_st22_fsm_21 = "10101";
const sc_lv<6> gaussian_sep::ap_ST_st23_fsm_22 = "10110";
const sc_lv<6> gaussian_sep::ap_ST_st24_fsm_23 = "10111";
const sc_lv<6> gaussian_sep::ap_ST_st25_fsm_24 = "11000";
const sc_lv<6> gaussian_sep::ap_ST_st26_fsm_25 = "11001";
const sc_lv<6> gaussian_sep::ap_ST_st27_fsm_26 = "11010";
const sc_lv<6> gaussian_sep::ap_ST_st28_fsm_27 = "11011";
const sc_lv<6> gaussian_sep::ap_ST_st29_fsm_28 = "11100";
const sc_lv<6> gaussian_sep::ap_ST_st30_fsm_29 = "11101";
const sc_lv<6> gaussian_sep::ap_ST_st31_fsm_30 = "11110";
const sc_lv<6> gaussian_sep::ap_ST_st32_fsm_31 = "11111";
const sc_lv<6> gaussian_sep::ap_ST_st33_fsm_32 = "100000";
const sc_lv<6> gaussian_sep::ap_ST_st34_fsm_33 = "100001";
const sc_lv<6> gaussian_sep::ap_ST_st35_fsm_34 = "100010";
const sc_lv<6> gaussian_sep::ap_ST_st36_fsm_35 = "100011";
const sc_lv<6> gaussian_sep::ap_ST_st37_fsm_36 = "100100";
const sc_lv<6> gaussian_sep::ap_ST_st38_fsm_37 = "100101";
const sc_lv<6> gaussian_sep::ap_ST_st39_fsm_38 = "100110";
const sc_lv<6> gaussian_sep::ap_ST_st40_fsm_39 = "100111";
const sc_lv<6> gaussian_sep::ap_ST_st41_fsm_40 = "101000";
const sc_lv<6> gaussian_sep::ap_ST_st42_fsm_41 = "101001";
const sc_lv<6> gaussian_sep::ap_ST_st43_fsm_42 = "101010";
const sc_lv<6> gaussian_sep::ap_ST_st44_fsm_43 = "101011";
const sc_lv<6> gaussian_sep::ap_ST_st45_fsm_44 = "101100";
const sc_lv<6> gaussian_sep::ap_ST_st46_fsm_45 = "101101";
const sc_lv<1> gaussian_sep::ap_const_lv1_0 = "0";
const sc_lv<11> gaussian_sep::ap_const_lv11_0 = "00000000000";
const sc_lv<32> gaussian_sep::ap_const_lv32_3E7C8F32 = "111110011111001000111100110010";
const sc_lv<32> gaussian_sep::ap_const_lv32_3F1B5159 = "111111000110110101000101011001";
const sc_lv<11> gaussian_sep::ap_const_lv11_2 = "10";
const sc_lv<11> gaussian_sep::ap_const_lv11_1 = "1";
const sc_lv<11> gaussian_sep::ap_const_lv11_436 = "10000110110";
const sc_lv<11> gaussian_sep::ap_const_lv11_780 = "11110000000";
const sc_lv<7> gaussian_sep::ap_const_lv7_0 = "0000000";
const sc_lv<11> gaussian_sep::ap_const_lv11_438 = "10000111000";
const sc_lv<11> gaussian_sep::ap_const_lv11_77E = "11101111110";

gaussian_sep::gaussian_sep(sc_module_name name) : sc_module(name), mVcdFile(0) {
    tmp_U = new gaussian_sep_tmp("tmp_U");
    tmp_U->clk(ap_clk);
    tmp_U->reset(ap_rst);
    tmp_U->address0(tmp_address0);
    tmp_U->ce0(tmp_ce0);
    tmp_U->we0(tmp_we0);
    tmp_U->d0(tmp_d0);
    tmp_U->q0(tmp_q0);
    tmp_U->address1(tmp_address1);
    tmp_U->ce1(tmp_ce1);
    tmp_U->q1(tmp_q1);
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1 = new gaussian_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("gaussian_fadd_32ns_32ns_32_5_full_dsp_U1");
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1->clk(ap_clk);
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1->reset(ap_rst);
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1->din0(grp_fu_171_p0);
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1->din1(grp_fu_171_p1);
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1->ce(grp_fu_171_ce);
    gaussian_fadd_32ns_32ns_32_5_full_dsp_U1->dout(grp_fu_171_p2);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2 = new gaussian_fmul_32ns_32ns_32_4_max_dsp<2,4,32,32,32>("gaussian_fmul_32ns_32ns_32_4_max_dsp_U2");
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2->clk(ap_clk);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2->reset(ap_rst);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2->din0(grp_fu_175_p0);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2->din1(grp_fu_175_p1);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2->ce(grp_fu_175_ce);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U2->dout(grp_fu_175_p2);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3 = new gaussian_fmul_32ns_32ns_32_4_max_dsp<3,4,32,32,32>("gaussian_fmul_32ns_32ns_32_4_max_dsp_U3");
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3->clk(ap_clk);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3->reset(ap_rst);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3->din0(grp_fu_180_p0);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3->din1(grp_fu_180_p1);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3->ce(grp_fu_180_ce);
    gaussian_fmul_32ns_32ns_32_4_max_dsp_U3->dout(grp_fu_180_p2);
    gaussian_fptoui_32ns_64_4_U4 = new gaussian_fptoui_32ns_64_4<4,4,32,64>("gaussian_fptoui_32ns_64_4_U4");
    gaussian_fptoui_32ns_64_4_U4->clk(ap_clk);
    gaussian_fptoui_32ns_64_4_U4->reset(ap_rst);
    gaussian_fptoui_32ns_64_4_U4->din0(grp_fu_187_p0);
    gaussian_fptoui_32ns_64_4_U4->ce(grp_fu_187_ce);
    gaussian_fptoui_32ns_64_4_U4->dout(grp_fu_187_p1);
    gaussian_sitofp_64ns_32_6_U5 = new gaussian_sitofp_64ns_32_6<5,6,64,32>("gaussian_sitofp_64ns_32_6_U5");
    gaussian_sitofp_64ns_32_6_U5->clk(ap_clk);
    gaussian_sitofp_64ns_32_6_U5->reset(ap_rst);
    gaussian_sitofp_64ns_32_6_U5->din0(grp_fu_190_p0);
    gaussian_sitofp_64ns_32_6_U5->ce(grp_fu_190_ce);
    gaussian_sitofp_64ns_32_6_U5->dout(grp_fu_190_p1);
    gaussian_sitofp_64ns_32_6_U6 = new gaussian_sitofp_64ns_32_6<6,6,64,32>("gaussian_sitofp_64ns_32_6_U6");
    gaussian_sitofp_64ns_32_6_U6->clk(ap_clk);
    gaussian_sitofp_64ns_32_6_U6->reset(ap_rst);
    gaussian_sitofp_64ns_32_6_U6->din0(grp_fu_193_p0);
    gaussian_sitofp_64ns_32_6_U6->ce(grp_fu_193_ce);
    gaussian_sitofp_64ns_32_6_U6->dout(grp_fu_193_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_418_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_fu_418_p2 );

    SC_METHOD(thread_exitcond1_fu_240_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar3_reg_124 );

    SC_METHOD(thread_exitcond2_fu_246_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( j_reg_136 );

    SC_METHOD(thread_exitcond3_fu_442_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( indvar_reg_159 );

    SC_METHOD(thread_exitcond_fu_418_p2);
    sensitive << ( ap_CS_fsm );
    sensitive << ( i_1_reg_147 );

    SC_METHOD(thread_grp_fu_171_ce);

    SC_METHOD(thread_grp_fu_171_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_205 );
    sensitive << ( reg_216 );

    SC_METHOD(thread_grp_fu_171_p1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_205 );
    sensitive << ( reg_211 );

    SC_METHOD(thread_grp_fu_175_ce);

    SC_METHOD(thread_grp_fu_175_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_q0 );
    sensitive << ( reg_200 );

    SC_METHOD(thread_grp_fu_175_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_180_ce);

    SC_METHOD(thread_grp_fu_180_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_q1 );
    sensitive << ( tmp_s_reg_606 );

    SC_METHOD(thread_grp_fu_180_p1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_grp_fu_187_ce);

    SC_METHOD(thread_grp_fu_187_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_216 );

    SC_METHOD(thread_grp_fu_190_ce);

    SC_METHOD(thread_grp_fu_190_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_6_fu_404_p1 );
    sensitive << ( tmp_12_fu_413_p1 );

    SC_METHOD(thread_grp_fu_193_ce);

    SC_METHOD(thread_grp_fu_193_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( in_load_1_reg_586 );

    SC_METHOD(thread_i_2_fu_424_p2);
    sensitive << ( i_1_reg_147 );

    SC_METHOD(thread_i_fu_234_p2);
    sensitive << ( indvar3_reg_124 );

    SC_METHOD(thread_in_r_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_3_fu_306_p1 );
    sensitive << ( tmp_25_fu_399_p1 );

    SC_METHOD(thread_in_r_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_16_fu_353_p1 );

    SC_METHOD(thread_in_r_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );

    SC_METHOD(thread_in_r_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );

    SC_METHOD(thread_j_1_fu_436_p2);
    sensitive << ( indvar_reg_159 );

    SC_METHOD(thread_j_2_fu_252_p2);
    sensitive << ( j_reg_136 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_29_reg_637 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_1_2_reg_662 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_p_addr1_fu_390_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );
    sensitive << ( p_addr_fu_380_p2 );

    SC_METHOD(thread_p_addr1_fu_390_p2);
    sensitive << ( tmp_5_trn5_cast_fu_258_p1 );
    sensitive << ( p_addr1_fu_390_p0 );

    SC_METHOD(thread_p_addr3_fu_333_p2);
    sensitive << ( p_shl2_cast_fu_318_p1 );
    sensitive << ( p_shl3_cast_fu_329_p1 );

    SC_METHOD(thread_p_addr4_fu_343_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );
    sensitive << ( p_addr3_fu_333_p2 );

    SC_METHOD(thread_p_addr4_fu_343_p2);
    sensitive << ( tmp_5_trn5_cast_fu_258_p1 );
    sensitive << ( p_addr4_fu_343_p0 );

    SC_METHOD(thread_p_addr6_fu_286_p2);
    sensitive << ( p_shl_cast_fu_270_p1 );
    sensitive << ( p_shl1_cast_fu_282_p1 );

    SC_METHOD(thread_p_addr7_fu_296_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );
    sensitive << ( p_addr6_fu_286_p2 );

    SC_METHOD(thread_p_addr7_fu_296_p2);
    sensitive << ( p_addr7_fu_296_p0 );
    sensitive << ( tmp_5_trn5_cast_fu_258_p1 );

    SC_METHOD(thread_p_addr_fu_380_p2);
    sensitive << ( p_shl4_cast_fu_365_p1 );
    sensitive << ( p_shl5_cast_fu_376_p1 );

    SC_METHOD(thread_p_shl1_cast_fu_282_p1);
    sensitive << ( tmp_2_fu_274_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_318_p1);
    sensitive << ( tmp_4_fu_311_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_329_p1);
    sensitive << ( tmp_5_fu_322_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_365_p1);
    sensitive << ( tmp_18_fu_358_p3 );

    SC_METHOD(thread_p_shl5_cast_fu_376_p1);
    sensitive << ( tmp_21_fu_369_p3 );

    SC_METHOD(thread_p_shl6_cast_fu_460_p1);
    sensitive << ( tmp_26_fu_452_p3 );

    SC_METHOD(thread_p_shl7_cast_fu_472_p1);
    sensitive << ( tmp_27_fu_464_p3 );

    SC_METHOD(thread_p_shl_cast_fu_270_p1);
    sensitive << ( tmp_1_fu_262_p3 );

    SC_METHOD(thread_tmp8_fu_430_p2);
    sensitive << ( indvar_reg_159 );

    SC_METHOD(thread_tmp_12_fu_413_p1);
    sensitive << ( reg_196 );

    SC_METHOD(thread_tmp_16_fu_353_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );
    sensitive << ( p_addr4_fu_343_p2 );

    SC_METHOD(thread_tmp_16_fu_353_p1);
    sensitive << ( tmp_16_fu_353_p0 );

    SC_METHOD(thread_tmp_16_trn_cast_fu_448_p1);
    sensitive << ( indvar_reg_159 );

    SC_METHOD(thread_tmp_18_fu_358_p3);
    sensitive << ( tmp_1_1_reg_542 );

    SC_METHOD(thread_tmp_18_trn_cast_fu_501_p1);
    sensitive << ( j_1_fu_436_p2 );

    SC_METHOD(thread_tmp_1_1_fu_228_p2);
    sensitive << ( indvar3_reg_124 );

    SC_METHOD(thread_tmp_1_2_fu_538_p1);
    sensitive << ( grp_fu_187_p1 );

    SC_METHOD(thread_tmp_1_fu_262_p3);
    sensitive << ( indvar3_reg_124 );

    SC_METHOD(thread_tmp_21_fu_369_p3);
    sensitive << ( tmp_1_1_reg_542 );

    SC_METHOD(thread_tmp_21_trn_cast_fu_520_p1);
    sensitive << ( tmp8_fu_430_p2 );

    SC_METHOD(thread_tmp_25_fu_399_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( p_addr1_reg_581 );

    SC_METHOD(thread_tmp_25_fu_399_p1);
    sensitive << ( tmp_25_fu_399_p0 );

    SC_METHOD(thread_tmp_26_fu_452_p3);
    sensitive << ( i_1_reg_147 );

    SC_METHOD(thread_tmp_27_fu_464_p3);
    sensitive << ( i_1_reg_147 );

    SC_METHOD(thread_tmp_28_fu_496_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );
    sensitive << ( tmp_addr2_fu_486_p2 );

    SC_METHOD(thread_tmp_28_fu_496_p1);
    sensitive << ( tmp_28_fu_496_p0 );

    SC_METHOD(thread_tmp_29_fu_515_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );
    sensitive << ( tmp_addr3_fu_505_p2 );

    SC_METHOD(thread_tmp_29_fu_515_p1);
    sensitive << ( tmp_29_fu_515_p0 );

    SC_METHOD(thread_tmp_2_fu_274_p3);
    sensitive << ( indvar3_reg_124 );

    SC_METHOD(thread_tmp_30_fu_533_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_addr4_reg_647 );

    SC_METHOD(thread_tmp_30_fu_533_p1);
    sensitive << ( tmp_30_fu_533_p0 );

    SC_METHOD(thread_tmp_3_fu_306_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );
    sensitive << ( p_addr7_fu_296_p2 );

    SC_METHOD(thread_tmp_3_fu_306_p1);
    sensitive << ( tmp_3_fu_306_p0 );

    SC_METHOD(thread_tmp_4_fu_311_p3);
    sensitive << ( i_reg_548 );

    SC_METHOD(thread_tmp_5_fu_322_p3);
    sensitive << ( i_reg_548 );

    SC_METHOD(thread_tmp_5_trn5_cast_fu_258_p1);
    sensitive << ( j_reg_136 );

    SC_METHOD(thread_tmp_6_fu_404_p1);
    sensitive << ( reg_196 );

    SC_METHOD(thread_tmp_addr1_cast_fu_482_p1);
    sensitive << ( tmp_addr1_fu_476_p2 );

    SC_METHOD(thread_tmp_addr1_fu_476_p2);
    sensitive << ( p_shl6_cast_fu_460_p1 );
    sensitive << ( p_shl7_cast_fu_472_p1 );

    SC_METHOD(thread_tmp_addr2_fu_486_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );
    sensitive << ( tmp_addr1_cast_fu_482_p1 );

    SC_METHOD(thread_tmp_addr2_fu_486_p2);
    sensitive << ( tmp_addr2_fu_486_p0 );
    sensitive << ( tmp_16_trn_cast_fu_448_p1 );

    SC_METHOD(thread_tmp_addr3_fu_505_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );
    sensitive << ( tmp_addr1_cast_fu_482_p1 );

    SC_METHOD(thread_tmp_addr3_fu_505_p2);
    sensitive << ( tmp_addr3_fu_505_p0 );
    sensitive << ( tmp_18_trn_cast_fu_501_p1 );

    SC_METHOD(thread_tmp_addr4_fu_524_p0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );
    sensitive << ( tmp_addr1_cast_fu_482_p1 );

    SC_METHOD(thread_tmp_addr4_fu_524_p2);
    sensitive << ( tmp_addr4_fu_524_p0 );
    sensitive << ( tmp_21_trn_cast_fu_520_p1 );

    SC_METHOD(thread_tmp_address0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_16_reg_571 );
    sensitive << ( tmp_28_fu_496_p1 );
    sensitive << ( tmp_30_fu_533_p1 );

    SC_METHOD(thread_tmp_address1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_29_fu_515_p1 );

    SC_METHOD(thread_tmp_ce0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );

    SC_METHOD(thread_tmp_ce1);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond3_fu_442_p2 );

    SC_METHOD(thread_tmp_d0);
    sensitive << ( ap_CS_fsm );
    sensitive << ( reg_216 );

    SC_METHOD(thread_tmp_we0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_246_p2 );
    sensitive << ( exitcond3_fu_442_p2 );
    sensitive << ( exitcond1_fu_240_p2 );
    sensitive << ( exitcond_fu_418_p2 );

    ap_CS_fsm = "000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "gaussian_sep_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    const char* dump_vcd = std::getenv("AP_WRITE_VCD");
    if (dump_vcd && string(dump_vcd) == "1" ) {
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, in_r_address0, "(port)in_r_address0");
    sc_trace(mVcdFile, in_r_ce0, "(port)in_r_ce0");
    sc_trace(mVcdFile, in_r_q0, "(port)in_r_q0");
    sc_trace(mVcdFile, in_r_address1, "(port)in_r_address1");
    sc_trace(mVcdFile, in_r_ce1, "(port)in_r_ce1");
    sc_trace(mVcdFile, in_r_q1, "(port)in_r_q1");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, tmp_address0, "tmp_address0");
    sc_trace(mVcdFile, tmp_ce0, "tmp_ce0");
    sc_trace(mVcdFile, tmp_we0, "tmp_we0");
    sc_trace(mVcdFile, tmp_d0, "tmp_d0");
    sc_trace(mVcdFile, tmp_q0, "tmp_q0");
    sc_trace(mVcdFile, tmp_address1, "tmp_address1");
    sc_trace(mVcdFile, tmp_ce1, "tmp_ce1");
    sc_trace(mVcdFile, tmp_q1, "tmp_q1");
    sc_trace(mVcdFile, reg_196, "reg_196");
    sc_trace(mVcdFile, grp_fu_190_p1, "grp_fu_190_p1");
    sc_trace(mVcdFile, reg_200, "reg_200");
    sc_trace(mVcdFile, grp_fu_175_p2, "grp_fu_175_p2");
    sc_trace(mVcdFile, reg_205, "reg_205");
    sc_trace(mVcdFile, grp_fu_180_p2, "grp_fu_180_p2");
    sc_trace(mVcdFile, reg_211, "reg_211");
    sc_trace(mVcdFile, grp_fu_171_p2, "grp_fu_171_p2");
    sc_trace(mVcdFile, reg_216, "reg_216");
    sc_trace(mVcdFile, tmp_1_1_fu_228_p2, "tmp_1_1_fu_228_p2");
    sc_trace(mVcdFile, tmp_1_1_reg_542, "tmp_1_1_reg_542");
    sc_trace(mVcdFile, i_fu_234_p2, "i_fu_234_p2");
    sc_trace(mVcdFile, i_reg_548, "i_reg_548");
    sc_trace(mVcdFile, j_2_fu_252_p2, "j_2_fu_252_p2");
    sc_trace(mVcdFile, j_2_reg_561, "j_2_reg_561");
    sc_trace(mVcdFile, exitcond2_fu_246_p2, "exitcond2_fu_246_p2");
    sc_trace(mVcdFile, tmp_16_fu_353_p1, "tmp_16_fu_353_p1");
    sc_trace(mVcdFile, tmp_16_reg_571, "tmp_16_reg_571");
    sc_trace(mVcdFile, p_addr1_fu_390_p2, "p_addr1_fu_390_p2");
    sc_trace(mVcdFile, p_addr1_reg_581, "p_addr1_reg_581");
    sc_trace(mVcdFile, in_load_1_reg_586, "in_load_1_reg_586");
    sc_trace(mVcdFile, tmp_6_fu_404_p1, "tmp_6_fu_404_p1");
    sc_trace(mVcdFile, grp_fu_193_p1, "grp_fu_193_p1");
    sc_trace(mVcdFile, tmp_s_reg_606, "tmp_s_reg_606");
    sc_trace(mVcdFile, tmp_12_fu_413_p1, "tmp_12_fu_413_p1");
    sc_trace(mVcdFile, i_2_fu_424_p2, "i_2_fu_424_p2");
    sc_trace(mVcdFile, i_2_reg_619, "i_2_reg_619");
    sc_trace(mVcdFile, j_1_fu_436_p2, "j_1_fu_436_p2");
    sc_trace(mVcdFile, j_1_reg_624, "j_1_reg_624");
    sc_trace(mVcdFile, exitcond3_fu_442_p2, "exitcond3_fu_442_p2");
    sc_trace(mVcdFile, tmp_29_fu_515_p1, "tmp_29_fu_515_p1");
    sc_trace(mVcdFile, tmp_29_reg_637, "tmp_29_reg_637");
    sc_trace(mVcdFile, tmp_addr4_fu_524_p2, "tmp_addr4_fu_524_p2");
    sc_trace(mVcdFile, tmp_addr4_reg_647, "tmp_addr4_reg_647");
    sc_trace(mVcdFile, tmp_1_2_fu_538_p1, "tmp_1_2_fu_538_p1");
    sc_trace(mVcdFile, tmp_1_2_reg_662, "tmp_1_2_reg_662");
    sc_trace(mVcdFile, indvar3_reg_124, "indvar3_reg_124");
    sc_trace(mVcdFile, j_reg_136, "j_reg_136");
    sc_trace(mVcdFile, exitcond1_fu_240_p2, "exitcond1_fu_240_p2");
    sc_trace(mVcdFile, i_1_reg_147, "i_1_reg_147");
    sc_trace(mVcdFile, indvar_reg_159, "indvar_reg_159");
    sc_trace(mVcdFile, exitcond_fu_418_p2, "exitcond_fu_418_p2");
    sc_trace(mVcdFile, tmp_3_fu_306_p1, "tmp_3_fu_306_p1");
    sc_trace(mVcdFile, tmp_25_fu_399_p1, "tmp_25_fu_399_p1");
    sc_trace(mVcdFile, tmp_28_fu_496_p1, "tmp_28_fu_496_p1");
    sc_trace(mVcdFile, tmp_30_fu_533_p1, "tmp_30_fu_533_p1");
    sc_trace(mVcdFile, grp_fu_171_p0, "grp_fu_171_p0");
    sc_trace(mVcdFile, grp_fu_171_p1, "grp_fu_171_p1");
    sc_trace(mVcdFile, grp_fu_175_p0, "grp_fu_175_p0");
    sc_trace(mVcdFile, grp_fu_175_p1, "grp_fu_175_p1");
    sc_trace(mVcdFile, grp_fu_180_p0, "grp_fu_180_p0");
    sc_trace(mVcdFile, grp_fu_180_p1, "grp_fu_180_p1");
    sc_trace(mVcdFile, grp_fu_187_p0, "grp_fu_187_p0");
    sc_trace(mVcdFile, grp_fu_190_p0, "grp_fu_190_p0");
    sc_trace(mVcdFile, grp_fu_193_p0, "grp_fu_193_p0");
    sc_trace(mVcdFile, tmp_1_fu_262_p3, "tmp_1_fu_262_p3");
    sc_trace(mVcdFile, tmp_2_fu_274_p3, "tmp_2_fu_274_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_270_p1, "p_shl_cast_fu_270_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_282_p1, "p_shl1_cast_fu_282_p1");
    sc_trace(mVcdFile, p_addr6_fu_286_p2, "p_addr6_fu_286_p2");
    sc_trace(mVcdFile, p_addr7_fu_296_p0, "p_addr7_fu_296_p0");
    sc_trace(mVcdFile, tmp_5_trn5_cast_fu_258_p1, "tmp_5_trn5_cast_fu_258_p1");
    sc_trace(mVcdFile, p_addr7_fu_296_p2, "p_addr7_fu_296_p2");
    sc_trace(mVcdFile, tmp_3_fu_306_p0, "tmp_3_fu_306_p0");
    sc_trace(mVcdFile, tmp_4_fu_311_p3, "tmp_4_fu_311_p3");
    sc_trace(mVcdFile, tmp_5_fu_322_p3, "tmp_5_fu_322_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_318_p1, "p_shl2_cast_fu_318_p1");
    sc_trace(mVcdFile, p_shl3_cast_fu_329_p1, "p_shl3_cast_fu_329_p1");
    sc_trace(mVcdFile, p_addr3_fu_333_p2, "p_addr3_fu_333_p2");
    sc_trace(mVcdFile, p_addr4_fu_343_p0, "p_addr4_fu_343_p0");
    sc_trace(mVcdFile, p_addr4_fu_343_p2, "p_addr4_fu_343_p2");
    sc_trace(mVcdFile, tmp_16_fu_353_p0, "tmp_16_fu_353_p0");
    sc_trace(mVcdFile, tmp_18_fu_358_p3, "tmp_18_fu_358_p3");
    sc_trace(mVcdFile, tmp_21_fu_369_p3, "tmp_21_fu_369_p3");
    sc_trace(mVcdFile, p_shl4_cast_fu_365_p1, "p_shl4_cast_fu_365_p1");
    sc_trace(mVcdFile, p_shl5_cast_fu_376_p1, "p_shl5_cast_fu_376_p1");
    sc_trace(mVcdFile, p_addr_fu_380_p2, "p_addr_fu_380_p2");
    sc_trace(mVcdFile, p_addr1_fu_390_p0, "p_addr1_fu_390_p0");
    sc_trace(mVcdFile, tmp_25_fu_399_p0, "tmp_25_fu_399_p0");
    sc_trace(mVcdFile, tmp_26_fu_452_p3, "tmp_26_fu_452_p3");
    sc_trace(mVcdFile, tmp_27_fu_464_p3, "tmp_27_fu_464_p3");
    sc_trace(mVcdFile, p_shl6_cast_fu_460_p1, "p_shl6_cast_fu_460_p1");
    sc_trace(mVcdFile, p_shl7_cast_fu_472_p1, "p_shl7_cast_fu_472_p1");
    sc_trace(mVcdFile, tmp_addr1_fu_476_p2, "tmp_addr1_fu_476_p2");
    sc_trace(mVcdFile, tmp_addr2_fu_486_p0, "tmp_addr2_fu_486_p0");
    sc_trace(mVcdFile, tmp_addr1_cast_fu_482_p1, "tmp_addr1_cast_fu_482_p1");
    sc_trace(mVcdFile, tmp_16_trn_cast_fu_448_p1, "tmp_16_trn_cast_fu_448_p1");
    sc_trace(mVcdFile, tmp_addr2_fu_486_p2, "tmp_addr2_fu_486_p2");
    sc_trace(mVcdFile, tmp_28_fu_496_p0, "tmp_28_fu_496_p0");
    sc_trace(mVcdFile, tmp_addr3_fu_505_p0, "tmp_addr3_fu_505_p0");
    sc_trace(mVcdFile, tmp_18_trn_cast_fu_501_p1, "tmp_18_trn_cast_fu_501_p1");
    sc_trace(mVcdFile, tmp_addr3_fu_505_p2, "tmp_addr3_fu_505_p2");
    sc_trace(mVcdFile, tmp_29_fu_515_p0, "tmp_29_fu_515_p0");
    sc_trace(mVcdFile, tmp8_fu_430_p2, "tmp8_fu_430_p2");
    sc_trace(mVcdFile, tmp_addr4_fu_524_p0, "tmp_addr4_fu_524_p0");
    sc_trace(mVcdFile, tmp_21_trn_cast_fu_520_p1, "tmp_21_trn_cast_fu_520_p1");
    sc_trace(mVcdFile, tmp_30_fu_533_p0, "tmp_30_fu_533_p0");
    sc_trace(mVcdFile, grp_fu_187_p1, "grp_fu_187_p1");
    sc_trace(mVcdFile, grp_fu_171_ce, "grp_fu_171_ce");
    sc_trace(mVcdFile, grp_fu_175_ce, "grp_fu_175_ce");
    sc_trace(mVcdFile, grp_fu_180_ce, "grp_fu_180_ce");
    sc_trace(mVcdFile, grp_fu_187_ce, "grp_fu_187_ce");
    sc_trace(mVcdFile, grp_fu_190_ce, "grp_fu_190_ce");
    sc_trace(mVcdFile, grp_fu_193_ce, "grp_fu_193_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");

    }
}

gaussian_sep::~gaussian_sep() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete tmp_U;
    delete gaussian_fadd_32ns_32ns_32_5_full_dsp_U1;
    delete gaussian_fmul_32ns_32ns_32_4_max_dsp_U2;
    delete gaussian_fmul_32ns_32ns_32_4_max_dsp_U3;
    delete gaussian_fptoui_32ns_64_4_U4;
    delete gaussian_sitofp_64ns_32_6_U5;
    delete gaussian_sitofp_64ns_32_6_U6;
}

void gaussian_sep::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st27_fsm_26, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_442_p2.read()))) {
        i_1_reg_147 = i_2_reg_619.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_240_p2.read()))) {
        i_1_reg_147 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(exitcond2_fu_246_p2.read(), ap_const_lv1_0))) {
        indvar3_reg_124 = i_reg_548.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar3_reg_124 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,6,6>(ap_ST_st26_fsm_25, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_418_p2.read()))) {
        indvar_reg_159 = ap_const_lv11_0;
    } else if (esl_seteq<1,6,6>(ap_ST_st46_fsm_45, ap_CS_fsm.read())) {
        indvar_reg_159 = j_1_reg_624.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_240_p2.read()))) {
        j_reg_136 = ap_const_lv11_0;
    } else if (esl_seteq<1,6,6>(ap_ST_st25_fsm_24, ap_CS_fsm.read())) {
        j_reg_136 = j_2_reg_561.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st26_fsm_25, ap_CS_fsm.read())) {
        i_2_reg_619 = i_2_fu_424_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st2_fsm_1, ap_CS_fsm.read())) {
        i_reg_548 = i_fu_234_p2.read();
        tmp_1_1_reg_542 = tmp_1_1_fu_228_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        in_load_1_reg_586 = in_r_q1.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st27_fsm_26, ap_CS_fsm.read())) {
        j_1_reg_624 = j_1_fu_436_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        j_2_reg_561 = j_2_fu_252_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && esl_seteq<1,1,1>(exitcond2_fu_246_p2.read(), ap_const_lv1_0))) {
        p_addr1_reg_581 = p_addr1_fu_390_p2.read();
        tmp_16_reg_571 = tmp_16_fu_353_p1.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st4_fsm_3, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st5_fsm_4, ap_CS_fsm.read()))) {
        reg_196 = in_r_q0.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st15_fsm_14, ap_CS_fsm.read()))) {
        reg_200 = grp_fu_190_p1.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st36_fsm_35, ap_CS_fsm.read()))) {
        reg_205 = grp_fu_175_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st14_fsm_13, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st31_fsm_30, ap_CS_fsm.read()))) {
        reg_211 = grp_fu_180_p2.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st19_fsm_18, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st36_fsm_35, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st24_fsm_23, ap_CS_fsm.read()) || esl_seteq<1,6,6>(ap_ST_st41_fsm_40, ap_CS_fsm.read()))) {
        reg_216 = grp_fu_171_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st45_fsm_44, ap_CS_fsm.read())) {
        tmp_1_2_reg_662 = tmp_1_2_fu_538_p1.read();
    }
    if ((esl_seteq<1,6,6>(ap_ST_st27_fsm_26, ap_CS_fsm.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_442_p2.read()))) {
        tmp_29_reg_637 = tmp_29_fu_515_p1.read();
        tmp_addr4_reg_647 = tmp_addr4_fu_524_p2.read();
    }
    if (esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) {
        tmp_s_reg_606 = grp_fu_193_p1.read();
    }
}

void gaussian_sep::thread_ap_done() {
    if (((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read())) || 
         (esl_seteq<1,6,6>(ap_ST_st26_fsm_25, ap_CS_fsm.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_418_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void gaussian_sep::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,6,6>(ap_ST_st1_fsm_0, ap_CS_fsm.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void gaussian_sep::thread_ap_ready() {
    if ((esl_seteq<1,6,6>(ap_ST_st26_fsm_25, ap_CS_fsm.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_418_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void gaussian_sep::thread_exitcond1_fu_240_p2() {
    exitcond1_fu_240_p2 = (!indvar3_reg_124.read().is_01() || !ap_const_lv11_436.is_01())? sc_lv<1>(): sc_lv<1>(indvar3_reg_124.read() == ap_const_lv11_436);
}

void gaussian_sep::thread_exitcond2_fu_246_p2() {
    exitcond2_fu_246_p2 = (!j_reg_136.read().is_01() || !ap_const_lv11_780.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_136.read() == ap_const_lv11_780);
}

void gaussian_sep::thread_exitcond3_fu_442_p2() {
    exitcond3_fu_442_p2 = (!indvar_reg_159.read().is_01() || !ap_const_lv11_77E.is_01())? sc_lv<1>(): sc_lv<1>(indvar_reg_159.read() == ap_const_lv11_77E);
}

void gaussian_sep::thread_exitcond_fu_418_p2() {
    exitcond_fu_418_p2 = (!i_1_reg_147.read().is_01() || !ap_const_lv11_438.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_147.read() == ap_const_lv11_438);
}

void gaussian_sep::thread_grp_fu_171_ce() {
    grp_fu_171_ce = ap_const_logic_1;
}

void gaussian_sep::thread_grp_fu_171_p0() {
    if ((esl_seteq<1,6,6>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st37_fsm_36, ap_CS_fsm.read()))) {
        grp_fu_171_p0 = reg_216.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st32_fsm_31, ap_CS_fsm.read()))) {
        grp_fu_171_p0 = reg_205.read();
    } else {
        grp_fu_171_p0 = reg_216.read();
    }
}

void gaussian_sep::thread_grp_fu_171_p1() {
    if ((esl_seteq<1,6,6>(ap_ST_st20_fsm_19, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st37_fsm_36, ap_CS_fsm.read()))) {
        grp_fu_171_p1 = reg_205.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st15_fsm_14, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st32_fsm_31, ap_CS_fsm.read()))) {
        grp_fu_171_p1 = reg_211.read();
    } else {
        grp_fu_171_p1 = reg_211.read();
    }
}

void gaussian_sep::thread_grp_fu_175_ce() {
    grp_fu_175_ce = ap_const_logic_1;
}

void gaussian_sep::thread_grp_fu_175_p0() {
    if ((esl_seteq<1,6,6>(ap_ST_st28_fsm_27, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st33_fsm_32, ap_CS_fsm.read()))) {
        grp_fu_175_p0 = tmp_q0.read();
    } else if ((esl_seteq<1,6,6>(ap_ST_st11_fsm_10, ap_CS_fsm.read()) || 
                esl_seteq<1,6,6>(ap_ST_st16_fsm_15, ap_CS_fsm.read()))) {
        grp_fu_175_p0 = reg_200.read();
    } else {
        grp_fu_175_p0 = reg_200.read();
    }
}

void gaussian_sep::thread_grp_fu_175_p1() {
    grp_fu_175_p1 = ap_const_lv32_3E7C8F32;
}

void gaussian_sep::thread_grp_fu_180_ce() {
    grp_fu_180_ce = ap_const_logic_1;
}

void gaussian_sep::thread_grp_fu_180_p0() {
    if (esl_seteq<1,6,6>(ap_ST_st28_fsm_27, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_q1.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st11_fsm_10, ap_CS_fsm.read())) {
        grp_fu_180_p0 = tmp_s_reg_606.read();
    } else {
        grp_fu_180_p0 = tmp_s_reg_606.read();
    }
}

void gaussian_sep::thread_grp_fu_180_p1() {
    grp_fu_180_p1 = ap_const_lv32_3F1B5159;
}

void gaussian_sep::thread_grp_fu_187_ce() {
    grp_fu_187_ce = ap_const_logic_1;
}

void gaussian_sep::thread_grp_fu_187_p0() {
    grp_fu_187_p0 = reg_216.read();
}

void gaussian_sep::thread_grp_fu_190_ce() {
    grp_fu_190_ce = ap_const_logic_1;
}

void gaussian_sep::thread_grp_fu_190_p0() {
    if (esl_seteq<1,6,6>(ap_ST_st10_fsm_9, ap_CS_fsm.read())) {
        grp_fu_190_p0 = tmp_12_fu_413_p1.read();
    } else if (esl_seteq<1,6,6>(ap_ST_st5_fsm_4, ap_CS_fsm.read())) {
        grp_fu_190_p0 = tmp_6_fu_404_p1.read();
    } else {
        grp_fu_190_p0 = tmp_12_fu_413_p1.read();
    }
}

void gaussian_sep::thread_grp_fu_193_ce() {
    grp_fu_193_ce = ap_const_logic_1;
}

void gaussian_sep::thread_grp_fu_193_p0() {
    grp_fu_193_p0 = esl_zext<64,16>(in_load_1_reg_586.read());
}

void gaussian_sep::thread_i_2_fu_424_p2() {
    i_2_fu_424_p2 = (!i_1_reg_147.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_bigint<11>(i_1_reg_147.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void gaussian_sep::thread_i_fu_234_p2() {
    i_fu_234_p2 = (!indvar3_reg_124.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_bigint<11>(indvar3_reg_124.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void gaussian_sep::thread_in_r_address0() {
    if (esl_seteq<1,6,6>(ap_ST_st4_fsm_3, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_25_fu_399_p1.read());
    } else if (esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read())) {
        in_r_address0 =  (sc_lv<21>) (tmp_3_fu_306_p1.read());
    } else {
        in_r_address0 =  (sc_lv<21>) (tmp_25_fu_399_p1.read());
    }
}

void gaussian_sep::thread_in_r_address1() {
    in_r_address1 =  (sc_lv<21>) (tmp_16_fu_353_p1.read());
}

void gaussian_sep::thread_in_r_ce0() {
    if ((esl_seteq<1,6,6>(ap_ST_st4_fsm_3, ap_CS_fsm.read()) || 
         (esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(exitcond2_fu_246_p2.read(), ap_const_lv1_0)))) {
        in_r_ce0 = ap_const_logic_1;
    } else {
        in_r_ce0 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_in_r_ce1() {
    if ((esl_seteq<1,6,6>(ap_ST_st3_fsm_2, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_246_p2.read(), ap_const_lv1_0))) {
        in_r_ce1 = ap_const_logic_1;
    } else {
        in_r_ce1 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_j_1_fu_436_p2() {
    j_1_fu_436_p2 = (!indvar_reg_159.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_bigint<11>(indvar_reg_159.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void gaussian_sep::thread_j_2_fu_252_p2() {
    j_2_fu_252_p2 = (!j_reg_136.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_bigint<11>(j_reg_136.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void gaussian_sep::thread_out_r_address0() {
    out_r_address0 =  (sc_lv<21>) (tmp_29_reg_637.read());
}

void gaussian_sep::thread_out_r_ce0() {
    if (esl_seteq<1,6,6>(ap_ST_st46_fsm_45, ap_CS_fsm.read())) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_out_r_d0() {
    out_r_d0 = tmp_1_2_reg_662.read();
}

void gaussian_sep::thread_out_r_we0() {
    if ((esl_seteq<1,6,6>(ap_ST_st46_fsm_45, ap_CS_fsm.read()))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_p_addr1_fu_390_p0() {
    p_addr1_fu_390_p0 = esl_sext<24,23>(p_addr_fu_380_p2.read());
}

void gaussian_sep::thread_p_addr1_fu_390_p2() {
    p_addr1_fu_390_p2 = (!p_addr1_fu_390_p0.read().is_01() || !tmp_5_trn5_cast_fu_258_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(p_addr1_fu_390_p0.read()) + sc_biguint<24>(tmp_5_trn5_cast_fu_258_p1.read()));
}

void gaussian_sep::thread_p_addr3_fu_333_p2() {
    p_addr3_fu_333_p2 = (!p_shl2_cast_fu_318_p1.read().is_01() || !p_shl3_cast_fu_329_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(p_shl2_cast_fu_318_p1.read()) - sc_biguint<23>(p_shl3_cast_fu_329_p1.read()));
}

void gaussian_sep::thread_p_addr4_fu_343_p0() {
    p_addr4_fu_343_p0 = esl_sext<24,23>(p_addr3_fu_333_p2.read());
}

void gaussian_sep::thread_p_addr4_fu_343_p2() {
    p_addr4_fu_343_p2 = (!p_addr4_fu_343_p0.read().is_01() || !tmp_5_trn5_cast_fu_258_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(p_addr4_fu_343_p0.read()) + sc_biguint<24>(tmp_5_trn5_cast_fu_258_p1.read()));
}

void gaussian_sep::thread_p_addr6_fu_286_p2() {
    p_addr6_fu_286_p2 = (!p_shl_cast_fu_270_p1.read().is_01() || !p_shl1_cast_fu_282_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(p_shl_cast_fu_270_p1.read()) - sc_biguint<23>(p_shl1_cast_fu_282_p1.read()));
}

void gaussian_sep::thread_p_addr7_fu_296_p0() {
    p_addr7_fu_296_p0 = esl_sext<24,23>(p_addr6_fu_286_p2.read());
}

void gaussian_sep::thread_p_addr7_fu_296_p2() {
    p_addr7_fu_296_p2 = (!p_addr7_fu_296_p0.read().is_01() || !tmp_5_trn5_cast_fu_258_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(p_addr7_fu_296_p0.read()) + sc_biguint<24>(tmp_5_trn5_cast_fu_258_p1.read()));
}

void gaussian_sep::thread_p_addr_fu_380_p2() {
    p_addr_fu_380_p2 = (!p_shl4_cast_fu_365_p1.read().is_01() || !p_shl5_cast_fu_376_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(p_shl4_cast_fu_365_p1.read()) - sc_biguint<23>(p_shl5_cast_fu_376_p1.read()));
}

void gaussian_sep::thread_p_shl1_cast_fu_282_p1() {
    p_shl1_cast_fu_282_p1 = esl_zext<23,18>(tmp_2_fu_274_p3.read());
}

void gaussian_sep::thread_p_shl2_cast_fu_318_p1() {
    p_shl2_cast_fu_318_p1 = esl_zext<23,22>(tmp_4_fu_311_p3.read());
}

void gaussian_sep::thread_p_shl3_cast_fu_329_p1() {
    p_shl3_cast_fu_329_p1 = esl_zext<23,18>(tmp_5_fu_322_p3.read());
}

void gaussian_sep::thread_p_shl4_cast_fu_365_p1() {
    p_shl4_cast_fu_365_p1 = esl_zext<23,22>(tmp_18_fu_358_p3.read());
}

void gaussian_sep::thread_p_shl5_cast_fu_376_p1() {
    p_shl5_cast_fu_376_p1 = esl_zext<23,18>(tmp_21_fu_369_p3.read());
}

void gaussian_sep::thread_p_shl6_cast_fu_460_p1() {
    p_shl6_cast_fu_460_p1 = esl_zext<23,22>(tmp_26_fu_452_p3.read());
}

void gaussian_sep::thread_p_shl7_cast_fu_472_p1() {
    p_shl7_cast_fu_472_p1 = esl_zext<23,18>(tmp_27_fu_464_p3.read());
}

void gaussian_sep::thread_p_shl_cast_fu_270_p1() {
    p_shl_cast_fu_270_p1 = esl_zext<23,22>(tmp_1_fu_262_p3.read());
}

void gaussian_sep::thread_tmp8_fu_430_p2() {
    tmp8_fu_430_p2 = (!indvar_reg_159.read().is_01() || !ap_const_lv11_2.is_01())? sc_lv<11>(): (sc_bigint<11>(indvar_reg_159.read()) + sc_biguint<11>(ap_const_lv11_2));
}

void gaussian_sep::thread_tmp_12_fu_413_p1() {
    tmp_12_fu_413_p1 = esl_zext<64,16>(reg_196.read());
}

void gaussian_sep::thread_tmp_16_fu_353_p0() {
    tmp_16_fu_353_p0 = esl_sext<32,24>(p_addr4_fu_343_p2.read());
}

void gaussian_sep::thread_tmp_16_fu_353_p1() {
    tmp_16_fu_353_p1 = esl_zext<64,32>(tmp_16_fu_353_p0.read());
}

void gaussian_sep::thread_tmp_16_trn_cast_fu_448_p1() {
    tmp_16_trn_cast_fu_448_p1 = esl_zext<24,11>(indvar_reg_159.read());
}

void gaussian_sep::thread_tmp_18_fu_358_p3() {
    tmp_18_fu_358_p3 = esl_concat<11,11>(tmp_1_1_reg_542.read(), ap_const_lv11_0);
}

void gaussian_sep::thread_tmp_18_trn_cast_fu_501_p1() {
    tmp_18_trn_cast_fu_501_p1 = esl_zext<24,11>(j_1_fu_436_p2.read());
}

void gaussian_sep::thread_tmp_1_1_fu_228_p2() {
    tmp_1_1_fu_228_p2 = (!indvar3_reg_124.read().is_01() || !ap_const_lv11_2.is_01())? sc_lv<11>(): (sc_bigint<11>(indvar3_reg_124.read()) + sc_biguint<11>(ap_const_lv11_2));
}

void gaussian_sep::thread_tmp_1_2_fu_538_p1() {
    tmp_1_2_fu_538_p1 = grp_fu_187_p1.read().range(16-1, 0);
}

void gaussian_sep::thread_tmp_1_fu_262_p3() {
    tmp_1_fu_262_p3 = esl_concat<11,11>(indvar3_reg_124.read(), ap_const_lv11_0);
}

void gaussian_sep::thread_tmp_21_fu_369_p3() {
    tmp_21_fu_369_p3 = esl_concat<11,7>(tmp_1_1_reg_542.read(), ap_const_lv7_0);
}

void gaussian_sep::thread_tmp_21_trn_cast_fu_520_p1() {
    tmp_21_trn_cast_fu_520_p1 = esl_zext<24,11>(tmp8_fu_430_p2.read());
}

void gaussian_sep::thread_tmp_25_fu_399_p0() {
    tmp_25_fu_399_p0 = esl_sext<32,24>(p_addr1_reg_581.read());
}

void gaussian_sep::thread_tmp_25_fu_399_p1() {
    tmp_25_fu_399_p1 = esl_zext<64,32>(tmp_25_fu_399_p0.read());
}

void gaussian_sep::thread_tmp_26_fu_452_p3() {
    tmp_26_fu_452_p3 = esl_concat<11,11>(i_1_reg_147.read(), ap_const_lv11_0);
}

void gaussian_sep::thread_tmp_27_fu_464_p3() {
    tmp_27_fu_464_p3 = esl_concat<11,7>(i_1_reg_147.read(), ap_const_lv7_0);
}

void gaussian_sep::thread_tmp_28_fu_496_p0() {
    tmp_28_fu_496_p0 = esl_sext<32,24>(tmp_addr2_fu_486_p2.read());
}

void gaussian_sep::thread_tmp_28_fu_496_p1() {
    tmp_28_fu_496_p1 = esl_zext<64,32>(tmp_28_fu_496_p0.read());
}

void gaussian_sep::thread_tmp_29_fu_515_p0() {
    tmp_29_fu_515_p0 = esl_sext<32,24>(tmp_addr3_fu_505_p2.read());
}

void gaussian_sep::thread_tmp_29_fu_515_p1() {
    tmp_29_fu_515_p1 = esl_zext<64,32>(tmp_29_fu_515_p0.read());
}

void gaussian_sep::thread_tmp_2_fu_274_p3() {
    tmp_2_fu_274_p3 = esl_concat<11,7>(indvar3_reg_124.read(), ap_const_lv7_0);
}

void gaussian_sep::thread_tmp_30_fu_533_p0() {
    tmp_30_fu_533_p0 = esl_sext<32,24>(tmp_addr4_reg_647.read());
}

void gaussian_sep::thread_tmp_30_fu_533_p1() {
    tmp_30_fu_533_p1 = esl_zext<64,32>(tmp_30_fu_533_p0.read());
}

void gaussian_sep::thread_tmp_3_fu_306_p0() {
    tmp_3_fu_306_p0 = esl_sext<32,24>(p_addr7_fu_296_p2.read());
}

void gaussian_sep::thread_tmp_3_fu_306_p1() {
    tmp_3_fu_306_p1 = esl_zext<64,32>(tmp_3_fu_306_p0.read());
}

void gaussian_sep::thread_tmp_4_fu_311_p3() {
    tmp_4_fu_311_p3 = esl_concat<11,11>(i_reg_548.read(), ap_const_lv11_0);
}

void gaussian_sep::thread_tmp_5_fu_322_p3() {
    tmp_5_fu_322_p3 = esl_concat<11,7>(i_reg_548.read(), ap_const_lv7_0);
}

void gaussian_sep::thread_tmp_5_trn5_cast_fu_258_p1() {
    tmp_5_trn5_cast_fu_258_p1 = esl_zext<24,11>(j_reg_136.read());
}

void gaussian_sep::thread_tmp_6_fu_404_p1() {
    tmp_6_fu_404_p1 = esl_zext<64,16>(reg_196.read());
}

void gaussian_sep::thread_tmp_addr1_cast_fu_482_p1() {
    tmp_addr1_cast_fu_482_p1 = esl_sext<24,23>(tmp_addr1_fu_476_p2.read());
}

void gaussian_sep::thread_tmp_addr1_fu_476_p2() {
    tmp_addr1_fu_476_p2 = (!p_shl6_cast_fu_460_p1.read().is_01() || !p_shl7_cast_fu_472_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(p_shl6_cast_fu_460_p1.read()) - sc_biguint<23>(p_shl7_cast_fu_472_p1.read()));
}

void gaussian_sep::thread_tmp_addr2_fu_486_p0() {
    tmp_addr2_fu_486_p0 = tmp_addr1_cast_fu_482_p1.read();
}

void gaussian_sep::thread_tmp_addr2_fu_486_p2() {
    tmp_addr2_fu_486_p2 = (!tmp_addr2_fu_486_p0.read().is_01() || !tmp_16_trn_cast_fu_448_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(tmp_addr2_fu_486_p0.read()) + sc_biguint<24>(tmp_16_trn_cast_fu_448_p1.read()));
}

void gaussian_sep::thread_tmp_addr3_fu_505_p0() {
    tmp_addr3_fu_505_p0 = tmp_addr1_cast_fu_482_p1.read();
}

void gaussian_sep::thread_tmp_addr3_fu_505_p2() {
    tmp_addr3_fu_505_p2 = (!tmp_addr3_fu_505_p0.read().is_01() || !tmp_18_trn_cast_fu_501_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(tmp_addr3_fu_505_p0.read()) + sc_biguint<24>(tmp_18_trn_cast_fu_501_p1.read()));
}

void gaussian_sep::thread_tmp_addr4_fu_524_p0() {
    tmp_addr4_fu_524_p0 = tmp_addr1_cast_fu_482_p1.read();
}

void gaussian_sep::thread_tmp_addr4_fu_524_p2() {
    tmp_addr4_fu_524_p2 = (!tmp_addr4_fu_524_p0.read().is_01() || !tmp_21_trn_cast_fu_520_p1.read().is_01())? sc_lv<24>(): (sc_bigint<24>(tmp_addr4_fu_524_p0.read()) + sc_biguint<24>(tmp_21_trn_cast_fu_520_p1.read()));
}

void gaussian_sep::thread_tmp_address0() {
    if (esl_seteq<1,6,6>(ap_ST_st25_fsm_24, ap_CS_fsm.read())) {
        tmp_address0 =  (sc_lv<21>) (tmp_16_reg_571.read());
    } else if (esl_seteq<1,6,6>(ap_ST_st32_fsm_31, ap_CS_fsm.read())) {
        tmp_address0 =  (sc_lv<21>) (tmp_30_fu_533_p1.read());
    } else if (esl_seteq<1,6,6>(ap_ST_st27_fsm_26, ap_CS_fsm.read())) {
        tmp_address0 =  (sc_lv<21>) (tmp_28_fu_496_p1.read());
    } else {
        tmp_address0 =  (sc_lv<21>) (tmp_16_reg_571.read());
    }
}

void gaussian_sep::thread_tmp_address1() {
    tmp_address1 =  (sc_lv<21>) (tmp_29_fu_515_p1.read());
}

void gaussian_sep::thread_tmp_ce0() {
    if (((esl_seteq<1,6,6>(ap_ST_st27_fsm_26, ap_CS_fsm.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_442_p2.read())) || 
         esl_seteq<1,6,6>(ap_ST_st32_fsm_31, ap_CS_fsm.read()) || 
         esl_seteq<1,6,6>(ap_ST_st25_fsm_24, ap_CS_fsm.read()))) {
        tmp_ce0 = ap_const_logic_1;
    } else {
        tmp_ce0 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_tmp_ce1() {
    if ((esl_seteq<1,6,6>(ap_ST_st27_fsm_26, ap_CS_fsm.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_442_p2.read()))) {
        tmp_ce1 = ap_const_logic_1;
    } else {
        tmp_ce1 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_tmp_d0() {
    tmp_d0 = reg_216.read();
}

void gaussian_sep::thread_tmp_we0() {
    if ((esl_seteq<1,6,6>(ap_ST_st25_fsm_24, ap_CS_fsm.read()))) {
        tmp_we0 = ap_const_logic_1;
    } else {
        tmp_we0 = ap_const_logic_0;
    }
}

void gaussian_sep::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint()) {
        case 0 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_240_p2.read())) {
                ap_NS_fsm = ap_ST_st26_fsm_25;
            } else {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond2_fu_246_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        case 3 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 5 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 6 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 7 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 9 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 10 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 11 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 12 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 13 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 14 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 15 : 
            ap_NS_fsm = ap_ST_st17_fsm_16;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st18_fsm_17;
            break;
        case 17 : 
            ap_NS_fsm = ap_ST_st19_fsm_18;
            break;
        case 18 : 
            ap_NS_fsm = ap_ST_st20_fsm_19;
            break;
        case 19 : 
            ap_NS_fsm = ap_ST_st21_fsm_20;
            break;
        case 20 : 
            ap_NS_fsm = ap_ST_st22_fsm_21;
            break;
        case 21 : 
            ap_NS_fsm = ap_ST_st23_fsm_22;
            break;
        case 22 : 
            ap_NS_fsm = ap_ST_st24_fsm_23;
            break;
        case 23 : 
            ap_NS_fsm = ap_ST_st25_fsm_24;
            break;
        case 24 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 25 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_418_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st27_fsm_26;
            }
            break;
        case 26 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_442_p2.read())) {
                ap_NS_fsm = ap_ST_st28_fsm_27;
            } else {
                ap_NS_fsm = ap_ST_st26_fsm_25;
            }
            break;
        case 27 : 
            ap_NS_fsm = ap_ST_st29_fsm_28;
            break;
        case 28 : 
            ap_NS_fsm = ap_ST_st30_fsm_29;
            break;
        case 29 : 
            ap_NS_fsm = ap_ST_st31_fsm_30;
            break;
        case 30 : 
            ap_NS_fsm = ap_ST_st32_fsm_31;
            break;
        case 31 : 
            ap_NS_fsm = ap_ST_st33_fsm_32;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st34_fsm_33;
            break;
        case 33 : 
            ap_NS_fsm = ap_ST_st35_fsm_34;
            break;
        case 34 : 
            ap_NS_fsm = ap_ST_st36_fsm_35;
            break;
        case 35 : 
            ap_NS_fsm = ap_ST_st37_fsm_36;
            break;
        case 36 : 
            ap_NS_fsm = ap_ST_st38_fsm_37;
            break;
        case 37 : 
            ap_NS_fsm = ap_ST_st39_fsm_38;
            break;
        case 38 : 
            ap_NS_fsm = ap_ST_st40_fsm_39;
            break;
        case 39 : 
            ap_NS_fsm = ap_ST_st41_fsm_40;
            break;
        case 40 : 
            ap_NS_fsm = ap_ST_st42_fsm_41;
            break;
        case 41 : 
            ap_NS_fsm = ap_ST_st43_fsm_42;
            break;
        case 42 : 
            ap_NS_fsm = ap_ST_st44_fsm_43;
            break;
        case 43 : 
            ap_NS_fsm = ap_ST_st45_fsm_44;
            break;
        case 44 : 
            ap_NS_fsm = ap_ST_st46_fsm_45;
            break;
        case 45 : 
            ap_NS_fsm = ap_ST_st27_fsm_26;
            break;
        default : 
            ap_NS_fsm = "XXXXXX";
            break;
    }
}
}

